
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `brands` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model brands
 * This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info.
 */
export type brandsModel = runtime.Types.Result.DefaultSelection<Prisma.$brandsPayload>

export type AggregateBrands = {
  _count: BrandsCountAggregateOutputType | null
  _avg: BrandsAvgAggregateOutputType | null
  _sum: BrandsSumAggregateOutputType | null
  _min: BrandsMinAggregateOutputType | null
  _max: BrandsMaxAggregateOutputType | null
}

export type BrandsAvgAggregateOutputType = {
  id: number | null
}

export type BrandsSumAggregateOutputType = {
  id: number | null
}

export type BrandsMinAggregateOutputType = {
  id: number | null
  name: string | null
  description: string | null
  created_at: Date | null
}

export type BrandsMaxAggregateOutputType = {
  id: number | null
  name: string | null
  description: string | null
  created_at: Date | null
}

export type BrandsCountAggregateOutputType = {
  id: number
  name: number
  description: number
  created_at: number
  _all: number
}


export type BrandsAvgAggregateInputType = {
  id?: true
}

export type BrandsSumAggregateInputType = {
  id?: true
}

export type BrandsMinAggregateInputType = {
  id?: true
  name?: true
  description?: true
  created_at?: true
}

export type BrandsMaxAggregateInputType = {
  id?: true
  name?: true
  description?: true
  created_at?: true
}

export type BrandsCountAggregateInputType = {
  id?: true
  name?: true
  description?: true
  created_at?: true
  _all?: true
}

export type BrandsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which brands to aggregate.
   */
  where?: Prisma.brandsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of brands to fetch.
   */
  orderBy?: Prisma.brandsOrderByWithRelationInput | Prisma.brandsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.brandsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` brands from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` brands.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned brands
  **/
  _count?: true | BrandsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: BrandsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: BrandsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BrandsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BrandsMaxAggregateInputType
}

export type GetBrandsAggregateType<T extends BrandsAggregateArgs> = {
      [P in keyof T & keyof AggregateBrands]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBrands[P]>
    : Prisma.GetScalarType<T[P], AggregateBrands[P]>
}




export type brandsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.brandsWhereInput
  orderBy?: Prisma.brandsOrderByWithAggregationInput | Prisma.brandsOrderByWithAggregationInput[]
  by: Prisma.BrandsScalarFieldEnum[] | Prisma.BrandsScalarFieldEnum
  having?: Prisma.brandsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BrandsCountAggregateInputType | true
  _avg?: BrandsAvgAggregateInputType
  _sum?: BrandsSumAggregateInputType
  _min?: BrandsMinAggregateInputType
  _max?: BrandsMaxAggregateInputType
}

export type BrandsGroupByOutputType = {
  id: number
  name: string
  description: string | null
  created_at: Date | null
  _count: BrandsCountAggregateOutputType | null
  _avg: BrandsAvgAggregateOutputType | null
  _sum: BrandsSumAggregateOutputType | null
  _min: BrandsMinAggregateOutputType | null
  _max: BrandsMaxAggregateOutputType | null
}

type GetBrandsGroupByPayload<T extends brandsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BrandsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BrandsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BrandsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BrandsGroupByOutputType[P]>
      }
    >
  >



export type brandsWhereInput = {
  AND?: Prisma.brandsWhereInput | Prisma.brandsWhereInput[]
  OR?: Prisma.brandsWhereInput[]
  NOT?: Prisma.brandsWhereInput | Prisma.brandsWhereInput[]
  id?: Prisma.IntFilter<"brands"> | number
  name?: Prisma.StringFilter<"brands"> | string
  description?: Prisma.StringNullableFilter<"brands"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"brands"> | Date | string | null
  houses?: Prisma.HousesListRelationFilter
  rallies?: Prisma.RalliesListRelationFilter
}

export type brandsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  houses?: Prisma.housesOrderByRelationAggregateInput
  rallies?: Prisma.ralliesOrderByRelationAggregateInput
}

export type brandsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.brandsWhereInput | Prisma.brandsWhereInput[]
  OR?: Prisma.brandsWhereInput[]
  NOT?: Prisma.brandsWhereInput | Prisma.brandsWhereInput[]
  name?: Prisma.StringFilter<"brands"> | string
  description?: Prisma.StringNullableFilter<"brands"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"brands"> | Date | string | null
  houses?: Prisma.HousesListRelationFilter
  rallies?: Prisma.RalliesListRelationFilter
}, "id">

export type brandsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.brandsCountOrderByAggregateInput
  _avg?: Prisma.brandsAvgOrderByAggregateInput
  _max?: Prisma.brandsMaxOrderByAggregateInput
  _min?: Prisma.brandsMinOrderByAggregateInput
  _sum?: Prisma.brandsSumOrderByAggregateInput
}

export type brandsScalarWhereWithAggregatesInput = {
  AND?: Prisma.brandsScalarWhereWithAggregatesInput | Prisma.brandsScalarWhereWithAggregatesInput[]
  OR?: Prisma.brandsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.brandsScalarWhereWithAggregatesInput | Prisma.brandsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"brands"> | number
  name?: Prisma.StringWithAggregatesFilter<"brands"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"brands"> | string | null
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"brands"> | Date | string | null
}

export type brandsCreateInput = {
  name: string
  description?: string | null
  created_at?: Date | string | null
  houses?: Prisma.housesCreateNestedManyWithoutBrandsInput
  rallies?: Prisma.ralliesCreateNestedManyWithoutBrandsInput
}

export type brandsUncheckedCreateInput = {
  id?: number
  name: string
  description?: string | null
  created_at?: Date | string | null
  houses?: Prisma.housesUncheckedCreateNestedManyWithoutBrandsInput
  rallies?: Prisma.ralliesUncheckedCreateNestedManyWithoutBrandsInput
}

export type brandsUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  houses?: Prisma.housesUpdateManyWithoutBrandsNestedInput
  rallies?: Prisma.ralliesUpdateManyWithoutBrandsNestedInput
}

export type brandsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  houses?: Prisma.housesUncheckedUpdateManyWithoutBrandsNestedInput
  rallies?: Prisma.ralliesUncheckedUpdateManyWithoutBrandsNestedInput
}

export type brandsCreateManyInput = {
  id?: number
  name: string
  description?: string | null
  created_at?: Date | string | null
}

export type brandsUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type brandsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type brandsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type brandsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type brandsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type brandsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type brandsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type BrandsNullableScalarRelationFilter = {
  is?: Prisma.brandsWhereInput | null
  isNot?: Prisma.brandsWhereInput | null
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type brandsCreateNestedOneWithoutHousesInput = {
  create?: Prisma.XOR<Prisma.brandsCreateWithoutHousesInput, Prisma.brandsUncheckedCreateWithoutHousesInput>
  connectOrCreate?: Prisma.brandsCreateOrConnectWithoutHousesInput
  connect?: Prisma.brandsWhereUniqueInput
}

export type brandsUpdateOneWithoutHousesNestedInput = {
  create?: Prisma.XOR<Prisma.brandsCreateWithoutHousesInput, Prisma.brandsUncheckedCreateWithoutHousesInput>
  connectOrCreate?: Prisma.brandsCreateOrConnectWithoutHousesInput
  upsert?: Prisma.brandsUpsertWithoutHousesInput
  disconnect?: Prisma.brandsWhereInput | boolean
  delete?: Prisma.brandsWhereInput | boolean
  connect?: Prisma.brandsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.brandsUpdateToOneWithWhereWithoutHousesInput, Prisma.brandsUpdateWithoutHousesInput>, Prisma.brandsUncheckedUpdateWithoutHousesInput>
}

export type brandsCreateNestedOneWithoutRalliesInput = {
  create?: Prisma.XOR<Prisma.brandsCreateWithoutRalliesInput, Prisma.brandsUncheckedCreateWithoutRalliesInput>
  connectOrCreate?: Prisma.brandsCreateOrConnectWithoutRalliesInput
  connect?: Prisma.brandsWhereUniqueInput
}

export type brandsUpdateOneWithoutRalliesNestedInput = {
  create?: Prisma.XOR<Prisma.brandsCreateWithoutRalliesInput, Prisma.brandsUncheckedCreateWithoutRalliesInput>
  connectOrCreate?: Prisma.brandsCreateOrConnectWithoutRalliesInput
  upsert?: Prisma.brandsUpsertWithoutRalliesInput
  disconnect?: Prisma.brandsWhereInput | boolean
  delete?: Prisma.brandsWhereInput | boolean
  connect?: Prisma.brandsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.brandsUpdateToOneWithWhereWithoutRalliesInput, Prisma.brandsUpdateWithoutRalliesInput>, Prisma.brandsUncheckedUpdateWithoutRalliesInput>
}

export type brandsCreateWithoutHousesInput = {
  name: string
  description?: string | null
  created_at?: Date | string | null
  rallies?: Prisma.ralliesCreateNestedManyWithoutBrandsInput
}

export type brandsUncheckedCreateWithoutHousesInput = {
  id?: number
  name: string
  description?: string | null
  created_at?: Date | string | null
  rallies?: Prisma.ralliesUncheckedCreateNestedManyWithoutBrandsInput
}

export type brandsCreateOrConnectWithoutHousesInput = {
  where: Prisma.brandsWhereUniqueInput
  create: Prisma.XOR<Prisma.brandsCreateWithoutHousesInput, Prisma.brandsUncheckedCreateWithoutHousesInput>
}

export type brandsUpsertWithoutHousesInput = {
  update: Prisma.XOR<Prisma.brandsUpdateWithoutHousesInput, Prisma.brandsUncheckedUpdateWithoutHousesInput>
  create: Prisma.XOR<Prisma.brandsCreateWithoutHousesInput, Prisma.brandsUncheckedCreateWithoutHousesInput>
  where?: Prisma.brandsWhereInput
}

export type brandsUpdateToOneWithWhereWithoutHousesInput = {
  where?: Prisma.brandsWhereInput
  data: Prisma.XOR<Prisma.brandsUpdateWithoutHousesInput, Prisma.brandsUncheckedUpdateWithoutHousesInput>
}

export type brandsUpdateWithoutHousesInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rallies?: Prisma.ralliesUpdateManyWithoutBrandsNestedInput
}

export type brandsUncheckedUpdateWithoutHousesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rallies?: Prisma.ralliesUncheckedUpdateManyWithoutBrandsNestedInput
}

export type brandsCreateWithoutRalliesInput = {
  name: string
  description?: string | null
  created_at?: Date | string | null
  houses?: Prisma.housesCreateNestedManyWithoutBrandsInput
}

export type brandsUncheckedCreateWithoutRalliesInput = {
  id?: number
  name: string
  description?: string | null
  created_at?: Date | string | null
  houses?: Prisma.housesUncheckedCreateNestedManyWithoutBrandsInput
}

export type brandsCreateOrConnectWithoutRalliesInput = {
  where: Prisma.brandsWhereUniqueInput
  create: Prisma.XOR<Prisma.brandsCreateWithoutRalliesInput, Prisma.brandsUncheckedCreateWithoutRalliesInput>
}

export type brandsUpsertWithoutRalliesInput = {
  update: Prisma.XOR<Prisma.brandsUpdateWithoutRalliesInput, Prisma.brandsUncheckedUpdateWithoutRalliesInput>
  create: Prisma.XOR<Prisma.brandsCreateWithoutRalliesInput, Prisma.brandsUncheckedCreateWithoutRalliesInput>
  where?: Prisma.brandsWhereInput
}

export type brandsUpdateToOneWithWhereWithoutRalliesInput = {
  where?: Prisma.brandsWhereInput
  data: Prisma.XOR<Prisma.brandsUpdateWithoutRalliesInput, Prisma.brandsUncheckedUpdateWithoutRalliesInput>
}

export type brandsUpdateWithoutRalliesInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  houses?: Prisma.housesUpdateManyWithoutBrandsNestedInput
}

export type brandsUncheckedUpdateWithoutRalliesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  houses?: Prisma.housesUncheckedUpdateManyWithoutBrandsNestedInput
}


/**
 * Count Type BrandsCountOutputType
 */

export type BrandsCountOutputType = {
  houses: number
  rallies: number
}

export type BrandsCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  houses?: boolean | BrandsCountOutputTypeCountHousesArgs
  rallies?: boolean | BrandsCountOutputTypeCountRalliesArgs
}

/**
 * BrandsCountOutputType without action
 */
export type BrandsCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BrandsCountOutputType
   */
  select?: Prisma.BrandsCountOutputTypeSelect<ExtArgs> | null
}

/**
 * BrandsCountOutputType without action
 */
export type BrandsCountOutputTypeCountHousesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.housesWhereInput
}

/**
 * BrandsCountOutputType without action
 */
export type BrandsCountOutputTypeCountRalliesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ralliesWhereInput
}


export type brandsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  created_at?: boolean
  houses?: boolean | Prisma.brands$housesArgs<ExtArgs>
  rallies?: boolean | Prisma.brands$ralliesArgs<ExtArgs>
  _count?: boolean | Prisma.BrandsCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["brands"]>

export type brandsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  created_at?: boolean
}, ExtArgs["result"]["brands"]>

export type brandsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  description?: boolean
  created_at?: boolean
}, ExtArgs["result"]["brands"]>

export type brandsSelectScalar = {
  id?: boolean
  name?: boolean
  description?: boolean
  created_at?: boolean
}

export type brandsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "description" | "created_at", ExtArgs["result"]["brands"]>
export type brandsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  houses?: boolean | Prisma.brands$housesArgs<ExtArgs>
  rallies?: boolean | Prisma.brands$ralliesArgs<ExtArgs>
  _count?: boolean | Prisma.BrandsCountOutputTypeDefaultArgs<ExtArgs>
}
export type brandsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type brandsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $brandsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "brands"
  objects: {
    houses: Prisma.$housesPayload<ExtArgs>[]
    rallies: Prisma.$ralliesPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
    description: string | null
    created_at: Date | null
  }, ExtArgs["result"]["brands"]>
  composites: {}
}

export type brandsGetPayload<S extends boolean | null | undefined | brandsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$brandsPayload, S>

export type brandsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<brandsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BrandsCountAggregateInputType | true
  }

export interface brandsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['brands'], meta: { name: 'brands' } }
  /**
   * Find zero or one Brands that matches the filter.
   * @param {brandsFindUniqueArgs} args - Arguments to find a Brands
   * @example
   * // Get one Brands
   * const brands = await prisma.brands.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends brandsFindUniqueArgs>(args: Prisma.SelectSubset<T, brandsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__brandsClient<runtime.Types.Result.GetResult<Prisma.$brandsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Brands that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {brandsFindUniqueOrThrowArgs} args - Arguments to find a Brands
   * @example
   * // Get one Brands
   * const brands = await prisma.brands.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends brandsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, brandsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__brandsClient<runtime.Types.Result.GetResult<Prisma.$brandsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Brands that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {brandsFindFirstArgs} args - Arguments to find a Brands
   * @example
   * // Get one Brands
   * const brands = await prisma.brands.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends brandsFindFirstArgs>(args?: Prisma.SelectSubset<T, brandsFindFirstArgs<ExtArgs>>): Prisma.Prisma__brandsClient<runtime.Types.Result.GetResult<Prisma.$brandsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Brands that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {brandsFindFirstOrThrowArgs} args - Arguments to find a Brands
   * @example
   * // Get one Brands
   * const brands = await prisma.brands.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends brandsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, brandsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__brandsClient<runtime.Types.Result.GetResult<Prisma.$brandsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Brands that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {brandsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Brands
   * const brands = await prisma.brands.findMany()
   * 
   * // Get first 10 Brands
   * const brands = await prisma.brands.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const brandsWithIdOnly = await prisma.brands.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends brandsFindManyArgs>(args?: Prisma.SelectSubset<T, brandsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$brandsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Brands.
   * @param {brandsCreateArgs} args - Arguments to create a Brands.
   * @example
   * // Create one Brands
   * const Brands = await prisma.brands.create({
   *   data: {
   *     // ... data to create a Brands
   *   }
   * })
   * 
   */
  create<T extends brandsCreateArgs>(args: Prisma.SelectSubset<T, brandsCreateArgs<ExtArgs>>): Prisma.Prisma__brandsClient<runtime.Types.Result.GetResult<Prisma.$brandsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Brands.
   * @param {brandsCreateManyArgs} args - Arguments to create many Brands.
   * @example
   * // Create many Brands
   * const brands = await prisma.brands.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends brandsCreateManyArgs>(args?: Prisma.SelectSubset<T, brandsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Brands and returns the data saved in the database.
   * @param {brandsCreateManyAndReturnArgs} args - Arguments to create many Brands.
   * @example
   * // Create many Brands
   * const brands = await prisma.brands.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Brands and only return the `id`
   * const brandsWithIdOnly = await prisma.brands.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends brandsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, brandsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$brandsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Brands.
   * @param {brandsDeleteArgs} args - Arguments to delete one Brands.
   * @example
   * // Delete one Brands
   * const Brands = await prisma.brands.delete({
   *   where: {
   *     // ... filter to delete one Brands
   *   }
   * })
   * 
   */
  delete<T extends brandsDeleteArgs>(args: Prisma.SelectSubset<T, brandsDeleteArgs<ExtArgs>>): Prisma.Prisma__brandsClient<runtime.Types.Result.GetResult<Prisma.$brandsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Brands.
   * @param {brandsUpdateArgs} args - Arguments to update one Brands.
   * @example
   * // Update one Brands
   * const brands = await prisma.brands.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends brandsUpdateArgs>(args: Prisma.SelectSubset<T, brandsUpdateArgs<ExtArgs>>): Prisma.Prisma__brandsClient<runtime.Types.Result.GetResult<Prisma.$brandsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Brands.
   * @param {brandsDeleteManyArgs} args - Arguments to filter Brands to delete.
   * @example
   * // Delete a few Brands
   * const { count } = await prisma.brands.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends brandsDeleteManyArgs>(args?: Prisma.SelectSubset<T, brandsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Brands.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {brandsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Brands
   * const brands = await prisma.brands.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends brandsUpdateManyArgs>(args: Prisma.SelectSubset<T, brandsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Brands and returns the data updated in the database.
   * @param {brandsUpdateManyAndReturnArgs} args - Arguments to update many Brands.
   * @example
   * // Update many Brands
   * const brands = await prisma.brands.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Brands and only return the `id`
   * const brandsWithIdOnly = await prisma.brands.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends brandsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, brandsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$brandsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Brands.
   * @param {brandsUpsertArgs} args - Arguments to update or create a Brands.
   * @example
   * // Update or create a Brands
   * const brands = await prisma.brands.upsert({
   *   create: {
   *     // ... data to create a Brands
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Brands we want to update
   *   }
   * })
   */
  upsert<T extends brandsUpsertArgs>(args: Prisma.SelectSubset<T, brandsUpsertArgs<ExtArgs>>): Prisma.Prisma__brandsClient<runtime.Types.Result.GetResult<Prisma.$brandsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Brands.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {brandsCountArgs} args - Arguments to filter Brands to count.
   * @example
   * // Count the number of Brands
   * const count = await prisma.brands.count({
   *   where: {
   *     // ... the filter for the Brands we want to count
   *   }
   * })
  **/
  count<T extends brandsCountArgs>(
    args?: Prisma.Subset<T, brandsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BrandsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Brands.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BrandsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BrandsAggregateArgs>(args: Prisma.Subset<T, BrandsAggregateArgs>): Prisma.PrismaPromise<GetBrandsAggregateType<T>>

  /**
   * Group by Brands.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {brandsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends brandsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: brandsGroupByArgs['orderBy'] }
      : { orderBy?: brandsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, brandsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBrandsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the brands model
 */
readonly fields: brandsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for brands.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__brandsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  houses<T extends Prisma.brands$housesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.brands$housesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$housesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  rallies<T extends Prisma.brands$ralliesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.brands$ralliesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ralliesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the brands model
 */
export interface brandsFieldRefs {
  readonly id: Prisma.FieldRef<"brands", 'Int'>
  readonly name: Prisma.FieldRef<"brands", 'String'>
  readonly description: Prisma.FieldRef<"brands", 'String'>
  readonly created_at: Prisma.FieldRef<"brands", 'DateTime'>
}
    

// Custom InputTypes
/**
 * brands findUnique
 */
export type brandsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the brands
   */
  select?: Prisma.brandsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the brands
   */
  omit?: Prisma.brandsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.brandsInclude<ExtArgs> | null
  /**
   * Filter, which brands to fetch.
   */
  where: Prisma.brandsWhereUniqueInput
}

/**
 * brands findUniqueOrThrow
 */
export type brandsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the brands
   */
  select?: Prisma.brandsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the brands
   */
  omit?: Prisma.brandsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.brandsInclude<ExtArgs> | null
  /**
   * Filter, which brands to fetch.
   */
  where: Prisma.brandsWhereUniqueInput
}

/**
 * brands findFirst
 */
export type brandsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the brands
   */
  select?: Prisma.brandsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the brands
   */
  omit?: Prisma.brandsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.brandsInclude<ExtArgs> | null
  /**
   * Filter, which brands to fetch.
   */
  where?: Prisma.brandsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of brands to fetch.
   */
  orderBy?: Prisma.brandsOrderByWithRelationInput | Prisma.brandsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for brands.
   */
  cursor?: Prisma.brandsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` brands from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` brands.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of brands.
   */
  distinct?: Prisma.BrandsScalarFieldEnum | Prisma.BrandsScalarFieldEnum[]
}

/**
 * brands findFirstOrThrow
 */
export type brandsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the brands
   */
  select?: Prisma.brandsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the brands
   */
  omit?: Prisma.brandsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.brandsInclude<ExtArgs> | null
  /**
   * Filter, which brands to fetch.
   */
  where?: Prisma.brandsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of brands to fetch.
   */
  orderBy?: Prisma.brandsOrderByWithRelationInput | Prisma.brandsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for brands.
   */
  cursor?: Prisma.brandsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` brands from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` brands.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of brands.
   */
  distinct?: Prisma.BrandsScalarFieldEnum | Prisma.BrandsScalarFieldEnum[]
}

/**
 * brands findMany
 */
export type brandsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the brands
   */
  select?: Prisma.brandsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the brands
   */
  omit?: Prisma.brandsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.brandsInclude<ExtArgs> | null
  /**
   * Filter, which brands to fetch.
   */
  where?: Prisma.brandsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of brands to fetch.
   */
  orderBy?: Prisma.brandsOrderByWithRelationInput | Prisma.brandsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing brands.
   */
  cursor?: Prisma.brandsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` brands from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` brands.
   */
  skip?: number
  distinct?: Prisma.BrandsScalarFieldEnum | Prisma.BrandsScalarFieldEnum[]
}

/**
 * brands create
 */
export type brandsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the brands
   */
  select?: Prisma.brandsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the brands
   */
  omit?: Prisma.brandsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.brandsInclude<ExtArgs> | null
  /**
   * The data needed to create a brands.
   */
  data: Prisma.XOR<Prisma.brandsCreateInput, Prisma.brandsUncheckedCreateInput>
}

/**
 * brands createMany
 */
export type brandsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many brands.
   */
  data: Prisma.brandsCreateManyInput | Prisma.brandsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * brands createManyAndReturn
 */
export type brandsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the brands
   */
  select?: Prisma.brandsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the brands
   */
  omit?: Prisma.brandsOmit<ExtArgs> | null
  /**
   * The data used to create many brands.
   */
  data: Prisma.brandsCreateManyInput | Prisma.brandsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * brands update
 */
export type brandsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the brands
   */
  select?: Prisma.brandsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the brands
   */
  omit?: Prisma.brandsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.brandsInclude<ExtArgs> | null
  /**
   * The data needed to update a brands.
   */
  data: Prisma.XOR<Prisma.brandsUpdateInput, Prisma.brandsUncheckedUpdateInput>
  /**
   * Choose, which brands to update.
   */
  where: Prisma.brandsWhereUniqueInput
}

/**
 * brands updateMany
 */
export type brandsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update brands.
   */
  data: Prisma.XOR<Prisma.brandsUpdateManyMutationInput, Prisma.brandsUncheckedUpdateManyInput>
  /**
   * Filter which brands to update
   */
  where?: Prisma.brandsWhereInput
  /**
   * Limit how many brands to update.
   */
  limit?: number
}

/**
 * brands updateManyAndReturn
 */
export type brandsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the brands
   */
  select?: Prisma.brandsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the brands
   */
  omit?: Prisma.brandsOmit<ExtArgs> | null
  /**
   * The data used to update brands.
   */
  data: Prisma.XOR<Prisma.brandsUpdateManyMutationInput, Prisma.brandsUncheckedUpdateManyInput>
  /**
   * Filter which brands to update
   */
  where?: Prisma.brandsWhereInput
  /**
   * Limit how many brands to update.
   */
  limit?: number
}

/**
 * brands upsert
 */
export type brandsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the brands
   */
  select?: Prisma.brandsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the brands
   */
  omit?: Prisma.brandsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.brandsInclude<ExtArgs> | null
  /**
   * The filter to search for the brands to update in case it exists.
   */
  where: Prisma.brandsWhereUniqueInput
  /**
   * In case the brands found by the `where` argument doesn't exist, create a new brands with this data.
   */
  create: Prisma.XOR<Prisma.brandsCreateInput, Prisma.brandsUncheckedCreateInput>
  /**
   * In case the brands was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.brandsUpdateInput, Prisma.brandsUncheckedUpdateInput>
}

/**
 * brands delete
 */
export type brandsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the brands
   */
  select?: Prisma.brandsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the brands
   */
  omit?: Prisma.brandsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.brandsInclude<ExtArgs> | null
  /**
   * Filter which brands to delete.
   */
  where: Prisma.brandsWhereUniqueInput
}

/**
 * brands deleteMany
 */
export type brandsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which brands to delete
   */
  where?: Prisma.brandsWhereInput
  /**
   * Limit how many brands to delete.
   */
  limit?: number
}

/**
 * brands.houses
 */
export type brands$housesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the houses
   */
  select?: Prisma.housesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the houses
   */
  omit?: Prisma.housesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.housesInclude<ExtArgs> | null
  where?: Prisma.housesWhereInput
  orderBy?: Prisma.housesOrderByWithRelationInput | Prisma.housesOrderByWithRelationInput[]
  cursor?: Prisma.housesWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.HousesScalarFieldEnum | Prisma.HousesScalarFieldEnum[]
}

/**
 * brands.rallies
 */
export type brands$ralliesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the rallies
   */
  select?: Prisma.ralliesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the rallies
   */
  omit?: Prisma.ralliesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ralliesInclude<ExtArgs> | null
  where?: Prisma.ralliesWhereInput
  orderBy?: Prisma.ralliesOrderByWithRelationInput | Prisma.ralliesOrderByWithRelationInput[]
  cursor?: Prisma.ralliesWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RalliesScalarFieldEnum | Prisma.RalliesScalarFieldEnum[]
}

/**
 * brands without action
 */
export type brandsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the brands
   */
  select?: Prisma.brandsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the brands
   */
  omit?: Prisma.brandsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.brandsInclude<ExtArgs> | null
}
