
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `directivos` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model directivos
 * This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info.
 */
export type directivosModel = runtime.Types.Result.DefaultSelection<Prisma.$directivosPayload>

export type AggregateDirectivos = {
  _count: DirectivosCountAggregateOutputType | null
  _avg: DirectivosAvgAggregateOutputType | null
  _sum: DirectivosSumAggregateOutputType | null
  _min: DirectivosMinAggregateOutputType | null
  _max: DirectivosMaxAggregateOutputType | null
}

export type DirectivosAvgAggregateOutputType = {
  id: number | null
  house_id: number | null
  member_id: number | null
}

export type DirectivosSumAggregateOutputType = {
  id: number | null
  house_id: number | null
  member_id: number | null
}

export type DirectivosMinAggregateOutputType = {
  id: number | null
  house_id: number | null
  member_id: number | null
  role: string | null
  start_date: Date | null
  end_date: Date | null
}

export type DirectivosMaxAggregateOutputType = {
  id: number | null
  house_id: number | null
  member_id: number | null
  role: string | null
  start_date: Date | null
  end_date: Date | null
}

export type DirectivosCountAggregateOutputType = {
  id: number
  house_id: number
  member_id: number
  role: number
  start_date: number
  end_date: number
  _all: number
}


export type DirectivosAvgAggregateInputType = {
  id?: true
  house_id?: true
  member_id?: true
}

export type DirectivosSumAggregateInputType = {
  id?: true
  house_id?: true
  member_id?: true
}

export type DirectivosMinAggregateInputType = {
  id?: true
  house_id?: true
  member_id?: true
  role?: true
  start_date?: true
  end_date?: true
}

export type DirectivosMaxAggregateInputType = {
  id?: true
  house_id?: true
  member_id?: true
  role?: true
  start_date?: true
  end_date?: true
}

export type DirectivosCountAggregateInputType = {
  id?: true
  house_id?: true
  member_id?: true
  role?: true
  start_date?: true
  end_date?: true
  _all?: true
}

export type DirectivosAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which directivos to aggregate.
   */
  where?: Prisma.directivosWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of directivos to fetch.
   */
  orderBy?: Prisma.directivosOrderByWithRelationInput | Prisma.directivosOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.directivosWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` directivos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` directivos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned directivos
  **/
  _count?: true | DirectivosCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: DirectivosAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: DirectivosSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: DirectivosMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: DirectivosMaxAggregateInputType
}

export type GetDirectivosAggregateType<T extends DirectivosAggregateArgs> = {
      [P in keyof T & keyof AggregateDirectivos]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateDirectivos[P]>
    : Prisma.GetScalarType<T[P], AggregateDirectivos[P]>
}




export type directivosGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.directivosWhereInput
  orderBy?: Prisma.directivosOrderByWithAggregationInput | Prisma.directivosOrderByWithAggregationInput[]
  by: Prisma.DirectivosScalarFieldEnum[] | Prisma.DirectivosScalarFieldEnum
  having?: Prisma.directivosScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: DirectivosCountAggregateInputType | true
  _avg?: DirectivosAvgAggregateInputType
  _sum?: DirectivosSumAggregateInputType
  _min?: DirectivosMinAggregateInputType
  _max?: DirectivosMaxAggregateInputType
}

export type DirectivosGroupByOutputType = {
  id: number
  house_id: number | null
  member_id: number | null
  role: string
  start_date: Date | null
  end_date: Date | null
  _count: DirectivosCountAggregateOutputType | null
  _avg: DirectivosAvgAggregateOutputType | null
  _sum: DirectivosSumAggregateOutputType | null
  _min: DirectivosMinAggregateOutputType | null
  _max: DirectivosMaxAggregateOutputType | null
}

type GetDirectivosGroupByPayload<T extends directivosGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<DirectivosGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof DirectivosGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], DirectivosGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], DirectivosGroupByOutputType[P]>
      }
    >
  >



export type directivosWhereInput = {
  AND?: Prisma.directivosWhereInput | Prisma.directivosWhereInput[]
  OR?: Prisma.directivosWhereInput[]
  NOT?: Prisma.directivosWhereInput | Prisma.directivosWhereInput[]
  id?: Prisma.IntFilter<"directivos"> | number
  house_id?: Prisma.IntNullableFilter<"directivos"> | number | null
  member_id?: Prisma.IntNullableFilter<"directivos"> | number | null
  role?: Prisma.StringFilter<"directivos"> | string
  start_date?: Prisma.DateTimeNullableFilter<"directivos"> | Date | string | null
  end_date?: Prisma.DateTimeNullableFilter<"directivos"> | Date | string | null
  houses?: Prisma.XOR<Prisma.HousesNullableScalarRelationFilter, Prisma.housesWhereInput> | null
  members?: Prisma.XOR<Prisma.MembersNullableScalarRelationFilter, Prisma.membersWhereInput> | null
}

export type directivosOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  house_id?: Prisma.SortOrderInput | Prisma.SortOrder
  member_id?: Prisma.SortOrderInput | Prisma.SortOrder
  role?: Prisma.SortOrder
  start_date?: Prisma.SortOrderInput | Prisma.SortOrder
  end_date?: Prisma.SortOrderInput | Prisma.SortOrder
  houses?: Prisma.housesOrderByWithRelationInput
  members?: Prisma.membersOrderByWithRelationInput
}

export type directivosWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.directivosWhereInput | Prisma.directivosWhereInput[]
  OR?: Prisma.directivosWhereInput[]
  NOT?: Prisma.directivosWhereInput | Prisma.directivosWhereInput[]
  house_id?: Prisma.IntNullableFilter<"directivos"> | number | null
  member_id?: Prisma.IntNullableFilter<"directivos"> | number | null
  role?: Prisma.StringFilter<"directivos"> | string
  start_date?: Prisma.DateTimeNullableFilter<"directivos"> | Date | string | null
  end_date?: Prisma.DateTimeNullableFilter<"directivos"> | Date | string | null
  houses?: Prisma.XOR<Prisma.HousesNullableScalarRelationFilter, Prisma.housesWhereInput> | null
  members?: Prisma.XOR<Prisma.MembersNullableScalarRelationFilter, Prisma.membersWhereInput> | null
}, "id">

export type directivosOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  house_id?: Prisma.SortOrderInput | Prisma.SortOrder
  member_id?: Prisma.SortOrderInput | Prisma.SortOrder
  role?: Prisma.SortOrder
  start_date?: Prisma.SortOrderInput | Prisma.SortOrder
  end_date?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.directivosCountOrderByAggregateInput
  _avg?: Prisma.directivosAvgOrderByAggregateInput
  _max?: Prisma.directivosMaxOrderByAggregateInput
  _min?: Prisma.directivosMinOrderByAggregateInput
  _sum?: Prisma.directivosSumOrderByAggregateInput
}

export type directivosScalarWhereWithAggregatesInput = {
  AND?: Prisma.directivosScalarWhereWithAggregatesInput | Prisma.directivosScalarWhereWithAggregatesInput[]
  OR?: Prisma.directivosScalarWhereWithAggregatesInput[]
  NOT?: Prisma.directivosScalarWhereWithAggregatesInput | Prisma.directivosScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"directivos"> | number
  house_id?: Prisma.IntNullableWithAggregatesFilter<"directivos"> | number | null
  member_id?: Prisma.IntNullableWithAggregatesFilter<"directivos"> | number | null
  role?: Prisma.StringWithAggregatesFilter<"directivos"> | string
  start_date?: Prisma.DateTimeNullableWithAggregatesFilter<"directivos"> | Date | string | null
  end_date?: Prisma.DateTimeNullableWithAggregatesFilter<"directivos"> | Date | string | null
}

export type directivosCreateInput = {
  role: string
  start_date?: Date | string | null
  end_date?: Date | string | null
  houses?: Prisma.housesCreateNestedOneWithoutDirectivosInput
  members?: Prisma.membersCreateNestedOneWithoutDirectivosInput
}

export type directivosUncheckedCreateInput = {
  id?: number
  house_id?: number | null
  member_id?: number | null
  role: string
  start_date?: Date | string | null
  end_date?: Date | string | null
}

export type directivosUpdateInput = {
  role?: Prisma.StringFieldUpdateOperationsInput | string
  start_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  end_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  houses?: Prisma.housesUpdateOneWithoutDirectivosNestedInput
  members?: Prisma.membersUpdateOneWithoutDirectivosNestedInput
}

export type directivosUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  house_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  member_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  start_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  end_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type directivosCreateManyInput = {
  id?: number
  house_id?: number | null
  member_id?: number | null
  role: string
  start_date?: Date | string | null
  end_date?: Date | string | null
}

export type directivosUpdateManyMutationInput = {
  role?: Prisma.StringFieldUpdateOperationsInput | string
  start_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  end_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type directivosUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  house_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  member_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  start_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  end_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type directivosCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  house_id?: Prisma.SortOrder
  member_id?: Prisma.SortOrder
  role?: Prisma.SortOrder
  start_date?: Prisma.SortOrder
  end_date?: Prisma.SortOrder
}

export type directivosAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  house_id?: Prisma.SortOrder
  member_id?: Prisma.SortOrder
}

export type directivosMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  house_id?: Prisma.SortOrder
  member_id?: Prisma.SortOrder
  role?: Prisma.SortOrder
  start_date?: Prisma.SortOrder
  end_date?: Prisma.SortOrder
}

export type directivosMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  house_id?: Prisma.SortOrder
  member_id?: Prisma.SortOrder
  role?: Prisma.SortOrder
  start_date?: Prisma.SortOrder
  end_date?: Prisma.SortOrder
}

export type directivosSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  house_id?: Prisma.SortOrder
  member_id?: Prisma.SortOrder
}

export type DirectivosListRelationFilter = {
  every?: Prisma.directivosWhereInput
  some?: Prisma.directivosWhereInput
  none?: Prisma.directivosWhereInput
}

export type directivosOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type directivosCreateNestedManyWithoutHousesInput = {
  create?: Prisma.XOR<Prisma.directivosCreateWithoutHousesInput, Prisma.directivosUncheckedCreateWithoutHousesInput> | Prisma.directivosCreateWithoutHousesInput[] | Prisma.directivosUncheckedCreateWithoutHousesInput[]
  connectOrCreate?: Prisma.directivosCreateOrConnectWithoutHousesInput | Prisma.directivosCreateOrConnectWithoutHousesInput[]
  createMany?: Prisma.directivosCreateManyHousesInputEnvelope
  connect?: Prisma.directivosWhereUniqueInput | Prisma.directivosWhereUniqueInput[]
}

export type directivosUncheckedCreateNestedManyWithoutHousesInput = {
  create?: Prisma.XOR<Prisma.directivosCreateWithoutHousesInput, Prisma.directivosUncheckedCreateWithoutHousesInput> | Prisma.directivosCreateWithoutHousesInput[] | Prisma.directivosUncheckedCreateWithoutHousesInput[]
  connectOrCreate?: Prisma.directivosCreateOrConnectWithoutHousesInput | Prisma.directivosCreateOrConnectWithoutHousesInput[]
  createMany?: Prisma.directivosCreateManyHousesInputEnvelope
  connect?: Prisma.directivosWhereUniqueInput | Prisma.directivosWhereUniqueInput[]
}

export type directivosUpdateManyWithoutHousesNestedInput = {
  create?: Prisma.XOR<Prisma.directivosCreateWithoutHousesInput, Prisma.directivosUncheckedCreateWithoutHousesInput> | Prisma.directivosCreateWithoutHousesInput[] | Prisma.directivosUncheckedCreateWithoutHousesInput[]
  connectOrCreate?: Prisma.directivosCreateOrConnectWithoutHousesInput | Prisma.directivosCreateOrConnectWithoutHousesInput[]
  upsert?: Prisma.directivosUpsertWithWhereUniqueWithoutHousesInput | Prisma.directivosUpsertWithWhereUniqueWithoutHousesInput[]
  createMany?: Prisma.directivosCreateManyHousesInputEnvelope
  set?: Prisma.directivosWhereUniqueInput | Prisma.directivosWhereUniqueInput[]
  disconnect?: Prisma.directivosWhereUniqueInput | Prisma.directivosWhereUniqueInput[]
  delete?: Prisma.directivosWhereUniqueInput | Prisma.directivosWhereUniqueInput[]
  connect?: Prisma.directivosWhereUniqueInput | Prisma.directivosWhereUniqueInput[]
  update?: Prisma.directivosUpdateWithWhereUniqueWithoutHousesInput | Prisma.directivosUpdateWithWhereUniqueWithoutHousesInput[]
  updateMany?: Prisma.directivosUpdateManyWithWhereWithoutHousesInput | Prisma.directivosUpdateManyWithWhereWithoutHousesInput[]
  deleteMany?: Prisma.directivosScalarWhereInput | Prisma.directivosScalarWhereInput[]
}

export type directivosUncheckedUpdateManyWithoutHousesNestedInput = {
  create?: Prisma.XOR<Prisma.directivosCreateWithoutHousesInput, Prisma.directivosUncheckedCreateWithoutHousesInput> | Prisma.directivosCreateWithoutHousesInput[] | Prisma.directivosUncheckedCreateWithoutHousesInput[]
  connectOrCreate?: Prisma.directivosCreateOrConnectWithoutHousesInput | Prisma.directivosCreateOrConnectWithoutHousesInput[]
  upsert?: Prisma.directivosUpsertWithWhereUniqueWithoutHousesInput | Prisma.directivosUpsertWithWhereUniqueWithoutHousesInput[]
  createMany?: Prisma.directivosCreateManyHousesInputEnvelope
  set?: Prisma.directivosWhereUniqueInput | Prisma.directivosWhereUniqueInput[]
  disconnect?: Prisma.directivosWhereUniqueInput | Prisma.directivosWhereUniqueInput[]
  delete?: Prisma.directivosWhereUniqueInput | Prisma.directivosWhereUniqueInput[]
  connect?: Prisma.directivosWhereUniqueInput | Prisma.directivosWhereUniqueInput[]
  update?: Prisma.directivosUpdateWithWhereUniqueWithoutHousesInput | Prisma.directivosUpdateWithWhereUniqueWithoutHousesInput[]
  updateMany?: Prisma.directivosUpdateManyWithWhereWithoutHousesInput | Prisma.directivosUpdateManyWithWhereWithoutHousesInput[]
  deleteMany?: Prisma.directivosScalarWhereInput | Prisma.directivosScalarWhereInput[]
}

export type directivosCreateNestedManyWithoutMembersInput = {
  create?: Prisma.XOR<Prisma.directivosCreateWithoutMembersInput, Prisma.directivosUncheckedCreateWithoutMembersInput> | Prisma.directivosCreateWithoutMembersInput[] | Prisma.directivosUncheckedCreateWithoutMembersInput[]
  connectOrCreate?: Prisma.directivosCreateOrConnectWithoutMembersInput | Prisma.directivosCreateOrConnectWithoutMembersInput[]
  createMany?: Prisma.directivosCreateManyMembersInputEnvelope
  connect?: Prisma.directivosWhereUniqueInput | Prisma.directivosWhereUniqueInput[]
}

export type directivosUncheckedCreateNestedManyWithoutMembersInput = {
  create?: Prisma.XOR<Prisma.directivosCreateWithoutMembersInput, Prisma.directivosUncheckedCreateWithoutMembersInput> | Prisma.directivosCreateWithoutMembersInput[] | Prisma.directivosUncheckedCreateWithoutMembersInput[]
  connectOrCreate?: Prisma.directivosCreateOrConnectWithoutMembersInput | Prisma.directivosCreateOrConnectWithoutMembersInput[]
  createMany?: Prisma.directivosCreateManyMembersInputEnvelope
  connect?: Prisma.directivosWhereUniqueInput | Prisma.directivosWhereUniqueInput[]
}

export type directivosUpdateManyWithoutMembersNestedInput = {
  create?: Prisma.XOR<Prisma.directivosCreateWithoutMembersInput, Prisma.directivosUncheckedCreateWithoutMembersInput> | Prisma.directivosCreateWithoutMembersInput[] | Prisma.directivosUncheckedCreateWithoutMembersInput[]
  connectOrCreate?: Prisma.directivosCreateOrConnectWithoutMembersInput | Prisma.directivosCreateOrConnectWithoutMembersInput[]
  upsert?: Prisma.directivosUpsertWithWhereUniqueWithoutMembersInput | Prisma.directivosUpsertWithWhereUniqueWithoutMembersInput[]
  createMany?: Prisma.directivosCreateManyMembersInputEnvelope
  set?: Prisma.directivosWhereUniqueInput | Prisma.directivosWhereUniqueInput[]
  disconnect?: Prisma.directivosWhereUniqueInput | Prisma.directivosWhereUniqueInput[]
  delete?: Prisma.directivosWhereUniqueInput | Prisma.directivosWhereUniqueInput[]
  connect?: Prisma.directivosWhereUniqueInput | Prisma.directivosWhereUniqueInput[]
  update?: Prisma.directivosUpdateWithWhereUniqueWithoutMembersInput | Prisma.directivosUpdateWithWhereUniqueWithoutMembersInput[]
  updateMany?: Prisma.directivosUpdateManyWithWhereWithoutMembersInput | Prisma.directivosUpdateManyWithWhereWithoutMembersInput[]
  deleteMany?: Prisma.directivosScalarWhereInput | Prisma.directivosScalarWhereInput[]
}

export type directivosUncheckedUpdateManyWithoutMembersNestedInput = {
  create?: Prisma.XOR<Prisma.directivosCreateWithoutMembersInput, Prisma.directivosUncheckedCreateWithoutMembersInput> | Prisma.directivosCreateWithoutMembersInput[] | Prisma.directivosUncheckedCreateWithoutMembersInput[]
  connectOrCreate?: Prisma.directivosCreateOrConnectWithoutMembersInput | Prisma.directivosCreateOrConnectWithoutMembersInput[]
  upsert?: Prisma.directivosUpsertWithWhereUniqueWithoutMembersInput | Prisma.directivosUpsertWithWhereUniqueWithoutMembersInput[]
  createMany?: Prisma.directivosCreateManyMembersInputEnvelope
  set?: Prisma.directivosWhereUniqueInput | Prisma.directivosWhereUniqueInput[]
  disconnect?: Prisma.directivosWhereUniqueInput | Prisma.directivosWhereUniqueInput[]
  delete?: Prisma.directivosWhereUniqueInput | Prisma.directivosWhereUniqueInput[]
  connect?: Prisma.directivosWhereUniqueInput | Prisma.directivosWhereUniqueInput[]
  update?: Prisma.directivosUpdateWithWhereUniqueWithoutMembersInput | Prisma.directivosUpdateWithWhereUniqueWithoutMembersInput[]
  updateMany?: Prisma.directivosUpdateManyWithWhereWithoutMembersInput | Prisma.directivosUpdateManyWithWhereWithoutMembersInput[]
  deleteMany?: Prisma.directivosScalarWhereInput | Prisma.directivosScalarWhereInput[]
}

export type directivosCreateWithoutHousesInput = {
  role: string
  start_date?: Date | string | null
  end_date?: Date | string | null
  members?: Prisma.membersCreateNestedOneWithoutDirectivosInput
}

export type directivosUncheckedCreateWithoutHousesInput = {
  id?: number
  member_id?: number | null
  role: string
  start_date?: Date | string | null
  end_date?: Date | string | null
}

export type directivosCreateOrConnectWithoutHousesInput = {
  where: Prisma.directivosWhereUniqueInput
  create: Prisma.XOR<Prisma.directivosCreateWithoutHousesInput, Prisma.directivosUncheckedCreateWithoutHousesInput>
}

export type directivosCreateManyHousesInputEnvelope = {
  data: Prisma.directivosCreateManyHousesInput | Prisma.directivosCreateManyHousesInput[]
  skipDuplicates?: boolean
}

export type directivosUpsertWithWhereUniqueWithoutHousesInput = {
  where: Prisma.directivosWhereUniqueInput
  update: Prisma.XOR<Prisma.directivosUpdateWithoutHousesInput, Prisma.directivosUncheckedUpdateWithoutHousesInput>
  create: Prisma.XOR<Prisma.directivosCreateWithoutHousesInput, Prisma.directivosUncheckedCreateWithoutHousesInput>
}

export type directivosUpdateWithWhereUniqueWithoutHousesInput = {
  where: Prisma.directivosWhereUniqueInput
  data: Prisma.XOR<Prisma.directivosUpdateWithoutHousesInput, Prisma.directivosUncheckedUpdateWithoutHousesInput>
}

export type directivosUpdateManyWithWhereWithoutHousesInput = {
  where: Prisma.directivosScalarWhereInput
  data: Prisma.XOR<Prisma.directivosUpdateManyMutationInput, Prisma.directivosUncheckedUpdateManyWithoutHousesInput>
}

export type directivosScalarWhereInput = {
  AND?: Prisma.directivosScalarWhereInput | Prisma.directivosScalarWhereInput[]
  OR?: Prisma.directivosScalarWhereInput[]
  NOT?: Prisma.directivosScalarWhereInput | Prisma.directivosScalarWhereInput[]
  id?: Prisma.IntFilter<"directivos"> | number
  house_id?: Prisma.IntNullableFilter<"directivos"> | number | null
  member_id?: Prisma.IntNullableFilter<"directivos"> | number | null
  role?: Prisma.StringFilter<"directivos"> | string
  start_date?: Prisma.DateTimeNullableFilter<"directivos"> | Date | string | null
  end_date?: Prisma.DateTimeNullableFilter<"directivos"> | Date | string | null
}

export type directivosCreateWithoutMembersInput = {
  role: string
  start_date?: Date | string | null
  end_date?: Date | string | null
  houses?: Prisma.housesCreateNestedOneWithoutDirectivosInput
}

export type directivosUncheckedCreateWithoutMembersInput = {
  id?: number
  house_id?: number | null
  role: string
  start_date?: Date | string | null
  end_date?: Date | string | null
}

export type directivosCreateOrConnectWithoutMembersInput = {
  where: Prisma.directivosWhereUniqueInput
  create: Prisma.XOR<Prisma.directivosCreateWithoutMembersInput, Prisma.directivosUncheckedCreateWithoutMembersInput>
}

export type directivosCreateManyMembersInputEnvelope = {
  data: Prisma.directivosCreateManyMembersInput | Prisma.directivosCreateManyMembersInput[]
  skipDuplicates?: boolean
}

export type directivosUpsertWithWhereUniqueWithoutMembersInput = {
  where: Prisma.directivosWhereUniqueInput
  update: Prisma.XOR<Prisma.directivosUpdateWithoutMembersInput, Prisma.directivosUncheckedUpdateWithoutMembersInput>
  create: Prisma.XOR<Prisma.directivosCreateWithoutMembersInput, Prisma.directivosUncheckedCreateWithoutMembersInput>
}

export type directivosUpdateWithWhereUniqueWithoutMembersInput = {
  where: Prisma.directivosWhereUniqueInput
  data: Prisma.XOR<Prisma.directivosUpdateWithoutMembersInput, Prisma.directivosUncheckedUpdateWithoutMembersInput>
}

export type directivosUpdateManyWithWhereWithoutMembersInput = {
  where: Prisma.directivosScalarWhereInput
  data: Prisma.XOR<Prisma.directivosUpdateManyMutationInput, Prisma.directivosUncheckedUpdateManyWithoutMembersInput>
}

export type directivosCreateManyHousesInput = {
  id?: number
  member_id?: number | null
  role: string
  start_date?: Date | string | null
  end_date?: Date | string | null
}

export type directivosUpdateWithoutHousesInput = {
  role?: Prisma.StringFieldUpdateOperationsInput | string
  start_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  end_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  members?: Prisma.membersUpdateOneWithoutDirectivosNestedInput
}

export type directivosUncheckedUpdateWithoutHousesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  member_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  start_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  end_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type directivosUncheckedUpdateManyWithoutHousesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  member_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  start_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  end_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type directivosCreateManyMembersInput = {
  id?: number
  house_id?: number | null
  role: string
  start_date?: Date | string | null
  end_date?: Date | string | null
}

export type directivosUpdateWithoutMembersInput = {
  role?: Prisma.StringFieldUpdateOperationsInput | string
  start_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  end_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  houses?: Prisma.housesUpdateOneWithoutDirectivosNestedInput
}

export type directivosUncheckedUpdateWithoutMembersInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  house_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  start_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  end_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type directivosUncheckedUpdateManyWithoutMembersInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  house_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  role?: Prisma.StringFieldUpdateOperationsInput | string
  start_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  end_date?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type directivosSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  house_id?: boolean
  member_id?: boolean
  role?: boolean
  start_date?: boolean
  end_date?: boolean
  houses?: boolean | Prisma.directivos$housesArgs<ExtArgs>
  members?: boolean | Prisma.directivos$membersArgs<ExtArgs>
}, ExtArgs["result"]["directivos"]>

export type directivosSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  house_id?: boolean
  member_id?: boolean
  role?: boolean
  start_date?: boolean
  end_date?: boolean
  houses?: boolean | Prisma.directivos$housesArgs<ExtArgs>
  members?: boolean | Prisma.directivos$membersArgs<ExtArgs>
}, ExtArgs["result"]["directivos"]>

export type directivosSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  house_id?: boolean
  member_id?: boolean
  role?: boolean
  start_date?: boolean
  end_date?: boolean
  houses?: boolean | Prisma.directivos$housesArgs<ExtArgs>
  members?: boolean | Prisma.directivos$membersArgs<ExtArgs>
}, ExtArgs["result"]["directivos"]>

export type directivosSelectScalar = {
  id?: boolean
  house_id?: boolean
  member_id?: boolean
  role?: boolean
  start_date?: boolean
  end_date?: boolean
}

export type directivosOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "house_id" | "member_id" | "role" | "start_date" | "end_date", ExtArgs["result"]["directivos"]>
export type directivosInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  houses?: boolean | Prisma.directivos$housesArgs<ExtArgs>
  members?: boolean | Prisma.directivos$membersArgs<ExtArgs>
}
export type directivosIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  houses?: boolean | Prisma.directivos$housesArgs<ExtArgs>
  members?: boolean | Prisma.directivos$membersArgs<ExtArgs>
}
export type directivosIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  houses?: boolean | Prisma.directivos$housesArgs<ExtArgs>
  members?: boolean | Prisma.directivos$membersArgs<ExtArgs>
}

export type $directivosPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "directivos"
  objects: {
    houses: Prisma.$housesPayload<ExtArgs> | null
    members: Prisma.$membersPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    house_id: number | null
    member_id: number | null
    role: string
    start_date: Date | null
    end_date: Date | null
  }, ExtArgs["result"]["directivos"]>
  composites: {}
}

export type directivosGetPayload<S extends boolean | null | undefined | directivosDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$directivosPayload, S>

export type directivosCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<directivosFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: DirectivosCountAggregateInputType | true
  }

export interface directivosDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['directivos'], meta: { name: 'directivos' } }
  /**
   * Find zero or one Directivos that matches the filter.
   * @param {directivosFindUniqueArgs} args - Arguments to find a Directivos
   * @example
   * // Get one Directivos
   * const directivos = await prisma.directivos.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends directivosFindUniqueArgs>(args: Prisma.SelectSubset<T, directivosFindUniqueArgs<ExtArgs>>): Prisma.Prisma__directivosClient<runtime.Types.Result.GetResult<Prisma.$directivosPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Directivos that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {directivosFindUniqueOrThrowArgs} args - Arguments to find a Directivos
   * @example
   * // Get one Directivos
   * const directivos = await prisma.directivos.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends directivosFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, directivosFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__directivosClient<runtime.Types.Result.GetResult<Prisma.$directivosPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Directivos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {directivosFindFirstArgs} args - Arguments to find a Directivos
   * @example
   * // Get one Directivos
   * const directivos = await prisma.directivos.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends directivosFindFirstArgs>(args?: Prisma.SelectSubset<T, directivosFindFirstArgs<ExtArgs>>): Prisma.Prisma__directivosClient<runtime.Types.Result.GetResult<Prisma.$directivosPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Directivos that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {directivosFindFirstOrThrowArgs} args - Arguments to find a Directivos
   * @example
   * // Get one Directivos
   * const directivos = await prisma.directivos.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends directivosFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, directivosFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__directivosClient<runtime.Types.Result.GetResult<Prisma.$directivosPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Directivos that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {directivosFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Directivos
   * const directivos = await prisma.directivos.findMany()
   * 
   * // Get first 10 Directivos
   * const directivos = await prisma.directivos.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const directivosWithIdOnly = await prisma.directivos.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends directivosFindManyArgs>(args?: Prisma.SelectSubset<T, directivosFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$directivosPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Directivos.
   * @param {directivosCreateArgs} args - Arguments to create a Directivos.
   * @example
   * // Create one Directivos
   * const Directivos = await prisma.directivos.create({
   *   data: {
   *     // ... data to create a Directivos
   *   }
   * })
   * 
   */
  create<T extends directivosCreateArgs>(args: Prisma.SelectSubset<T, directivosCreateArgs<ExtArgs>>): Prisma.Prisma__directivosClient<runtime.Types.Result.GetResult<Prisma.$directivosPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Directivos.
   * @param {directivosCreateManyArgs} args - Arguments to create many Directivos.
   * @example
   * // Create many Directivos
   * const directivos = await prisma.directivos.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends directivosCreateManyArgs>(args?: Prisma.SelectSubset<T, directivosCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Directivos and returns the data saved in the database.
   * @param {directivosCreateManyAndReturnArgs} args - Arguments to create many Directivos.
   * @example
   * // Create many Directivos
   * const directivos = await prisma.directivos.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Directivos and only return the `id`
   * const directivosWithIdOnly = await prisma.directivos.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends directivosCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, directivosCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$directivosPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Directivos.
   * @param {directivosDeleteArgs} args - Arguments to delete one Directivos.
   * @example
   * // Delete one Directivos
   * const Directivos = await prisma.directivos.delete({
   *   where: {
   *     // ... filter to delete one Directivos
   *   }
   * })
   * 
   */
  delete<T extends directivosDeleteArgs>(args: Prisma.SelectSubset<T, directivosDeleteArgs<ExtArgs>>): Prisma.Prisma__directivosClient<runtime.Types.Result.GetResult<Prisma.$directivosPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Directivos.
   * @param {directivosUpdateArgs} args - Arguments to update one Directivos.
   * @example
   * // Update one Directivos
   * const directivos = await prisma.directivos.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends directivosUpdateArgs>(args: Prisma.SelectSubset<T, directivosUpdateArgs<ExtArgs>>): Prisma.Prisma__directivosClient<runtime.Types.Result.GetResult<Prisma.$directivosPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Directivos.
   * @param {directivosDeleteManyArgs} args - Arguments to filter Directivos to delete.
   * @example
   * // Delete a few Directivos
   * const { count } = await prisma.directivos.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends directivosDeleteManyArgs>(args?: Prisma.SelectSubset<T, directivosDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Directivos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {directivosUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Directivos
   * const directivos = await prisma.directivos.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends directivosUpdateManyArgs>(args: Prisma.SelectSubset<T, directivosUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Directivos and returns the data updated in the database.
   * @param {directivosUpdateManyAndReturnArgs} args - Arguments to update many Directivos.
   * @example
   * // Update many Directivos
   * const directivos = await prisma.directivos.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Directivos and only return the `id`
   * const directivosWithIdOnly = await prisma.directivos.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends directivosUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, directivosUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$directivosPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Directivos.
   * @param {directivosUpsertArgs} args - Arguments to update or create a Directivos.
   * @example
   * // Update or create a Directivos
   * const directivos = await prisma.directivos.upsert({
   *   create: {
   *     // ... data to create a Directivos
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Directivos we want to update
   *   }
   * })
   */
  upsert<T extends directivosUpsertArgs>(args: Prisma.SelectSubset<T, directivosUpsertArgs<ExtArgs>>): Prisma.Prisma__directivosClient<runtime.Types.Result.GetResult<Prisma.$directivosPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Directivos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {directivosCountArgs} args - Arguments to filter Directivos to count.
   * @example
   * // Count the number of Directivos
   * const count = await prisma.directivos.count({
   *   where: {
   *     // ... the filter for the Directivos we want to count
   *   }
   * })
  **/
  count<T extends directivosCountArgs>(
    args?: Prisma.Subset<T, directivosCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], DirectivosCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Directivos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {DirectivosAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends DirectivosAggregateArgs>(args: Prisma.Subset<T, DirectivosAggregateArgs>): Prisma.PrismaPromise<GetDirectivosAggregateType<T>>

  /**
   * Group by Directivos.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {directivosGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends directivosGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: directivosGroupByArgs['orderBy'] }
      : { orderBy?: directivosGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, directivosGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetDirectivosGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the directivos model
 */
readonly fields: directivosFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for directivos.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__directivosClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  houses<T extends Prisma.directivos$housesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.directivos$housesArgs<ExtArgs>>): Prisma.Prisma__housesClient<runtime.Types.Result.GetResult<Prisma.$housesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  members<T extends Prisma.directivos$membersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.directivos$membersArgs<ExtArgs>>): Prisma.Prisma__membersClient<runtime.Types.Result.GetResult<Prisma.$membersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the directivos model
 */
export interface directivosFieldRefs {
  readonly id: Prisma.FieldRef<"directivos", 'Int'>
  readonly house_id: Prisma.FieldRef<"directivos", 'Int'>
  readonly member_id: Prisma.FieldRef<"directivos", 'Int'>
  readonly role: Prisma.FieldRef<"directivos", 'String'>
  readonly start_date: Prisma.FieldRef<"directivos", 'DateTime'>
  readonly end_date: Prisma.FieldRef<"directivos", 'DateTime'>
}
    

// Custom InputTypes
/**
 * directivos findUnique
 */
export type directivosFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the directivos
   */
  select?: Prisma.directivosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the directivos
   */
  omit?: Prisma.directivosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.directivosInclude<ExtArgs> | null
  /**
   * Filter, which directivos to fetch.
   */
  where: Prisma.directivosWhereUniqueInput
}

/**
 * directivos findUniqueOrThrow
 */
export type directivosFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the directivos
   */
  select?: Prisma.directivosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the directivos
   */
  omit?: Prisma.directivosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.directivosInclude<ExtArgs> | null
  /**
   * Filter, which directivos to fetch.
   */
  where: Prisma.directivosWhereUniqueInput
}

/**
 * directivos findFirst
 */
export type directivosFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the directivos
   */
  select?: Prisma.directivosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the directivos
   */
  omit?: Prisma.directivosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.directivosInclude<ExtArgs> | null
  /**
   * Filter, which directivos to fetch.
   */
  where?: Prisma.directivosWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of directivos to fetch.
   */
  orderBy?: Prisma.directivosOrderByWithRelationInput | Prisma.directivosOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for directivos.
   */
  cursor?: Prisma.directivosWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` directivos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` directivos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of directivos.
   */
  distinct?: Prisma.DirectivosScalarFieldEnum | Prisma.DirectivosScalarFieldEnum[]
}

/**
 * directivos findFirstOrThrow
 */
export type directivosFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the directivos
   */
  select?: Prisma.directivosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the directivos
   */
  omit?: Prisma.directivosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.directivosInclude<ExtArgs> | null
  /**
   * Filter, which directivos to fetch.
   */
  where?: Prisma.directivosWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of directivos to fetch.
   */
  orderBy?: Prisma.directivosOrderByWithRelationInput | Prisma.directivosOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for directivos.
   */
  cursor?: Prisma.directivosWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` directivos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` directivos.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of directivos.
   */
  distinct?: Prisma.DirectivosScalarFieldEnum | Prisma.DirectivosScalarFieldEnum[]
}

/**
 * directivos findMany
 */
export type directivosFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the directivos
   */
  select?: Prisma.directivosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the directivos
   */
  omit?: Prisma.directivosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.directivosInclude<ExtArgs> | null
  /**
   * Filter, which directivos to fetch.
   */
  where?: Prisma.directivosWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of directivos to fetch.
   */
  orderBy?: Prisma.directivosOrderByWithRelationInput | Prisma.directivosOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing directivos.
   */
  cursor?: Prisma.directivosWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` directivos from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` directivos.
   */
  skip?: number
  distinct?: Prisma.DirectivosScalarFieldEnum | Prisma.DirectivosScalarFieldEnum[]
}

/**
 * directivos create
 */
export type directivosCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the directivos
   */
  select?: Prisma.directivosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the directivos
   */
  omit?: Prisma.directivosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.directivosInclude<ExtArgs> | null
  /**
   * The data needed to create a directivos.
   */
  data: Prisma.XOR<Prisma.directivosCreateInput, Prisma.directivosUncheckedCreateInput>
}

/**
 * directivos createMany
 */
export type directivosCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many directivos.
   */
  data: Prisma.directivosCreateManyInput | Prisma.directivosCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * directivos createManyAndReturn
 */
export type directivosCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the directivos
   */
  select?: Prisma.directivosSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the directivos
   */
  omit?: Prisma.directivosOmit<ExtArgs> | null
  /**
   * The data used to create many directivos.
   */
  data: Prisma.directivosCreateManyInput | Prisma.directivosCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.directivosIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * directivos update
 */
export type directivosUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the directivos
   */
  select?: Prisma.directivosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the directivos
   */
  omit?: Prisma.directivosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.directivosInclude<ExtArgs> | null
  /**
   * The data needed to update a directivos.
   */
  data: Prisma.XOR<Prisma.directivosUpdateInput, Prisma.directivosUncheckedUpdateInput>
  /**
   * Choose, which directivos to update.
   */
  where: Prisma.directivosWhereUniqueInput
}

/**
 * directivos updateMany
 */
export type directivosUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update directivos.
   */
  data: Prisma.XOR<Prisma.directivosUpdateManyMutationInput, Prisma.directivosUncheckedUpdateManyInput>
  /**
   * Filter which directivos to update
   */
  where?: Prisma.directivosWhereInput
  /**
   * Limit how many directivos to update.
   */
  limit?: number
}

/**
 * directivos updateManyAndReturn
 */
export type directivosUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the directivos
   */
  select?: Prisma.directivosSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the directivos
   */
  omit?: Prisma.directivosOmit<ExtArgs> | null
  /**
   * The data used to update directivos.
   */
  data: Prisma.XOR<Prisma.directivosUpdateManyMutationInput, Prisma.directivosUncheckedUpdateManyInput>
  /**
   * Filter which directivos to update
   */
  where?: Prisma.directivosWhereInput
  /**
   * Limit how many directivos to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.directivosIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * directivos upsert
 */
export type directivosUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the directivos
   */
  select?: Prisma.directivosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the directivos
   */
  omit?: Prisma.directivosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.directivosInclude<ExtArgs> | null
  /**
   * The filter to search for the directivos to update in case it exists.
   */
  where: Prisma.directivosWhereUniqueInput
  /**
   * In case the directivos found by the `where` argument doesn't exist, create a new directivos with this data.
   */
  create: Prisma.XOR<Prisma.directivosCreateInput, Prisma.directivosUncheckedCreateInput>
  /**
   * In case the directivos was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.directivosUpdateInput, Prisma.directivosUncheckedUpdateInput>
}

/**
 * directivos delete
 */
export type directivosDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the directivos
   */
  select?: Prisma.directivosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the directivos
   */
  omit?: Prisma.directivosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.directivosInclude<ExtArgs> | null
  /**
   * Filter which directivos to delete.
   */
  where: Prisma.directivosWhereUniqueInput
}

/**
 * directivos deleteMany
 */
export type directivosDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which directivos to delete
   */
  where?: Prisma.directivosWhereInput
  /**
   * Limit how many directivos to delete.
   */
  limit?: number
}

/**
 * directivos.houses
 */
export type directivos$housesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the houses
   */
  select?: Prisma.housesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the houses
   */
  omit?: Prisma.housesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.housesInclude<ExtArgs> | null
  where?: Prisma.housesWhereInput
}

/**
 * directivos.members
 */
export type directivos$membersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the members
   */
  select?: Prisma.membersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the members
   */
  omit?: Prisma.membersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.membersInclude<ExtArgs> | null
  where?: Prisma.membersWhereInput
}

/**
 * directivos without action
 */
export type directivosDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the directivos
   */
  select?: Prisma.directivosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the directivos
   */
  omit?: Prisma.directivosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.directivosInclude<ExtArgs> | null
}
