
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `houses` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model houses
 * This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info.
 */
export type housesModel = runtime.Types.Result.DefaultSelection<Prisma.$housesPayload>

export type AggregateHouses = {
  _count: HousesCountAggregateOutputType | null
  _avg: HousesAvgAggregateOutputType | null
  _sum: HousesSumAggregateOutputType | null
  _min: HousesMinAggregateOutputType | null
  _max: HousesMaxAggregateOutputType | null
}

export type HousesAvgAggregateOutputType = {
  id: number | null
  brand_id: number | null
}

export type HousesSumAggregateOutputType = {
  id: number | null
  brand_id: number | null
}

export type HousesMinAggregateOutputType = {
  id: number | null
  brand_id: number | null
  name: string | null
  description: string | null
  created_at: Date | null
}

export type HousesMaxAggregateOutputType = {
  id: number | null
  brand_id: number | null
  name: string | null
  description: string | null
  created_at: Date | null
}

export type HousesCountAggregateOutputType = {
  id: number
  brand_id: number
  name: number
  description: number
  created_at: number
  _all: number
}


export type HousesAvgAggregateInputType = {
  id?: true
  brand_id?: true
}

export type HousesSumAggregateInputType = {
  id?: true
  brand_id?: true
}

export type HousesMinAggregateInputType = {
  id?: true
  brand_id?: true
  name?: true
  description?: true
  created_at?: true
}

export type HousesMaxAggregateInputType = {
  id?: true
  brand_id?: true
  name?: true
  description?: true
  created_at?: true
}

export type HousesCountAggregateInputType = {
  id?: true
  brand_id?: true
  name?: true
  description?: true
  created_at?: true
  _all?: true
}

export type HousesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which houses to aggregate.
   */
  where?: Prisma.housesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of houses to fetch.
   */
  orderBy?: Prisma.housesOrderByWithRelationInput | Prisma.housesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.housesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` houses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` houses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned houses
  **/
  _count?: true | HousesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: HousesAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: HousesSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: HousesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: HousesMaxAggregateInputType
}

export type GetHousesAggregateType<T extends HousesAggregateArgs> = {
      [P in keyof T & keyof AggregateHouses]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateHouses[P]>
    : Prisma.GetScalarType<T[P], AggregateHouses[P]>
}




export type housesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.housesWhereInput
  orderBy?: Prisma.housesOrderByWithAggregationInput | Prisma.housesOrderByWithAggregationInput[]
  by: Prisma.HousesScalarFieldEnum[] | Prisma.HousesScalarFieldEnum
  having?: Prisma.housesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: HousesCountAggregateInputType | true
  _avg?: HousesAvgAggregateInputType
  _sum?: HousesSumAggregateInputType
  _min?: HousesMinAggregateInputType
  _max?: HousesMaxAggregateInputType
}

export type HousesGroupByOutputType = {
  id: number
  brand_id: number | null
  name: string
  description: string | null
  created_at: Date | null
  _count: HousesCountAggregateOutputType | null
  _avg: HousesAvgAggregateOutputType | null
  _sum: HousesSumAggregateOutputType | null
  _min: HousesMinAggregateOutputType | null
  _max: HousesMaxAggregateOutputType | null
}

type GetHousesGroupByPayload<T extends housesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<HousesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof HousesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], HousesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], HousesGroupByOutputType[P]>
      }
    >
  >



export type housesWhereInput = {
  AND?: Prisma.housesWhereInput | Prisma.housesWhereInput[]
  OR?: Prisma.housesWhereInput[]
  NOT?: Prisma.housesWhereInput | Prisma.housesWhereInput[]
  id?: Prisma.IntFilter<"houses"> | number
  brand_id?: Prisma.IntNullableFilter<"houses"> | number | null
  name?: Prisma.StringFilter<"houses"> | string
  description?: Prisma.StringNullableFilter<"houses"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"houses"> | Date | string | null
  directivos?: Prisma.DirectivosListRelationFilter
  brands?: Prisma.XOR<Prisma.BrandsNullableScalarRelationFilter, Prisma.brandsWhereInput> | null
  members?: Prisma.MembersListRelationFilter
}

export type housesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  brand_id?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  directivos?: Prisma.directivosOrderByRelationAggregateInput
  brands?: Prisma.brandsOrderByWithRelationInput
  members?: Prisma.membersOrderByRelationAggregateInput
}

export type housesWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.housesWhereInput | Prisma.housesWhereInput[]
  OR?: Prisma.housesWhereInput[]
  NOT?: Prisma.housesWhereInput | Prisma.housesWhereInput[]
  brand_id?: Prisma.IntNullableFilter<"houses"> | number | null
  name?: Prisma.StringFilter<"houses"> | string
  description?: Prisma.StringNullableFilter<"houses"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"houses"> | Date | string | null
  directivos?: Prisma.DirectivosListRelationFilter
  brands?: Prisma.XOR<Prisma.BrandsNullableScalarRelationFilter, Prisma.brandsWhereInput> | null
  members?: Prisma.MembersListRelationFilter
}, "id">

export type housesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  brand_id?: Prisma.SortOrderInput | Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.housesCountOrderByAggregateInput
  _avg?: Prisma.housesAvgOrderByAggregateInput
  _max?: Prisma.housesMaxOrderByAggregateInput
  _min?: Prisma.housesMinOrderByAggregateInput
  _sum?: Prisma.housesSumOrderByAggregateInput
}

export type housesScalarWhereWithAggregatesInput = {
  AND?: Prisma.housesScalarWhereWithAggregatesInput | Prisma.housesScalarWhereWithAggregatesInput[]
  OR?: Prisma.housesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.housesScalarWhereWithAggregatesInput | Prisma.housesScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"houses"> | number
  brand_id?: Prisma.IntNullableWithAggregatesFilter<"houses"> | number | null
  name?: Prisma.StringWithAggregatesFilter<"houses"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"houses"> | string | null
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"houses"> | Date | string | null
}

export type housesCreateInput = {
  name: string
  description?: string | null
  created_at?: Date | string | null
  directivos?: Prisma.directivosCreateNestedManyWithoutHousesInput
  brands?: Prisma.brandsCreateNestedOneWithoutHousesInput
  members?: Prisma.membersCreateNestedManyWithoutHousesInput
}

export type housesUncheckedCreateInput = {
  id?: number
  brand_id?: number | null
  name: string
  description?: string | null
  created_at?: Date | string | null
  directivos?: Prisma.directivosUncheckedCreateNestedManyWithoutHousesInput
  members?: Prisma.membersUncheckedCreateNestedManyWithoutHousesInput
}

export type housesUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  directivos?: Prisma.directivosUpdateManyWithoutHousesNestedInput
  brands?: Prisma.brandsUpdateOneWithoutHousesNestedInput
  members?: Prisma.membersUpdateManyWithoutHousesNestedInput
}

export type housesUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  brand_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  directivos?: Prisma.directivosUncheckedUpdateManyWithoutHousesNestedInput
  members?: Prisma.membersUncheckedUpdateManyWithoutHousesNestedInput
}

export type housesCreateManyInput = {
  id?: number
  brand_id?: number | null
  name: string
  description?: string | null
  created_at?: Date | string | null
}

export type housesUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type housesUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  brand_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type HousesListRelationFilter = {
  every?: Prisma.housesWhereInput
  some?: Prisma.housesWhereInput
  none?: Prisma.housesWhereInput
}

export type housesOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type HousesNullableScalarRelationFilter = {
  is?: Prisma.housesWhereInput | null
  isNot?: Prisma.housesWhereInput | null
}

export type housesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  brand_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type housesAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  brand_id?: Prisma.SortOrder
}

export type housesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  brand_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type housesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  brand_id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  description?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type housesSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  brand_id?: Prisma.SortOrder
}

export type housesCreateNestedManyWithoutBrandsInput = {
  create?: Prisma.XOR<Prisma.housesCreateWithoutBrandsInput, Prisma.housesUncheckedCreateWithoutBrandsInput> | Prisma.housesCreateWithoutBrandsInput[] | Prisma.housesUncheckedCreateWithoutBrandsInput[]
  connectOrCreate?: Prisma.housesCreateOrConnectWithoutBrandsInput | Prisma.housesCreateOrConnectWithoutBrandsInput[]
  createMany?: Prisma.housesCreateManyBrandsInputEnvelope
  connect?: Prisma.housesWhereUniqueInput | Prisma.housesWhereUniqueInput[]
}

export type housesUncheckedCreateNestedManyWithoutBrandsInput = {
  create?: Prisma.XOR<Prisma.housesCreateWithoutBrandsInput, Prisma.housesUncheckedCreateWithoutBrandsInput> | Prisma.housesCreateWithoutBrandsInput[] | Prisma.housesUncheckedCreateWithoutBrandsInput[]
  connectOrCreate?: Prisma.housesCreateOrConnectWithoutBrandsInput | Prisma.housesCreateOrConnectWithoutBrandsInput[]
  createMany?: Prisma.housesCreateManyBrandsInputEnvelope
  connect?: Prisma.housesWhereUniqueInput | Prisma.housesWhereUniqueInput[]
}

export type housesUpdateManyWithoutBrandsNestedInput = {
  create?: Prisma.XOR<Prisma.housesCreateWithoutBrandsInput, Prisma.housesUncheckedCreateWithoutBrandsInput> | Prisma.housesCreateWithoutBrandsInput[] | Prisma.housesUncheckedCreateWithoutBrandsInput[]
  connectOrCreate?: Prisma.housesCreateOrConnectWithoutBrandsInput | Prisma.housesCreateOrConnectWithoutBrandsInput[]
  upsert?: Prisma.housesUpsertWithWhereUniqueWithoutBrandsInput | Prisma.housesUpsertWithWhereUniqueWithoutBrandsInput[]
  createMany?: Prisma.housesCreateManyBrandsInputEnvelope
  set?: Prisma.housesWhereUniqueInput | Prisma.housesWhereUniqueInput[]
  disconnect?: Prisma.housesWhereUniqueInput | Prisma.housesWhereUniqueInput[]
  delete?: Prisma.housesWhereUniqueInput | Prisma.housesWhereUniqueInput[]
  connect?: Prisma.housesWhereUniqueInput | Prisma.housesWhereUniqueInput[]
  update?: Prisma.housesUpdateWithWhereUniqueWithoutBrandsInput | Prisma.housesUpdateWithWhereUniqueWithoutBrandsInput[]
  updateMany?: Prisma.housesUpdateManyWithWhereWithoutBrandsInput | Prisma.housesUpdateManyWithWhereWithoutBrandsInput[]
  deleteMany?: Prisma.housesScalarWhereInput | Prisma.housesScalarWhereInput[]
}

export type housesUncheckedUpdateManyWithoutBrandsNestedInput = {
  create?: Prisma.XOR<Prisma.housesCreateWithoutBrandsInput, Prisma.housesUncheckedCreateWithoutBrandsInput> | Prisma.housesCreateWithoutBrandsInput[] | Prisma.housesUncheckedCreateWithoutBrandsInput[]
  connectOrCreate?: Prisma.housesCreateOrConnectWithoutBrandsInput | Prisma.housesCreateOrConnectWithoutBrandsInput[]
  upsert?: Prisma.housesUpsertWithWhereUniqueWithoutBrandsInput | Prisma.housesUpsertWithWhereUniqueWithoutBrandsInput[]
  createMany?: Prisma.housesCreateManyBrandsInputEnvelope
  set?: Prisma.housesWhereUniqueInput | Prisma.housesWhereUniqueInput[]
  disconnect?: Prisma.housesWhereUniqueInput | Prisma.housesWhereUniqueInput[]
  delete?: Prisma.housesWhereUniqueInput | Prisma.housesWhereUniqueInput[]
  connect?: Prisma.housesWhereUniqueInput | Prisma.housesWhereUniqueInput[]
  update?: Prisma.housesUpdateWithWhereUniqueWithoutBrandsInput | Prisma.housesUpdateWithWhereUniqueWithoutBrandsInput[]
  updateMany?: Prisma.housesUpdateManyWithWhereWithoutBrandsInput | Prisma.housesUpdateManyWithWhereWithoutBrandsInput[]
  deleteMany?: Prisma.housesScalarWhereInput | Prisma.housesScalarWhereInput[]
}

export type housesCreateNestedOneWithoutDirectivosInput = {
  create?: Prisma.XOR<Prisma.housesCreateWithoutDirectivosInput, Prisma.housesUncheckedCreateWithoutDirectivosInput>
  connectOrCreate?: Prisma.housesCreateOrConnectWithoutDirectivosInput
  connect?: Prisma.housesWhereUniqueInput
}

export type housesUpdateOneWithoutDirectivosNestedInput = {
  create?: Prisma.XOR<Prisma.housesCreateWithoutDirectivosInput, Prisma.housesUncheckedCreateWithoutDirectivosInput>
  connectOrCreate?: Prisma.housesCreateOrConnectWithoutDirectivosInput
  upsert?: Prisma.housesUpsertWithoutDirectivosInput
  disconnect?: Prisma.housesWhereInput | boolean
  delete?: Prisma.housesWhereInput | boolean
  connect?: Prisma.housesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.housesUpdateToOneWithWhereWithoutDirectivosInput, Prisma.housesUpdateWithoutDirectivosInput>, Prisma.housesUncheckedUpdateWithoutDirectivosInput>
}

export type housesCreateNestedOneWithoutMembersInput = {
  create?: Prisma.XOR<Prisma.housesCreateWithoutMembersInput, Prisma.housesUncheckedCreateWithoutMembersInput>
  connectOrCreate?: Prisma.housesCreateOrConnectWithoutMembersInput
  connect?: Prisma.housesWhereUniqueInput
}

export type housesUpdateOneWithoutMembersNestedInput = {
  create?: Prisma.XOR<Prisma.housesCreateWithoutMembersInput, Prisma.housesUncheckedCreateWithoutMembersInput>
  connectOrCreate?: Prisma.housesCreateOrConnectWithoutMembersInput
  upsert?: Prisma.housesUpsertWithoutMembersInput
  disconnect?: Prisma.housesWhereInput | boolean
  delete?: Prisma.housesWhereInput | boolean
  connect?: Prisma.housesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.housesUpdateToOneWithWhereWithoutMembersInput, Prisma.housesUpdateWithoutMembersInput>, Prisma.housesUncheckedUpdateWithoutMembersInput>
}

export type housesCreateWithoutBrandsInput = {
  name: string
  description?: string | null
  created_at?: Date | string | null
  directivos?: Prisma.directivosCreateNestedManyWithoutHousesInput
  members?: Prisma.membersCreateNestedManyWithoutHousesInput
}

export type housesUncheckedCreateWithoutBrandsInput = {
  id?: number
  name: string
  description?: string | null
  created_at?: Date | string | null
  directivos?: Prisma.directivosUncheckedCreateNestedManyWithoutHousesInput
  members?: Prisma.membersUncheckedCreateNestedManyWithoutHousesInput
}

export type housesCreateOrConnectWithoutBrandsInput = {
  where: Prisma.housesWhereUniqueInput
  create: Prisma.XOR<Prisma.housesCreateWithoutBrandsInput, Prisma.housesUncheckedCreateWithoutBrandsInput>
}

export type housesCreateManyBrandsInputEnvelope = {
  data: Prisma.housesCreateManyBrandsInput | Prisma.housesCreateManyBrandsInput[]
  skipDuplicates?: boolean
}

export type housesUpsertWithWhereUniqueWithoutBrandsInput = {
  where: Prisma.housesWhereUniqueInput
  update: Prisma.XOR<Prisma.housesUpdateWithoutBrandsInput, Prisma.housesUncheckedUpdateWithoutBrandsInput>
  create: Prisma.XOR<Prisma.housesCreateWithoutBrandsInput, Prisma.housesUncheckedCreateWithoutBrandsInput>
}

export type housesUpdateWithWhereUniqueWithoutBrandsInput = {
  where: Prisma.housesWhereUniqueInput
  data: Prisma.XOR<Prisma.housesUpdateWithoutBrandsInput, Prisma.housesUncheckedUpdateWithoutBrandsInput>
}

export type housesUpdateManyWithWhereWithoutBrandsInput = {
  where: Prisma.housesScalarWhereInput
  data: Prisma.XOR<Prisma.housesUpdateManyMutationInput, Prisma.housesUncheckedUpdateManyWithoutBrandsInput>
}

export type housesScalarWhereInput = {
  AND?: Prisma.housesScalarWhereInput | Prisma.housesScalarWhereInput[]
  OR?: Prisma.housesScalarWhereInput[]
  NOT?: Prisma.housesScalarWhereInput | Prisma.housesScalarWhereInput[]
  id?: Prisma.IntFilter<"houses"> | number
  brand_id?: Prisma.IntNullableFilter<"houses"> | number | null
  name?: Prisma.StringFilter<"houses"> | string
  description?: Prisma.StringNullableFilter<"houses"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"houses"> | Date | string | null
}

export type housesCreateWithoutDirectivosInput = {
  name: string
  description?: string | null
  created_at?: Date | string | null
  brands?: Prisma.brandsCreateNestedOneWithoutHousesInput
  members?: Prisma.membersCreateNestedManyWithoutHousesInput
}

export type housesUncheckedCreateWithoutDirectivosInput = {
  id?: number
  brand_id?: number | null
  name: string
  description?: string | null
  created_at?: Date | string | null
  members?: Prisma.membersUncheckedCreateNestedManyWithoutHousesInput
}

export type housesCreateOrConnectWithoutDirectivosInput = {
  where: Prisma.housesWhereUniqueInput
  create: Prisma.XOR<Prisma.housesCreateWithoutDirectivosInput, Prisma.housesUncheckedCreateWithoutDirectivosInput>
}

export type housesUpsertWithoutDirectivosInput = {
  update: Prisma.XOR<Prisma.housesUpdateWithoutDirectivosInput, Prisma.housesUncheckedUpdateWithoutDirectivosInput>
  create: Prisma.XOR<Prisma.housesCreateWithoutDirectivosInput, Prisma.housesUncheckedCreateWithoutDirectivosInput>
  where?: Prisma.housesWhereInput
}

export type housesUpdateToOneWithWhereWithoutDirectivosInput = {
  where?: Prisma.housesWhereInput
  data: Prisma.XOR<Prisma.housesUpdateWithoutDirectivosInput, Prisma.housesUncheckedUpdateWithoutDirectivosInput>
}

export type housesUpdateWithoutDirectivosInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  brands?: Prisma.brandsUpdateOneWithoutHousesNestedInput
  members?: Prisma.membersUpdateManyWithoutHousesNestedInput
}

export type housesUncheckedUpdateWithoutDirectivosInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  brand_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  members?: Prisma.membersUncheckedUpdateManyWithoutHousesNestedInput
}

export type housesCreateWithoutMembersInput = {
  name: string
  description?: string | null
  created_at?: Date | string | null
  directivos?: Prisma.directivosCreateNestedManyWithoutHousesInput
  brands?: Prisma.brandsCreateNestedOneWithoutHousesInput
}

export type housesUncheckedCreateWithoutMembersInput = {
  id?: number
  brand_id?: number | null
  name: string
  description?: string | null
  created_at?: Date | string | null
  directivos?: Prisma.directivosUncheckedCreateNestedManyWithoutHousesInput
}

export type housesCreateOrConnectWithoutMembersInput = {
  where: Prisma.housesWhereUniqueInput
  create: Prisma.XOR<Prisma.housesCreateWithoutMembersInput, Prisma.housesUncheckedCreateWithoutMembersInput>
}

export type housesUpsertWithoutMembersInput = {
  update: Prisma.XOR<Prisma.housesUpdateWithoutMembersInput, Prisma.housesUncheckedUpdateWithoutMembersInput>
  create: Prisma.XOR<Prisma.housesCreateWithoutMembersInput, Prisma.housesUncheckedCreateWithoutMembersInput>
  where?: Prisma.housesWhereInput
}

export type housesUpdateToOneWithWhereWithoutMembersInput = {
  where?: Prisma.housesWhereInput
  data: Prisma.XOR<Prisma.housesUpdateWithoutMembersInput, Prisma.housesUncheckedUpdateWithoutMembersInput>
}

export type housesUpdateWithoutMembersInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  directivos?: Prisma.directivosUpdateManyWithoutHousesNestedInput
  brands?: Prisma.brandsUpdateOneWithoutHousesNestedInput
}

export type housesUncheckedUpdateWithoutMembersInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  brand_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  directivos?: Prisma.directivosUncheckedUpdateManyWithoutHousesNestedInput
}

export type housesCreateManyBrandsInput = {
  id?: number
  name: string
  description?: string | null
  created_at?: Date | string | null
}

export type housesUpdateWithoutBrandsInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  directivos?: Prisma.directivosUpdateManyWithoutHousesNestedInput
  members?: Prisma.membersUpdateManyWithoutHousesNestedInput
}

export type housesUncheckedUpdateWithoutBrandsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  directivos?: Prisma.directivosUncheckedUpdateManyWithoutHousesNestedInput
  members?: Prisma.membersUncheckedUpdateManyWithoutHousesNestedInput
}

export type housesUncheckedUpdateManyWithoutBrandsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type HousesCountOutputType
 */

export type HousesCountOutputType = {
  directivos: number
  members: number
}

export type HousesCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  directivos?: boolean | HousesCountOutputTypeCountDirectivosArgs
  members?: boolean | HousesCountOutputTypeCountMembersArgs
}

/**
 * HousesCountOutputType without action
 */
export type HousesCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HousesCountOutputType
   */
  select?: Prisma.HousesCountOutputTypeSelect<ExtArgs> | null
}

/**
 * HousesCountOutputType without action
 */
export type HousesCountOutputTypeCountDirectivosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.directivosWhereInput
}

/**
 * HousesCountOutputType without action
 */
export type HousesCountOutputTypeCountMembersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.membersWhereInput
}


export type housesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  brand_id?: boolean
  name?: boolean
  description?: boolean
  created_at?: boolean
  directivos?: boolean | Prisma.houses$directivosArgs<ExtArgs>
  brands?: boolean | Prisma.houses$brandsArgs<ExtArgs>
  members?: boolean | Prisma.houses$membersArgs<ExtArgs>
  _count?: boolean | Prisma.HousesCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["houses"]>

export type housesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  brand_id?: boolean
  name?: boolean
  description?: boolean
  created_at?: boolean
  brands?: boolean | Prisma.houses$brandsArgs<ExtArgs>
}, ExtArgs["result"]["houses"]>

export type housesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  brand_id?: boolean
  name?: boolean
  description?: boolean
  created_at?: boolean
  brands?: boolean | Prisma.houses$brandsArgs<ExtArgs>
}, ExtArgs["result"]["houses"]>

export type housesSelectScalar = {
  id?: boolean
  brand_id?: boolean
  name?: boolean
  description?: boolean
  created_at?: boolean
}

export type housesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "brand_id" | "name" | "description" | "created_at", ExtArgs["result"]["houses"]>
export type housesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  directivos?: boolean | Prisma.houses$directivosArgs<ExtArgs>
  brands?: boolean | Prisma.houses$brandsArgs<ExtArgs>
  members?: boolean | Prisma.houses$membersArgs<ExtArgs>
  _count?: boolean | Prisma.HousesCountOutputTypeDefaultArgs<ExtArgs>
}
export type housesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  brands?: boolean | Prisma.houses$brandsArgs<ExtArgs>
}
export type housesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  brands?: boolean | Prisma.houses$brandsArgs<ExtArgs>
}

export type $housesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "houses"
  objects: {
    directivos: Prisma.$directivosPayload<ExtArgs>[]
    brands: Prisma.$brandsPayload<ExtArgs> | null
    members: Prisma.$membersPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    brand_id: number | null
    name: string
    description: string | null
    created_at: Date | null
  }, ExtArgs["result"]["houses"]>
  composites: {}
}

export type housesGetPayload<S extends boolean | null | undefined | housesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$housesPayload, S>

export type housesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<housesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: HousesCountAggregateInputType | true
  }

export interface housesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['houses'], meta: { name: 'houses' } }
  /**
   * Find zero or one Houses that matches the filter.
   * @param {housesFindUniqueArgs} args - Arguments to find a Houses
   * @example
   * // Get one Houses
   * const houses = await prisma.houses.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends housesFindUniqueArgs>(args: Prisma.SelectSubset<T, housesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__housesClient<runtime.Types.Result.GetResult<Prisma.$housesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Houses that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {housesFindUniqueOrThrowArgs} args - Arguments to find a Houses
   * @example
   * // Get one Houses
   * const houses = await prisma.houses.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends housesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, housesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__housesClient<runtime.Types.Result.GetResult<Prisma.$housesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Houses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {housesFindFirstArgs} args - Arguments to find a Houses
   * @example
   * // Get one Houses
   * const houses = await prisma.houses.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends housesFindFirstArgs>(args?: Prisma.SelectSubset<T, housesFindFirstArgs<ExtArgs>>): Prisma.Prisma__housesClient<runtime.Types.Result.GetResult<Prisma.$housesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Houses that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {housesFindFirstOrThrowArgs} args - Arguments to find a Houses
   * @example
   * // Get one Houses
   * const houses = await prisma.houses.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends housesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, housesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__housesClient<runtime.Types.Result.GetResult<Prisma.$housesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Houses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {housesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Houses
   * const houses = await prisma.houses.findMany()
   * 
   * // Get first 10 Houses
   * const houses = await prisma.houses.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const housesWithIdOnly = await prisma.houses.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends housesFindManyArgs>(args?: Prisma.SelectSubset<T, housesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$housesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Houses.
   * @param {housesCreateArgs} args - Arguments to create a Houses.
   * @example
   * // Create one Houses
   * const Houses = await prisma.houses.create({
   *   data: {
   *     // ... data to create a Houses
   *   }
   * })
   * 
   */
  create<T extends housesCreateArgs>(args: Prisma.SelectSubset<T, housesCreateArgs<ExtArgs>>): Prisma.Prisma__housesClient<runtime.Types.Result.GetResult<Prisma.$housesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Houses.
   * @param {housesCreateManyArgs} args - Arguments to create many Houses.
   * @example
   * // Create many Houses
   * const houses = await prisma.houses.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends housesCreateManyArgs>(args?: Prisma.SelectSubset<T, housesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Houses and returns the data saved in the database.
   * @param {housesCreateManyAndReturnArgs} args - Arguments to create many Houses.
   * @example
   * // Create many Houses
   * const houses = await prisma.houses.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Houses and only return the `id`
   * const housesWithIdOnly = await prisma.houses.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends housesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, housesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$housesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Houses.
   * @param {housesDeleteArgs} args - Arguments to delete one Houses.
   * @example
   * // Delete one Houses
   * const Houses = await prisma.houses.delete({
   *   where: {
   *     // ... filter to delete one Houses
   *   }
   * })
   * 
   */
  delete<T extends housesDeleteArgs>(args: Prisma.SelectSubset<T, housesDeleteArgs<ExtArgs>>): Prisma.Prisma__housesClient<runtime.Types.Result.GetResult<Prisma.$housesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Houses.
   * @param {housesUpdateArgs} args - Arguments to update one Houses.
   * @example
   * // Update one Houses
   * const houses = await prisma.houses.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends housesUpdateArgs>(args: Prisma.SelectSubset<T, housesUpdateArgs<ExtArgs>>): Prisma.Prisma__housesClient<runtime.Types.Result.GetResult<Prisma.$housesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Houses.
   * @param {housesDeleteManyArgs} args - Arguments to filter Houses to delete.
   * @example
   * // Delete a few Houses
   * const { count } = await prisma.houses.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends housesDeleteManyArgs>(args?: Prisma.SelectSubset<T, housesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Houses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {housesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Houses
   * const houses = await prisma.houses.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends housesUpdateManyArgs>(args: Prisma.SelectSubset<T, housesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Houses and returns the data updated in the database.
   * @param {housesUpdateManyAndReturnArgs} args - Arguments to update many Houses.
   * @example
   * // Update many Houses
   * const houses = await prisma.houses.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Houses and only return the `id`
   * const housesWithIdOnly = await prisma.houses.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends housesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, housesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$housesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Houses.
   * @param {housesUpsertArgs} args - Arguments to update or create a Houses.
   * @example
   * // Update or create a Houses
   * const houses = await prisma.houses.upsert({
   *   create: {
   *     // ... data to create a Houses
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Houses we want to update
   *   }
   * })
   */
  upsert<T extends housesUpsertArgs>(args: Prisma.SelectSubset<T, housesUpsertArgs<ExtArgs>>): Prisma.Prisma__housesClient<runtime.Types.Result.GetResult<Prisma.$housesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Houses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {housesCountArgs} args - Arguments to filter Houses to count.
   * @example
   * // Count the number of Houses
   * const count = await prisma.houses.count({
   *   where: {
   *     // ... the filter for the Houses we want to count
   *   }
   * })
  **/
  count<T extends housesCountArgs>(
    args?: Prisma.Subset<T, housesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], HousesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Houses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HousesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends HousesAggregateArgs>(args: Prisma.Subset<T, HousesAggregateArgs>): Prisma.PrismaPromise<GetHousesAggregateType<T>>

  /**
   * Group by Houses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {housesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends housesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: housesGroupByArgs['orderBy'] }
      : { orderBy?: housesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, housesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetHousesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the houses model
 */
readonly fields: housesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for houses.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__housesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  directivos<T extends Prisma.houses$directivosArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.houses$directivosArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$directivosPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  brands<T extends Prisma.houses$brandsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.houses$brandsArgs<ExtArgs>>): Prisma.Prisma__brandsClient<runtime.Types.Result.GetResult<Prisma.$brandsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  members<T extends Prisma.houses$membersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.houses$membersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$membersPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the houses model
 */
export interface housesFieldRefs {
  readonly id: Prisma.FieldRef<"houses", 'Int'>
  readonly brand_id: Prisma.FieldRef<"houses", 'Int'>
  readonly name: Prisma.FieldRef<"houses", 'String'>
  readonly description: Prisma.FieldRef<"houses", 'String'>
  readonly created_at: Prisma.FieldRef<"houses", 'DateTime'>
}
    

// Custom InputTypes
/**
 * houses findUnique
 */
export type housesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the houses
   */
  select?: Prisma.housesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the houses
   */
  omit?: Prisma.housesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.housesInclude<ExtArgs> | null
  /**
   * Filter, which houses to fetch.
   */
  where: Prisma.housesWhereUniqueInput
}

/**
 * houses findUniqueOrThrow
 */
export type housesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the houses
   */
  select?: Prisma.housesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the houses
   */
  omit?: Prisma.housesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.housesInclude<ExtArgs> | null
  /**
   * Filter, which houses to fetch.
   */
  where: Prisma.housesWhereUniqueInput
}

/**
 * houses findFirst
 */
export type housesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the houses
   */
  select?: Prisma.housesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the houses
   */
  omit?: Prisma.housesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.housesInclude<ExtArgs> | null
  /**
   * Filter, which houses to fetch.
   */
  where?: Prisma.housesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of houses to fetch.
   */
  orderBy?: Prisma.housesOrderByWithRelationInput | Prisma.housesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for houses.
   */
  cursor?: Prisma.housesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` houses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` houses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of houses.
   */
  distinct?: Prisma.HousesScalarFieldEnum | Prisma.HousesScalarFieldEnum[]
}

/**
 * houses findFirstOrThrow
 */
export type housesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the houses
   */
  select?: Prisma.housesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the houses
   */
  omit?: Prisma.housesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.housesInclude<ExtArgs> | null
  /**
   * Filter, which houses to fetch.
   */
  where?: Prisma.housesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of houses to fetch.
   */
  orderBy?: Prisma.housesOrderByWithRelationInput | Prisma.housesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for houses.
   */
  cursor?: Prisma.housesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` houses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` houses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of houses.
   */
  distinct?: Prisma.HousesScalarFieldEnum | Prisma.HousesScalarFieldEnum[]
}

/**
 * houses findMany
 */
export type housesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the houses
   */
  select?: Prisma.housesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the houses
   */
  omit?: Prisma.housesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.housesInclude<ExtArgs> | null
  /**
   * Filter, which houses to fetch.
   */
  where?: Prisma.housesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of houses to fetch.
   */
  orderBy?: Prisma.housesOrderByWithRelationInput | Prisma.housesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing houses.
   */
  cursor?: Prisma.housesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` houses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` houses.
   */
  skip?: number
  distinct?: Prisma.HousesScalarFieldEnum | Prisma.HousesScalarFieldEnum[]
}

/**
 * houses create
 */
export type housesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the houses
   */
  select?: Prisma.housesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the houses
   */
  omit?: Prisma.housesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.housesInclude<ExtArgs> | null
  /**
   * The data needed to create a houses.
   */
  data: Prisma.XOR<Prisma.housesCreateInput, Prisma.housesUncheckedCreateInput>
}

/**
 * houses createMany
 */
export type housesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many houses.
   */
  data: Prisma.housesCreateManyInput | Prisma.housesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * houses createManyAndReturn
 */
export type housesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the houses
   */
  select?: Prisma.housesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the houses
   */
  omit?: Prisma.housesOmit<ExtArgs> | null
  /**
   * The data used to create many houses.
   */
  data: Prisma.housesCreateManyInput | Prisma.housesCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.housesIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * houses update
 */
export type housesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the houses
   */
  select?: Prisma.housesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the houses
   */
  omit?: Prisma.housesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.housesInclude<ExtArgs> | null
  /**
   * The data needed to update a houses.
   */
  data: Prisma.XOR<Prisma.housesUpdateInput, Prisma.housesUncheckedUpdateInput>
  /**
   * Choose, which houses to update.
   */
  where: Prisma.housesWhereUniqueInput
}

/**
 * houses updateMany
 */
export type housesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update houses.
   */
  data: Prisma.XOR<Prisma.housesUpdateManyMutationInput, Prisma.housesUncheckedUpdateManyInput>
  /**
   * Filter which houses to update
   */
  where?: Prisma.housesWhereInput
  /**
   * Limit how many houses to update.
   */
  limit?: number
}

/**
 * houses updateManyAndReturn
 */
export type housesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the houses
   */
  select?: Prisma.housesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the houses
   */
  omit?: Prisma.housesOmit<ExtArgs> | null
  /**
   * The data used to update houses.
   */
  data: Prisma.XOR<Prisma.housesUpdateManyMutationInput, Prisma.housesUncheckedUpdateManyInput>
  /**
   * Filter which houses to update
   */
  where?: Prisma.housesWhereInput
  /**
   * Limit how many houses to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.housesIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * houses upsert
 */
export type housesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the houses
   */
  select?: Prisma.housesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the houses
   */
  omit?: Prisma.housesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.housesInclude<ExtArgs> | null
  /**
   * The filter to search for the houses to update in case it exists.
   */
  where: Prisma.housesWhereUniqueInput
  /**
   * In case the houses found by the `where` argument doesn't exist, create a new houses with this data.
   */
  create: Prisma.XOR<Prisma.housesCreateInput, Prisma.housesUncheckedCreateInput>
  /**
   * In case the houses was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.housesUpdateInput, Prisma.housesUncheckedUpdateInput>
}

/**
 * houses delete
 */
export type housesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the houses
   */
  select?: Prisma.housesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the houses
   */
  omit?: Prisma.housesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.housesInclude<ExtArgs> | null
  /**
   * Filter which houses to delete.
   */
  where: Prisma.housesWhereUniqueInput
}

/**
 * houses deleteMany
 */
export type housesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which houses to delete
   */
  where?: Prisma.housesWhereInput
  /**
   * Limit how many houses to delete.
   */
  limit?: number
}

/**
 * houses.directivos
 */
export type houses$directivosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the directivos
   */
  select?: Prisma.directivosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the directivos
   */
  omit?: Prisma.directivosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.directivosInclude<ExtArgs> | null
  where?: Prisma.directivosWhereInput
  orderBy?: Prisma.directivosOrderByWithRelationInput | Prisma.directivosOrderByWithRelationInput[]
  cursor?: Prisma.directivosWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.DirectivosScalarFieldEnum | Prisma.DirectivosScalarFieldEnum[]
}

/**
 * houses.brands
 */
export type houses$brandsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the brands
   */
  select?: Prisma.brandsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the brands
   */
  omit?: Prisma.brandsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.brandsInclude<ExtArgs> | null
  where?: Prisma.brandsWhereInput
}

/**
 * houses.members
 */
export type houses$membersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the members
   */
  select?: Prisma.membersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the members
   */
  omit?: Prisma.membersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.membersInclude<ExtArgs> | null
  where?: Prisma.membersWhereInput
  orderBy?: Prisma.membersOrderByWithRelationInput | Prisma.membersOrderByWithRelationInput[]
  cursor?: Prisma.membersWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MembersScalarFieldEnum | Prisma.MembersScalarFieldEnum[]
}

/**
 * houses without action
 */
export type housesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the houses
   */
  select?: Prisma.housesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the houses
   */
  omit?: Prisma.housesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.housesInclude<ExtArgs> | null
}
