
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `members` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model members
 * This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info.
 */
export type membersModel = runtime.Types.Result.DefaultSelection<Prisma.$membersPayload>

export type AggregateMembers = {
  _count: MembersCountAggregateOutputType | null
  _avg: MembersAvgAggregateOutputType | null
  _sum: MembersSumAggregateOutputType | null
  _min: MembersMinAggregateOutputType | null
  _max: MembersMaxAggregateOutputType | null
}

export type MembersAvgAggregateOutputType = {
  id: number | null
  house_id: number | null
}

export type MembersSumAggregateOutputType = {
  id: number | null
  house_id: number | null
}

export type MembersMinAggregateOutputType = {
  id: number | null
  house_id: number | null
  cuenta: string | null
  nombre: string | null
  activo: boolean | null
  fecha_ingreso: Date | null
  fecha_salida: Date | null
  created_at: Date | null
  user_id: string | null
}

export type MembersMaxAggregateOutputType = {
  id: number | null
  house_id: number | null
  cuenta: string | null
  nombre: string | null
  activo: boolean | null
  fecha_ingreso: Date | null
  fecha_salida: Date | null
  created_at: Date | null
  user_id: string | null
}

export type MembersCountAggregateOutputType = {
  id: number
  house_id: number
  cuenta: number
  nombre: number
  activo: number
  fecha_ingreso: number
  fecha_salida: number
  created_at: number
  user_id: number
  _all: number
}


export type MembersAvgAggregateInputType = {
  id?: true
  house_id?: true
}

export type MembersSumAggregateInputType = {
  id?: true
  house_id?: true
}

export type MembersMinAggregateInputType = {
  id?: true
  house_id?: true
  cuenta?: true
  nombre?: true
  activo?: true
  fecha_ingreso?: true
  fecha_salida?: true
  created_at?: true
  user_id?: true
}

export type MembersMaxAggregateInputType = {
  id?: true
  house_id?: true
  cuenta?: true
  nombre?: true
  activo?: true
  fecha_ingreso?: true
  fecha_salida?: true
  created_at?: true
  user_id?: true
}

export type MembersCountAggregateInputType = {
  id?: true
  house_id?: true
  cuenta?: true
  nombre?: true
  activo?: true
  fecha_ingreso?: true
  fecha_salida?: true
  created_at?: true
  user_id?: true
  _all?: true
}

export type MembersAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which members to aggregate.
   */
  where?: Prisma.membersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of members to fetch.
   */
  orderBy?: Prisma.membersOrderByWithRelationInput | Prisma.membersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.membersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` members from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` members.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned members
  **/
  _count?: true | MembersCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MembersAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MembersSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MembersMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MembersMaxAggregateInputType
}

export type GetMembersAggregateType<T extends MembersAggregateArgs> = {
      [P in keyof T & keyof AggregateMembers]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMembers[P]>
    : Prisma.GetScalarType<T[P], AggregateMembers[P]>
}




export type membersGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.membersWhereInput
  orderBy?: Prisma.membersOrderByWithAggregationInput | Prisma.membersOrderByWithAggregationInput[]
  by: Prisma.MembersScalarFieldEnum[] | Prisma.MembersScalarFieldEnum
  having?: Prisma.membersScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MembersCountAggregateInputType | true
  _avg?: MembersAvgAggregateInputType
  _sum?: MembersSumAggregateInputType
  _min?: MembersMinAggregateInputType
  _max?: MembersMaxAggregateInputType
}

export type MembersGroupByOutputType = {
  id: number
  house_id: number | null
  cuenta: string
  nombre: string
  activo: boolean | null
  fecha_ingreso: Date
  fecha_salida: Date | null
  created_at: Date | null
  user_id: string | null
  _count: MembersCountAggregateOutputType | null
  _avg: MembersAvgAggregateOutputType | null
  _sum: MembersSumAggregateOutputType | null
  _min: MembersMinAggregateOutputType | null
  _max: MembersMaxAggregateOutputType | null
}

type GetMembersGroupByPayload<T extends membersGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MembersGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MembersGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MembersGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MembersGroupByOutputType[P]>
      }
    >
  >



export type membersWhereInput = {
  AND?: Prisma.membersWhereInput | Prisma.membersWhereInput[]
  OR?: Prisma.membersWhereInput[]
  NOT?: Prisma.membersWhereInput | Prisma.membersWhereInput[]
  id?: Prisma.IntFilter<"members"> | number
  house_id?: Prisma.IntNullableFilter<"members"> | number | null
  cuenta?: Prisma.StringFilter<"members"> | string
  nombre?: Prisma.StringFilter<"members"> | string
  activo?: Prisma.BoolNullableFilter<"members"> | boolean | null
  fecha_ingreso?: Prisma.DateTimeFilter<"members"> | Date | string
  fecha_salida?: Prisma.DateTimeNullableFilter<"members"> | Date | string | null
  created_at?: Prisma.DateTimeNullableFilter<"members"> | Date | string | null
  user_id?: Prisma.UuidNullableFilter<"members"> | string | null
  directivos?: Prisma.DirectivosListRelationFilter
  houses?: Prisma.XOR<Prisma.HousesNullableScalarRelationFilter, Prisma.housesWhereInput> | null
  participations?: Prisma.ParticipationsListRelationFilter
}

export type membersOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  house_id?: Prisma.SortOrderInput | Prisma.SortOrder
  cuenta?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  activo?: Prisma.SortOrderInput | Prisma.SortOrder
  fecha_ingreso?: Prisma.SortOrder
  fecha_salida?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  user_id?: Prisma.SortOrderInput | Prisma.SortOrder
  directivos?: Prisma.directivosOrderByRelationAggregateInput
  houses?: Prisma.housesOrderByWithRelationInput
  participations?: Prisma.participationsOrderByRelationAggregateInput
}

export type membersWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.membersWhereInput | Prisma.membersWhereInput[]
  OR?: Prisma.membersWhereInput[]
  NOT?: Prisma.membersWhereInput | Prisma.membersWhereInput[]
  house_id?: Prisma.IntNullableFilter<"members"> | number | null
  cuenta?: Prisma.StringFilter<"members"> | string
  nombre?: Prisma.StringFilter<"members"> | string
  activo?: Prisma.BoolNullableFilter<"members"> | boolean | null
  fecha_ingreso?: Prisma.DateTimeFilter<"members"> | Date | string
  fecha_salida?: Prisma.DateTimeNullableFilter<"members"> | Date | string | null
  created_at?: Prisma.DateTimeNullableFilter<"members"> | Date | string | null
  user_id?: Prisma.UuidNullableFilter<"members"> | string | null
  directivos?: Prisma.DirectivosListRelationFilter
  houses?: Prisma.XOR<Prisma.HousesNullableScalarRelationFilter, Prisma.housesWhereInput> | null
  participations?: Prisma.ParticipationsListRelationFilter
}, "id">

export type membersOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  house_id?: Prisma.SortOrderInput | Prisma.SortOrder
  cuenta?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  activo?: Prisma.SortOrderInput | Prisma.SortOrder
  fecha_ingreso?: Prisma.SortOrder
  fecha_salida?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  user_id?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.membersCountOrderByAggregateInput
  _avg?: Prisma.membersAvgOrderByAggregateInput
  _max?: Prisma.membersMaxOrderByAggregateInput
  _min?: Prisma.membersMinOrderByAggregateInput
  _sum?: Prisma.membersSumOrderByAggregateInput
}

export type membersScalarWhereWithAggregatesInput = {
  AND?: Prisma.membersScalarWhereWithAggregatesInput | Prisma.membersScalarWhereWithAggregatesInput[]
  OR?: Prisma.membersScalarWhereWithAggregatesInput[]
  NOT?: Prisma.membersScalarWhereWithAggregatesInput | Prisma.membersScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"members"> | number
  house_id?: Prisma.IntNullableWithAggregatesFilter<"members"> | number | null
  cuenta?: Prisma.StringWithAggregatesFilter<"members"> | string
  nombre?: Prisma.StringWithAggregatesFilter<"members"> | string
  activo?: Prisma.BoolNullableWithAggregatesFilter<"members"> | boolean | null
  fecha_ingreso?: Prisma.DateTimeWithAggregatesFilter<"members"> | Date | string
  fecha_salida?: Prisma.DateTimeNullableWithAggregatesFilter<"members"> | Date | string | null
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"members"> | Date | string | null
  user_id?: Prisma.UuidNullableWithAggregatesFilter<"members"> | string | null
}

export type membersCreateInput = {
  cuenta: string
  nombre: string
  activo?: boolean | null
  fecha_ingreso: Date | string
  fecha_salida?: Date | string | null
  created_at?: Date | string | null
  user_id?: string | null
  directivos?: Prisma.directivosCreateNestedManyWithoutMembersInput
  houses?: Prisma.housesCreateNestedOneWithoutMembersInput
  participations?: Prisma.participationsCreateNestedManyWithoutMembersInput
}

export type membersUncheckedCreateInput = {
  id?: number
  house_id?: number | null
  cuenta: string
  nombre: string
  activo?: boolean | null
  fecha_ingreso: Date | string
  fecha_salida?: Date | string | null
  created_at?: Date | string | null
  user_id?: string | null
  directivos?: Prisma.directivosUncheckedCreateNestedManyWithoutMembersInput
  participations?: Prisma.participationsUncheckedCreateNestedManyWithoutMembersInput
}

export type membersUpdateInput = {
  cuenta?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  activo?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  fecha_ingreso?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fecha_salida?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  directivos?: Prisma.directivosUpdateManyWithoutMembersNestedInput
  houses?: Prisma.housesUpdateOneWithoutMembersNestedInput
  participations?: Prisma.participationsUpdateManyWithoutMembersNestedInput
}

export type membersUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  house_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  cuenta?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  activo?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  fecha_ingreso?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fecha_salida?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  directivos?: Prisma.directivosUncheckedUpdateManyWithoutMembersNestedInput
  participations?: Prisma.participationsUncheckedUpdateManyWithoutMembersNestedInput
}

export type membersCreateManyInput = {
  id?: number
  house_id?: number | null
  cuenta: string
  nombre: string
  activo?: boolean | null
  fecha_ingreso: Date | string
  fecha_salida?: Date | string | null
  created_at?: Date | string | null
  user_id?: string | null
}

export type membersUpdateManyMutationInput = {
  cuenta?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  activo?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  fecha_ingreso?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fecha_salida?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type membersUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  house_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  cuenta?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  activo?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  fecha_ingreso?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fecha_salida?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type MembersNullableScalarRelationFilter = {
  is?: Prisma.membersWhereInput | null
  isNot?: Prisma.membersWhereInput | null
}

export type MembersListRelationFilter = {
  every?: Prisma.membersWhereInput
  some?: Prisma.membersWhereInput
  none?: Prisma.membersWhereInput
}

export type membersOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type membersCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  house_id?: Prisma.SortOrder
  cuenta?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  activo?: Prisma.SortOrder
  fecha_ingreso?: Prisma.SortOrder
  fecha_salida?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
}

export type membersAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  house_id?: Prisma.SortOrder
}

export type membersMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  house_id?: Prisma.SortOrder
  cuenta?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  activo?: Prisma.SortOrder
  fecha_ingreso?: Prisma.SortOrder
  fecha_salida?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
}

export type membersMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  house_id?: Prisma.SortOrder
  cuenta?: Prisma.SortOrder
  nombre?: Prisma.SortOrder
  activo?: Prisma.SortOrder
  fecha_ingreso?: Prisma.SortOrder
  fecha_salida?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
  user_id?: Prisma.SortOrder
}

export type membersSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  house_id?: Prisma.SortOrder
}

export type membersCreateNestedOneWithoutDirectivosInput = {
  create?: Prisma.XOR<Prisma.membersCreateWithoutDirectivosInput, Prisma.membersUncheckedCreateWithoutDirectivosInput>
  connectOrCreate?: Prisma.membersCreateOrConnectWithoutDirectivosInput
  connect?: Prisma.membersWhereUniqueInput
}

export type membersUpdateOneWithoutDirectivosNestedInput = {
  create?: Prisma.XOR<Prisma.membersCreateWithoutDirectivosInput, Prisma.membersUncheckedCreateWithoutDirectivosInput>
  connectOrCreate?: Prisma.membersCreateOrConnectWithoutDirectivosInput
  upsert?: Prisma.membersUpsertWithoutDirectivosInput
  disconnect?: Prisma.membersWhereInput | boolean
  delete?: Prisma.membersWhereInput | boolean
  connect?: Prisma.membersWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.membersUpdateToOneWithWhereWithoutDirectivosInput, Prisma.membersUpdateWithoutDirectivosInput>, Prisma.membersUncheckedUpdateWithoutDirectivosInput>
}

export type membersCreateNestedManyWithoutHousesInput = {
  create?: Prisma.XOR<Prisma.membersCreateWithoutHousesInput, Prisma.membersUncheckedCreateWithoutHousesInput> | Prisma.membersCreateWithoutHousesInput[] | Prisma.membersUncheckedCreateWithoutHousesInput[]
  connectOrCreate?: Prisma.membersCreateOrConnectWithoutHousesInput | Prisma.membersCreateOrConnectWithoutHousesInput[]
  createMany?: Prisma.membersCreateManyHousesInputEnvelope
  connect?: Prisma.membersWhereUniqueInput | Prisma.membersWhereUniqueInput[]
}

export type membersUncheckedCreateNestedManyWithoutHousesInput = {
  create?: Prisma.XOR<Prisma.membersCreateWithoutHousesInput, Prisma.membersUncheckedCreateWithoutHousesInput> | Prisma.membersCreateWithoutHousesInput[] | Prisma.membersUncheckedCreateWithoutHousesInput[]
  connectOrCreate?: Prisma.membersCreateOrConnectWithoutHousesInput | Prisma.membersCreateOrConnectWithoutHousesInput[]
  createMany?: Prisma.membersCreateManyHousesInputEnvelope
  connect?: Prisma.membersWhereUniqueInput | Prisma.membersWhereUniqueInput[]
}

export type membersUpdateManyWithoutHousesNestedInput = {
  create?: Prisma.XOR<Prisma.membersCreateWithoutHousesInput, Prisma.membersUncheckedCreateWithoutHousesInput> | Prisma.membersCreateWithoutHousesInput[] | Prisma.membersUncheckedCreateWithoutHousesInput[]
  connectOrCreate?: Prisma.membersCreateOrConnectWithoutHousesInput | Prisma.membersCreateOrConnectWithoutHousesInput[]
  upsert?: Prisma.membersUpsertWithWhereUniqueWithoutHousesInput | Prisma.membersUpsertWithWhereUniqueWithoutHousesInput[]
  createMany?: Prisma.membersCreateManyHousesInputEnvelope
  set?: Prisma.membersWhereUniqueInput | Prisma.membersWhereUniqueInput[]
  disconnect?: Prisma.membersWhereUniqueInput | Prisma.membersWhereUniqueInput[]
  delete?: Prisma.membersWhereUniqueInput | Prisma.membersWhereUniqueInput[]
  connect?: Prisma.membersWhereUniqueInput | Prisma.membersWhereUniqueInput[]
  update?: Prisma.membersUpdateWithWhereUniqueWithoutHousesInput | Prisma.membersUpdateWithWhereUniqueWithoutHousesInput[]
  updateMany?: Prisma.membersUpdateManyWithWhereWithoutHousesInput | Prisma.membersUpdateManyWithWhereWithoutHousesInput[]
  deleteMany?: Prisma.membersScalarWhereInput | Prisma.membersScalarWhereInput[]
}

export type membersUncheckedUpdateManyWithoutHousesNestedInput = {
  create?: Prisma.XOR<Prisma.membersCreateWithoutHousesInput, Prisma.membersUncheckedCreateWithoutHousesInput> | Prisma.membersCreateWithoutHousesInput[] | Prisma.membersUncheckedCreateWithoutHousesInput[]
  connectOrCreate?: Prisma.membersCreateOrConnectWithoutHousesInput | Prisma.membersCreateOrConnectWithoutHousesInput[]
  upsert?: Prisma.membersUpsertWithWhereUniqueWithoutHousesInput | Prisma.membersUpsertWithWhereUniqueWithoutHousesInput[]
  createMany?: Prisma.membersCreateManyHousesInputEnvelope
  set?: Prisma.membersWhereUniqueInput | Prisma.membersWhereUniqueInput[]
  disconnect?: Prisma.membersWhereUniqueInput | Prisma.membersWhereUniqueInput[]
  delete?: Prisma.membersWhereUniqueInput | Prisma.membersWhereUniqueInput[]
  connect?: Prisma.membersWhereUniqueInput | Prisma.membersWhereUniqueInput[]
  update?: Prisma.membersUpdateWithWhereUniqueWithoutHousesInput | Prisma.membersUpdateWithWhereUniqueWithoutHousesInput[]
  updateMany?: Prisma.membersUpdateManyWithWhereWithoutHousesInput | Prisma.membersUpdateManyWithWhereWithoutHousesInput[]
  deleteMany?: Prisma.membersScalarWhereInput | Prisma.membersScalarWhereInput[]
}

export type NullableBoolFieldUpdateOperationsInput = {
  set?: boolean | null
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type membersCreateNestedOneWithoutParticipationsInput = {
  create?: Prisma.XOR<Prisma.membersCreateWithoutParticipationsInput, Prisma.membersUncheckedCreateWithoutParticipationsInput>
  connectOrCreate?: Prisma.membersCreateOrConnectWithoutParticipationsInput
  connect?: Prisma.membersWhereUniqueInput
}

export type membersUpdateOneWithoutParticipationsNestedInput = {
  create?: Prisma.XOR<Prisma.membersCreateWithoutParticipationsInput, Prisma.membersUncheckedCreateWithoutParticipationsInput>
  connectOrCreate?: Prisma.membersCreateOrConnectWithoutParticipationsInput
  upsert?: Prisma.membersUpsertWithoutParticipationsInput
  disconnect?: Prisma.membersWhereInput | boolean
  delete?: Prisma.membersWhereInput | boolean
  connect?: Prisma.membersWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.membersUpdateToOneWithWhereWithoutParticipationsInput, Prisma.membersUpdateWithoutParticipationsInput>, Prisma.membersUncheckedUpdateWithoutParticipationsInput>
}

export type membersCreateWithoutDirectivosInput = {
  cuenta: string
  nombre: string
  activo?: boolean | null
  fecha_ingreso: Date | string
  fecha_salida?: Date | string | null
  created_at?: Date | string | null
  user_id?: string | null
  houses?: Prisma.housesCreateNestedOneWithoutMembersInput
  participations?: Prisma.participationsCreateNestedManyWithoutMembersInput
}

export type membersUncheckedCreateWithoutDirectivosInput = {
  id?: number
  house_id?: number | null
  cuenta: string
  nombre: string
  activo?: boolean | null
  fecha_ingreso: Date | string
  fecha_salida?: Date | string | null
  created_at?: Date | string | null
  user_id?: string | null
  participations?: Prisma.participationsUncheckedCreateNestedManyWithoutMembersInput
}

export type membersCreateOrConnectWithoutDirectivosInput = {
  where: Prisma.membersWhereUniqueInput
  create: Prisma.XOR<Prisma.membersCreateWithoutDirectivosInput, Prisma.membersUncheckedCreateWithoutDirectivosInput>
}

export type membersUpsertWithoutDirectivosInput = {
  update: Prisma.XOR<Prisma.membersUpdateWithoutDirectivosInput, Prisma.membersUncheckedUpdateWithoutDirectivosInput>
  create: Prisma.XOR<Prisma.membersCreateWithoutDirectivosInput, Prisma.membersUncheckedCreateWithoutDirectivosInput>
  where?: Prisma.membersWhereInput
}

export type membersUpdateToOneWithWhereWithoutDirectivosInput = {
  where?: Prisma.membersWhereInput
  data: Prisma.XOR<Prisma.membersUpdateWithoutDirectivosInput, Prisma.membersUncheckedUpdateWithoutDirectivosInput>
}

export type membersUpdateWithoutDirectivosInput = {
  cuenta?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  activo?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  fecha_ingreso?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fecha_salida?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  houses?: Prisma.housesUpdateOneWithoutMembersNestedInput
  participations?: Prisma.participationsUpdateManyWithoutMembersNestedInput
}

export type membersUncheckedUpdateWithoutDirectivosInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  house_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  cuenta?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  activo?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  fecha_ingreso?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fecha_salida?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  participations?: Prisma.participationsUncheckedUpdateManyWithoutMembersNestedInput
}

export type membersCreateWithoutHousesInput = {
  cuenta: string
  nombre: string
  activo?: boolean | null
  fecha_ingreso: Date | string
  fecha_salida?: Date | string | null
  created_at?: Date | string | null
  user_id?: string | null
  directivos?: Prisma.directivosCreateNestedManyWithoutMembersInput
  participations?: Prisma.participationsCreateNestedManyWithoutMembersInput
}

export type membersUncheckedCreateWithoutHousesInput = {
  id?: number
  cuenta: string
  nombre: string
  activo?: boolean | null
  fecha_ingreso: Date | string
  fecha_salida?: Date | string | null
  created_at?: Date | string | null
  user_id?: string | null
  directivos?: Prisma.directivosUncheckedCreateNestedManyWithoutMembersInput
  participations?: Prisma.participationsUncheckedCreateNestedManyWithoutMembersInput
}

export type membersCreateOrConnectWithoutHousesInput = {
  where: Prisma.membersWhereUniqueInput
  create: Prisma.XOR<Prisma.membersCreateWithoutHousesInput, Prisma.membersUncheckedCreateWithoutHousesInput>
}

export type membersCreateManyHousesInputEnvelope = {
  data: Prisma.membersCreateManyHousesInput | Prisma.membersCreateManyHousesInput[]
  skipDuplicates?: boolean
}

export type membersUpsertWithWhereUniqueWithoutHousesInput = {
  where: Prisma.membersWhereUniqueInput
  update: Prisma.XOR<Prisma.membersUpdateWithoutHousesInput, Prisma.membersUncheckedUpdateWithoutHousesInput>
  create: Prisma.XOR<Prisma.membersCreateWithoutHousesInput, Prisma.membersUncheckedCreateWithoutHousesInput>
}

export type membersUpdateWithWhereUniqueWithoutHousesInput = {
  where: Prisma.membersWhereUniqueInput
  data: Prisma.XOR<Prisma.membersUpdateWithoutHousesInput, Prisma.membersUncheckedUpdateWithoutHousesInput>
}

export type membersUpdateManyWithWhereWithoutHousesInput = {
  where: Prisma.membersScalarWhereInput
  data: Prisma.XOR<Prisma.membersUpdateManyMutationInput, Prisma.membersUncheckedUpdateManyWithoutHousesInput>
}

export type membersScalarWhereInput = {
  AND?: Prisma.membersScalarWhereInput | Prisma.membersScalarWhereInput[]
  OR?: Prisma.membersScalarWhereInput[]
  NOT?: Prisma.membersScalarWhereInput | Prisma.membersScalarWhereInput[]
  id?: Prisma.IntFilter<"members"> | number
  house_id?: Prisma.IntNullableFilter<"members"> | number | null
  cuenta?: Prisma.StringFilter<"members"> | string
  nombre?: Prisma.StringFilter<"members"> | string
  activo?: Prisma.BoolNullableFilter<"members"> | boolean | null
  fecha_ingreso?: Prisma.DateTimeFilter<"members"> | Date | string
  fecha_salida?: Prisma.DateTimeNullableFilter<"members"> | Date | string | null
  created_at?: Prisma.DateTimeNullableFilter<"members"> | Date | string | null
  user_id?: Prisma.UuidNullableFilter<"members"> | string | null
}

export type membersCreateWithoutParticipationsInput = {
  cuenta: string
  nombre: string
  activo?: boolean | null
  fecha_ingreso: Date | string
  fecha_salida?: Date | string | null
  created_at?: Date | string | null
  user_id?: string | null
  directivos?: Prisma.directivosCreateNestedManyWithoutMembersInput
  houses?: Prisma.housesCreateNestedOneWithoutMembersInput
}

export type membersUncheckedCreateWithoutParticipationsInput = {
  id?: number
  house_id?: number | null
  cuenta: string
  nombre: string
  activo?: boolean | null
  fecha_ingreso: Date | string
  fecha_salida?: Date | string | null
  created_at?: Date | string | null
  user_id?: string | null
  directivos?: Prisma.directivosUncheckedCreateNestedManyWithoutMembersInput
}

export type membersCreateOrConnectWithoutParticipationsInput = {
  where: Prisma.membersWhereUniqueInput
  create: Prisma.XOR<Prisma.membersCreateWithoutParticipationsInput, Prisma.membersUncheckedCreateWithoutParticipationsInput>
}

export type membersUpsertWithoutParticipationsInput = {
  update: Prisma.XOR<Prisma.membersUpdateWithoutParticipationsInput, Prisma.membersUncheckedUpdateWithoutParticipationsInput>
  create: Prisma.XOR<Prisma.membersCreateWithoutParticipationsInput, Prisma.membersUncheckedCreateWithoutParticipationsInput>
  where?: Prisma.membersWhereInput
}

export type membersUpdateToOneWithWhereWithoutParticipationsInput = {
  where?: Prisma.membersWhereInput
  data: Prisma.XOR<Prisma.membersUpdateWithoutParticipationsInput, Prisma.membersUncheckedUpdateWithoutParticipationsInput>
}

export type membersUpdateWithoutParticipationsInput = {
  cuenta?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  activo?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  fecha_ingreso?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fecha_salida?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  directivos?: Prisma.directivosUpdateManyWithoutMembersNestedInput
  houses?: Prisma.housesUpdateOneWithoutMembersNestedInput
}

export type membersUncheckedUpdateWithoutParticipationsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  house_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  cuenta?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  activo?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  fecha_ingreso?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fecha_salida?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  directivos?: Prisma.directivosUncheckedUpdateManyWithoutMembersNestedInput
}

export type membersCreateManyHousesInput = {
  id?: number
  cuenta: string
  nombre: string
  activo?: boolean | null
  fecha_ingreso: Date | string
  fecha_salida?: Date | string | null
  created_at?: Date | string | null
  user_id?: string | null
}

export type membersUpdateWithoutHousesInput = {
  cuenta?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  activo?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  fecha_ingreso?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fecha_salida?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  directivos?: Prisma.directivosUpdateManyWithoutMembersNestedInput
  participations?: Prisma.participationsUpdateManyWithoutMembersNestedInput
}

export type membersUncheckedUpdateWithoutHousesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  cuenta?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  activo?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  fecha_ingreso?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fecha_salida?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  directivos?: Prisma.directivosUncheckedUpdateManyWithoutMembersNestedInput
  participations?: Prisma.participationsUncheckedUpdateManyWithoutMembersNestedInput
}

export type membersUncheckedUpdateManyWithoutHousesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  cuenta?: Prisma.StringFieldUpdateOperationsInput | string
  nombre?: Prisma.StringFieldUpdateOperationsInput | string
  activo?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  fecha_ingreso?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  fecha_salida?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user_id?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type MembersCountOutputType
 */

export type MembersCountOutputType = {
  directivos: number
  participations: number
}

export type MembersCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  directivos?: boolean | MembersCountOutputTypeCountDirectivosArgs
  participations?: boolean | MembersCountOutputTypeCountParticipationsArgs
}

/**
 * MembersCountOutputType without action
 */
export type MembersCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MembersCountOutputType
   */
  select?: Prisma.MembersCountOutputTypeSelect<ExtArgs> | null
}

/**
 * MembersCountOutputType without action
 */
export type MembersCountOutputTypeCountDirectivosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.directivosWhereInput
}

/**
 * MembersCountOutputType without action
 */
export type MembersCountOutputTypeCountParticipationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.participationsWhereInput
}


export type membersSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  house_id?: boolean
  cuenta?: boolean
  nombre?: boolean
  activo?: boolean
  fecha_ingreso?: boolean
  fecha_salida?: boolean
  created_at?: boolean
  user_id?: boolean
  directivos?: boolean | Prisma.members$directivosArgs<ExtArgs>
  houses?: boolean | Prisma.members$housesArgs<ExtArgs>
  participations?: boolean | Prisma.members$participationsArgs<ExtArgs>
  _count?: boolean | Prisma.MembersCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["members"]>

export type membersSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  house_id?: boolean
  cuenta?: boolean
  nombre?: boolean
  activo?: boolean
  fecha_ingreso?: boolean
  fecha_salida?: boolean
  created_at?: boolean
  user_id?: boolean
  houses?: boolean | Prisma.members$housesArgs<ExtArgs>
}, ExtArgs["result"]["members"]>

export type membersSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  house_id?: boolean
  cuenta?: boolean
  nombre?: boolean
  activo?: boolean
  fecha_ingreso?: boolean
  fecha_salida?: boolean
  created_at?: boolean
  user_id?: boolean
  houses?: boolean | Prisma.members$housesArgs<ExtArgs>
}, ExtArgs["result"]["members"]>

export type membersSelectScalar = {
  id?: boolean
  house_id?: boolean
  cuenta?: boolean
  nombre?: boolean
  activo?: boolean
  fecha_ingreso?: boolean
  fecha_salida?: boolean
  created_at?: boolean
  user_id?: boolean
}

export type membersOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "house_id" | "cuenta" | "nombre" | "activo" | "fecha_ingreso" | "fecha_salida" | "created_at" | "user_id", ExtArgs["result"]["members"]>
export type membersInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  directivos?: boolean | Prisma.members$directivosArgs<ExtArgs>
  houses?: boolean | Prisma.members$housesArgs<ExtArgs>
  participations?: boolean | Prisma.members$participationsArgs<ExtArgs>
  _count?: boolean | Prisma.MembersCountOutputTypeDefaultArgs<ExtArgs>
}
export type membersIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  houses?: boolean | Prisma.members$housesArgs<ExtArgs>
}
export type membersIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  houses?: boolean | Prisma.members$housesArgs<ExtArgs>
}

export type $membersPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "members"
  objects: {
    directivos: Prisma.$directivosPayload<ExtArgs>[]
    houses: Prisma.$housesPayload<ExtArgs> | null
    participations: Prisma.$participationsPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    house_id: number | null
    cuenta: string
    nombre: string
    activo: boolean | null
    fecha_ingreso: Date
    fecha_salida: Date | null
    created_at: Date | null
    user_id: string | null
  }, ExtArgs["result"]["members"]>
  composites: {}
}

export type membersGetPayload<S extends boolean | null | undefined | membersDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$membersPayload, S>

export type membersCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<membersFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MembersCountAggregateInputType | true
  }

export interface membersDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['members'], meta: { name: 'members' } }
  /**
   * Find zero or one Members that matches the filter.
   * @param {membersFindUniqueArgs} args - Arguments to find a Members
   * @example
   * // Get one Members
   * const members = await prisma.members.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends membersFindUniqueArgs>(args: Prisma.SelectSubset<T, membersFindUniqueArgs<ExtArgs>>): Prisma.Prisma__membersClient<runtime.Types.Result.GetResult<Prisma.$membersPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Members that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {membersFindUniqueOrThrowArgs} args - Arguments to find a Members
   * @example
   * // Get one Members
   * const members = await prisma.members.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends membersFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, membersFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__membersClient<runtime.Types.Result.GetResult<Prisma.$membersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Members that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {membersFindFirstArgs} args - Arguments to find a Members
   * @example
   * // Get one Members
   * const members = await prisma.members.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends membersFindFirstArgs>(args?: Prisma.SelectSubset<T, membersFindFirstArgs<ExtArgs>>): Prisma.Prisma__membersClient<runtime.Types.Result.GetResult<Prisma.$membersPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Members that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {membersFindFirstOrThrowArgs} args - Arguments to find a Members
   * @example
   * // Get one Members
   * const members = await prisma.members.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends membersFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, membersFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__membersClient<runtime.Types.Result.GetResult<Prisma.$membersPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Members that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {membersFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Members
   * const members = await prisma.members.findMany()
   * 
   * // Get first 10 Members
   * const members = await prisma.members.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const membersWithIdOnly = await prisma.members.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends membersFindManyArgs>(args?: Prisma.SelectSubset<T, membersFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$membersPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Members.
   * @param {membersCreateArgs} args - Arguments to create a Members.
   * @example
   * // Create one Members
   * const Members = await prisma.members.create({
   *   data: {
   *     // ... data to create a Members
   *   }
   * })
   * 
   */
  create<T extends membersCreateArgs>(args: Prisma.SelectSubset<T, membersCreateArgs<ExtArgs>>): Prisma.Prisma__membersClient<runtime.Types.Result.GetResult<Prisma.$membersPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Members.
   * @param {membersCreateManyArgs} args - Arguments to create many Members.
   * @example
   * // Create many Members
   * const members = await prisma.members.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends membersCreateManyArgs>(args?: Prisma.SelectSubset<T, membersCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Members and returns the data saved in the database.
   * @param {membersCreateManyAndReturnArgs} args - Arguments to create many Members.
   * @example
   * // Create many Members
   * const members = await prisma.members.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Members and only return the `id`
   * const membersWithIdOnly = await prisma.members.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends membersCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, membersCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$membersPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Members.
   * @param {membersDeleteArgs} args - Arguments to delete one Members.
   * @example
   * // Delete one Members
   * const Members = await prisma.members.delete({
   *   where: {
   *     // ... filter to delete one Members
   *   }
   * })
   * 
   */
  delete<T extends membersDeleteArgs>(args: Prisma.SelectSubset<T, membersDeleteArgs<ExtArgs>>): Prisma.Prisma__membersClient<runtime.Types.Result.GetResult<Prisma.$membersPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Members.
   * @param {membersUpdateArgs} args - Arguments to update one Members.
   * @example
   * // Update one Members
   * const members = await prisma.members.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends membersUpdateArgs>(args: Prisma.SelectSubset<T, membersUpdateArgs<ExtArgs>>): Prisma.Prisma__membersClient<runtime.Types.Result.GetResult<Prisma.$membersPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Members.
   * @param {membersDeleteManyArgs} args - Arguments to filter Members to delete.
   * @example
   * // Delete a few Members
   * const { count } = await prisma.members.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends membersDeleteManyArgs>(args?: Prisma.SelectSubset<T, membersDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Members.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {membersUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Members
   * const members = await prisma.members.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends membersUpdateManyArgs>(args: Prisma.SelectSubset<T, membersUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Members and returns the data updated in the database.
   * @param {membersUpdateManyAndReturnArgs} args - Arguments to update many Members.
   * @example
   * // Update many Members
   * const members = await prisma.members.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Members and only return the `id`
   * const membersWithIdOnly = await prisma.members.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends membersUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, membersUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$membersPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Members.
   * @param {membersUpsertArgs} args - Arguments to update or create a Members.
   * @example
   * // Update or create a Members
   * const members = await prisma.members.upsert({
   *   create: {
   *     // ... data to create a Members
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Members we want to update
   *   }
   * })
   */
  upsert<T extends membersUpsertArgs>(args: Prisma.SelectSubset<T, membersUpsertArgs<ExtArgs>>): Prisma.Prisma__membersClient<runtime.Types.Result.GetResult<Prisma.$membersPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Members.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {membersCountArgs} args - Arguments to filter Members to count.
   * @example
   * // Count the number of Members
   * const count = await prisma.members.count({
   *   where: {
   *     // ... the filter for the Members we want to count
   *   }
   * })
  **/
  count<T extends membersCountArgs>(
    args?: Prisma.Subset<T, membersCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MembersCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Members.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MembersAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MembersAggregateArgs>(args: Prisma.Subset<T, MembersAggregateArgs>): Prisma.PrismaPromise<GetMembersAggregateType<T>>

  /**
   * Group by Members.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {membersGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends membersGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: membersGroupByArgs['orderBy'] }
      : { orderBy?: membersGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, membersGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMembersGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the members model
 */
readonly fields: membersFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for members.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__membersClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  directivos<T extends Prisma.members$directivosArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.members$directivosArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$directivosPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  houses<T extends Prisma.members$housesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.members$housesArgs<ExtArgs>>): Prisma.Prisma__housesClient<runtime.Types.Result.GetResult<Prisma.$housesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  participations<T extends Prisma.members$participationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.members$participationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$participationsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the members model
 */
export interface membersFieldRefs {
  readonly id: Prisma.FieldRef<"members", 'Int'>
  readonly house_id: Prisma.FieldRef<"members", 'Int'>
  readonly cuenta: Prisma.FieldRef<"members", 'String'>
  readonly nombre: Prisma.FieldRef<"members", 'String'>
  readonly activo: Prisma.FieldRef<"members", 'Boolean'>
  readonly fecha_ingreso: Prisma.FieldRef<"members", 'DateTime'>
  readonly fecha_salida: Prisma.FieldRef<"members", 'DateTime'>
  readonly created_at: Prisma.FieldRef<"members", 'DateTime'>
  readonly user_id: Prisma.FieldRef<"members", 'String'>
}
    

// Custom InputTypes
/**
 * members findUnique
 */
export type membersFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the members
   */
  select?: Prisma.membersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the members
   */
  omit?: Prisma.membersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.membersInclude<ExtArgs> | null
  /**
   * Filter, which members to fetch.
   */
  where: Prisma.membersWhereUniqueInput
}

/**
 * members findUniqueOrThrow
 */
export type membersFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the members
   */
  select?: Prisma.membersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the members
   */
  omit?: Prisma.membersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.membersInclude<ExtArgs> | null
  /**
   * Filter, which members to fetch.
   */
  where: Prisma.membersWhereUniqueInput
}

/**
 * members findFirst
 */
export type membersFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the members
   */
  select?: Prisma.membersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the members
   */
  omit?: Prisma.membersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.membersInclude<ExtArgs> | null
  /**
   * Filter, which members to fetch.
   */
  where?: Prisma.membersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of members to fetch.
   */
  orderBy?: Prisma.membersOrderByWithRelationInput | Prisma.membersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for members.
   */
  cursor?: Prisma.membersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` members from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` members.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of members.
   */
  distinct?: Prisma.MembersScalarFieldEnum | Prisma.MembersScalarFieldEnum[]
}

/**
 * members findFirstOrThrow
 */
export type membersFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the members
   */
  select?: Prisma.membersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the members
   */
  omit?: Prisma.membersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.membersInclude<ExtArgs> | null
  /**
   * Filter, which members to fetch.
   */
  where?: Prisma.membersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of members to fetch.
   */
  orderBy?: Prisma.membersOrderByWithRelationInput | Prisma.membersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for members.
   */
  cursor?: Prisma.membersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` members from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` members.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of members.
   */
  distinct?: Prisma.MembersScalarFieldEnum | Prisma.MembersScalarFieldEnum[]
}

/**
 * members findMany
 */
export type membersFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the members
   */
  select?: Prisma.membersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the members
   */
  omit?: Prisma.membersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.membersInclude<ExtArgs> | null
  /**
   * Filter, which members to fetch.
   */
  where?: Prisma.membersWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of members to fetch.
   */
  orderBy?: Prisma.membersOrderByWithRelationInput | Prisma.membersOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing members.
   */
  cursor?: Prisma.membersWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` members from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` members.
   */
  skip?: number
  distinct?: Prisma.MembersScalarFieldEnum | Prisma.MembersScalarFieldEnum[]
}

/**
 * members create
 */
export type membersCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the members
   */
  select?: Prisma.membersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the members
   */
  omit?: Prisma.membersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.membersInclude<ExtArgs> | null
  /**
   * The data needed to create a members.
   */
  data: Prisma.XOR<Prisma.membersCreateInput, Prisma.membersUncheckedCreateInput>
}

/**
 * members createMany
 */
export type membersCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many members.
   */
  data: Prisma.membersCreateManyInput | Prisma.membersCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * members createManyAndReturn
 */
export type membersCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the members
   */
  select?: Prisma.membersSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the members
   */
  omit?: Prisma.membersOmit<ExtArgs> | null
  /**
   * The data used to create many members.
   */
  data: Prisma.membersCreateManyInput | Prisma.membersCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.membersIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * members update
 */
export type membersUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the members
   */
  select?: Prisma.membersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the members
   */
  omit?: Prisma.membersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.membersInclude<ExtArgs> | null
  /**
   * The data needed to update a members.
   */
  data: Prisma.XOR<Prisma.membersUpdateInput, Prisma.membersUncheckedUpdateInput>
  /**
   * Choose, which members to update.
   */
  where: Prisma.membersWhereUniqueInput
}

/**
 * members updateMany
 */
export type membersUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update members.
   */
  data: Prisma.XOR<Prisma.membersUpdateManyMutationInput, Prisma.membersUncheckedUpdateManyInput>
  /**
   * Filter which members to update
   */
  where?: Prisma.membersWhereInput
  /**
   * Limit how many members to update.
   */
  limit?: number
}

/**
 * members updateManyAndReturn
 */
export type membersUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the members
   */
  select?: Prisma.membersSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the members
   */
  omit?: Prisma.membersOmit<ExtArgs> | null
  /**
   * The data used to update members.
   */
  data: Prisma.XOR<Prisma.membersUpdateManyMutationInput, Prisma.membersUncheckedUpdateManyInput>
  /**
   * Filter which members to update
   */
  where?: Prisma.membersWhereInput
  /**
   * Limit how many members to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.membersIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * members upsert
 */
export type membersUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the members
   */
  select?: Prisma.membersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the members
   */
  omit?: Prisma.membersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.membersInclude<ExtArgs> | null
  /**
   * The filter to search for the members to update in case it exists.
   */
  where: Prisma.membersWhereUniqueInput
  /**
   * In case the members found by the `where` argument doesn't exist, create a new members with this data.
   */
  create: Prisma.XOR<Prisma.membersCreateInput, Prisma.membersUncheckedCreateInput>
  /**
   * In case the members was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.membersUpdateInput, Prisma.membersUncheckedUpdateInput>
}

/**
 * members delete
 */
export type membersDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the members
   */
  select?: Prisma.membersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the members
   */
  omit?: Prisma.membersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.membersInclude<ExtArgs> | null
  /**
   * Filter which members to delete.
   */
  where: Prisma.membersWhereUniqueInput
}

/**
 * members deleteMany
 */
export type membersDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which members to delete
   */
  where?: Prisma.membersWhereInput
  /**
   * Limit how many members to delete.
   */
  limit?: number
}

/**
 * members.directivos
 */
export type members$directivosArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the directivos
   */
  select?: Prisma.directivosSelect<ExtArgs> | null
  /**
   * Omit specific fields from the directivos
   */
  omit?: Prisma.directivosOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.directivosInclude<ExtArgs> | null
  where?: Prisma.directivosWhereInput
  orderBy?: Prisma.directivosOrderByWithRelationInput | Prisma.directivosOrderByWithRelationInput[]
  cursor?: Prisma.directivosWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.DirectivosScalarFieldEnum | Prisma.DirectivosScalarFieldEnum[]
}

/**
 * members.houses
 */
export type members$housesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the houses
   */
  select?: Prisma.housesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the houses
   */
  omit?: Prisma.housesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.housesInclude<ExtArgs> | null
  where?: Prisma.housesWhereInput
}

/**
 * members.participations
 */
export type members$participationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the participations
   */
  select?: Prisma.participationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the participations
   */
  omit?: Prisma.participationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.participationsInclude<ExtArgs> | null
  where?: Prisma.participationsWhereInput
  orderBy?: Prisma.participationsOrderByWithRelationInput | Prisma.participationsOrderByWithRelationInput[]
  cursor?: Prisma.participationsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ParticipationsScalarFieldEnum | Prisma.ParticipationsScalarFieldEnum[]
}

/**
 * members without action
 */
export type membersDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the members
   */
  select?: Prisma.membersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the members
   */
  omit?: Prisma.membersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.membersInclude<ExtArgs> | null
}
