
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `participations` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model participations
 * This model or at least one of its fields has comments in the database, and requires an additional setup for migrations: Read more: https://pris.ly/d/database-comments
 * This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info.
 */
export type participationsModel = runtime.Types.Result.DefaultSelection<Prisma.$participationsPayload>

export type AggregateParticipations = {
  _count: ParticipationsCountAggregateOutputType | null
  _avg: ParticipationsAvgAggregateOutputType | null
  _sum: ParticipationsSumAggregateOutputType | null
  _min: ParticipationsMinAggregateOutputType | null
  _max: ParticipationsMaxAggregateOutputType | null
}

export type ParticipationsAvgAggregateOutputType = {
  id: number | null
  member_id: number | null
  show_id: number | null
  points: number | null
}

export type ParticipationsSumAggregateOutputType = {
  id: number | null
  member_id: number | null
  show_id: number | null
  points: number | null
}

export type ParticipationsMinAggregateOutputType = {
  id: number | null
  member_id: number | null
  show_id: number | null
  status: string | null
  points: number | null
  updated_at: Date | null
  notes: string | null
}

export type ParticipationsMaxAggregateOutputType = {
  id: number | null
  member_id: number | null
  show_id: number | null
  status: string | null
  points: number | null
  updated_at: Date | null
  notes: string | null
}

export type ParticipationsCountAggregateOutputType = {
  id: number
  member_id: number
  show_id: number
  status: number
  points: number
  updated_at: number
  notes: number
  _all: number
}


export type ParticipationsAvgAggregateInputType = {
  id?: true
  member_id?: true
  show_id?: true
  points?: true
}

export type ParticipationsSumAggregateInputType = {
  id?: true
  member_id?: true
  show_id?: true
  points?: true
}

export type ParticipationsMinAggregateInputType = {
  id?: true
  member_id?: true
  show_id?: true
  status?: true
  points?: true
  updated_at?: true
  notes?: true
}

export type ParticipationsMaxAggregateInputType = {
  id?: true
  member_id?: true
  show_id?: true
  status?: true
  points?: true
  updated_at?: true
  notes?: true
}

export type ParticipationsCountAggregateInputType = {
  id?: true
  member_id?: true
  show_id?: true
  status?: true
  points?: true
  updated_at?: true
  notes?: true
  _all?: true
}

export type ParticipationsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which participations to aggregate.
   */
  where?: Prisma.participationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of participations to fetch.
   */
  orderBy?: Prisma.participationsOrderByWithRelationInput | Prisma.participationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.participationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` participations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` participations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned participations
  **/
  _count?: true | ParticipationsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ParticipationsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ParticipationsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ParticipationsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ParticipationsMaxAggregateInputType
}

export type GetParticipationsAggregateType<T extends ParticipationsAggregateArgs> = {
      [P in keyof T & keyof AggregateParticipations]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateParticipations[P]>
    : Prisma.GetScalarType<T[P], AggregateParticipations[P]>
}




export type participationsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.participationsWhereInput
  orderBy?: Prisma.participationsOrderByWithAggregationInput | Prisma.participationsOrderByWithAggregationInput[]
  by: Prisma.ParticipationsScalarFieldEnum[] | Prisma.ParticipationsScalarFieldEnum
  having?: Prisma.participationsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ParticipationsCountAggregateInputType | true
  _avg?: ParticipationsAvgAggregateInputType
  _sum?: ParticipationsSumAggregateInputType
  _min?: ParticipationsMinAggregateInputType
  _max?: ParticipationsMaxAggregateInputType
}

export type ParticipationsGroupByOutputType = {
  id: number
  member_id: number | null
  show_id: number | null
  status: string | null
  points: number | null
  updated_at: Date | null
  notes: string | null
  _count: ParticipationsCountAggregateOutputType | null
  _avg: ParticipationsAvgAggregateOutputType | null
  _sum: ParticipationsSumAggregateOutputType | null
  _min: ParticipationsMinAggregateOutputType | null
  _max: ParticipationsMaxAggregateOutputType | null
}

type GetParticipationsGroupByPayload<T extends participationsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ParticipationsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ParticipationsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ParticipationsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ParticipationsGroupByOutputType[P]>
      }
    >
  >



export type participationsWhereInput = {
  AND?: Prisma.participationsWhereInput | Prisma.participationsWhereInput[]
  OR?: Prisma.participationsWhereInput[]
  NOT?: Prisma.participationsWhereInput | Prisma.participationsWhereInput[]
  id?: Prisma.IntFilter<"participations"> | number
  member_id?: Prisma.IntNullableFilter<"participations"> | number | null
  show_id?: Prisma.IntNullableFilter<"participations"> | number | null
  status?: Prisma.StringNullableFilter<"participations"> | string | null
  points?: Prisma.IntNullableFilter<"participations"> | number | null
  updated_at?: Prisma.DateTimeNullableFilter<"participations"> | Date | string | null
  notes?: Prisma.StringNullableFilter<"participations"> | string | null
  members?: Prisma.XOR<Prisma.MembersNullableScalarRelationFilter, Prisma.membersWhereInput> | null
  shows?: Prisma.XOR<Prisma.ShowsNullableScalarRelationFilter, Prisma.showsWhereInput> | null
}

export type participationsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  member_id?: Prisma.SortOrderInput | Prisma.SortOrder
  show_id?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  points?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  members?: Prisma.membersOrderByWithRelationInput
  shows?: Prisma.showsOrderByWithRelationInput
}

export type participationsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.participationsWhereInput | Prisma.participationsWhereInput[]
  OR?: Prisma.participationsWhereInput[]
  NOT?: Prisma.participationsWhereInput | Prisma.participationsWhereInput[]
  member_id?: Prisma.IntNullableFilter<"participations"> | number | null
  show_id?: Prisma.IntNullableFilter<"participations"> | number | null
  status?: Prisma.StringNullableFilter<"participations"> | string | null
  points?: Prisma.IntNullableFilter<"participations"> | number | null
  updated_at?: Prisma.DateTimeNullableFilter<"participations"> | Date | string | null
  notes?: Prisma.StringNullableFilter<"participations"> | string | null
  members?: Prisma.XOR<Prisma.MembersNullableScalarRelationFilter, Prisma.membersWhereInput> | null
  shows?: Prisma.XOR<Prisma.ShowsNullableScalarRelationFilter, Prisma.showsWhereInput> | null
}, "id">

export type participationsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  member_id?: Prisma.SortOrderInput | Prisma.SortOrder
  show_id?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrderInput | Prisma.SortOrder
  points?: Prisma.SortOrderInput | Prisma.SortOrder
  updated_at?: Prisma.SortOrderInput | Prisma.SortOrder
  notes?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.participationsCountOrderByAggregateInput
  _avg?: Prisma.participationsAvgOrderByAggregateInput
  _max?: Prisma.participationsMaxOrderByAggregateInput
  _min?: Prisma.participationsMinOrderByAggregateInput
  _sum?: Prisma.participationsSumOrderByAggregateInput
}

export type participationsScalarWhereWithAggregatesInput = {
  AND?: Prisma.participationsScalarWhereWithAggregatesInput | Prisma.participationsScalarWhereWithAggregatesInput[]
  OR?: Prisma.participationsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.participationsScalarWhereWithAggregatesInput | Prisma.participationsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"participations"> | number
  member_id?: Prisma.IntNullableWithAggregatesFilter<"participations"> | number | null
  show_id?: Prisma.IntNullableWithAggregatesFilter<"participations"> | number | null
  status?: Prisma.StringNullableWithAggregatesFilter<"participations"> | string | null
  points?: Prisma.IntNullableWithAggregatesFilter<"participations"> | number | null
  updated_at?: Prisma.DateTimeNullableWithAggregatesFilter<"participations"> | Date | string | null
  notes?: Prisma.StringNullableWithAggregatesFilter<"participations"> | string | null
}

export type participationsCreateInput = {
  status?: string | null
  points?: number | null
  updated_at?: Date | string | null
  notes?: string | null
  members?: Prisma.membersCreateNestedOneWithoutParticipationsInput
  shows?: Prisma.showsCreateNestedOneWithoutParticipationsInput
}

export type participationsUncheckedCreateInput = {
  id?: number
  member_id?: number | null
  show_id?: number | null
  status?: string | null
  points?: number | null
  updated_at?: Date | string | null
  notes?: string | null
}

export type participationsUpdateInput = {
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  points?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  members?: Prisma.membersUpdateOneWithoutParticipationsNestedInput
  shows?: Prisma.showsUpdateOneWithoutParticipationsNestedInput
}

export type participationsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  member_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  show_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  points?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type participationsCreateManyInput = {
  id?: number
  member_id?: number | null
  show_id?: number | null
  status?: string | null
  points?: number | null
  updated_at?: Date | string | null
  notes?: string | null
}

export type participationsUpdateManyMutationInput = {
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  points?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type participationsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  member_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  show_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  points?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type ParticipationsListRelationFilter = {
  every?: Prisma.participationsWhereInput
  some?: Prisma.participationsWhereInput
  none?: Prisma.participationsWhereInput
}

export type participationsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type participationsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  member_id?: Prisma.SortOrder
  show_id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  points?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  notes?: Prisma.SortOrder
}

export type participationsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  member_id?: Prisma.SortOrder
  show_id?: Prisma.SortOrder
  points?: Prisma.SortOrder
}

export type participationsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  member_id?: Prisma.SortOrder
  show_id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  points?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  notes?: Prisma.SortOrder
}

export type participationsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  member_id?: Prisma.SortOrder
  show_id?: Prisma.SortOrder
  status?: Prisma.SortOrder
  points?: Prisma.SortOrder
  updated_at?: Prisma.SortOrder
  notes?: Prisma.SortOrder
}

export type participationsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  member_id?: Prisma.SortOrder
  show_id?: Prisma.SortOrder
  points?: Prisma.SortOrder
}

export type participationsCreateNestedManyWithoutMembersInput = {
  create?: Prisma.XOR<Prisma.participationsCreateWithoutMembersInput, Prisma.participationsUncheckedCreateWithoutMembersInput> | Prisma.participationsCreateWithoutMembersInput[] | Prisma.participationsUncheckedCreateWithoutMembersInput[]
  connectOrCreate?: Prisma.participationsCreateOrConnectWithoutMembersInput | Prisma.participationsCreateOrConnectWithoutMembersInput[]
  createMany?: Prisma.participationsCreateManyMembersInputEnvelope
  connect?: Prisma.participationsWhereUniqueInput | Prisma.participationsWhereUniqueInput[]
}

export type participationsUncheckedCreateNestedManyWithoutMembersInput = {
  create?: Prisma.XOR<Prisma.participationsCreateWithoutMembersInput, Prisma.participationsUncheckedCreateWithoutMembersInput> | Prisma.participationsCreateWithoutMembersInput[] | Prisma.participationsUncheckedCreateWithoutMembersInput[]
  connectOrCreate?: Prisma.participationsCreateOrConnectWithoutMembersInput | Prisma.participationsCreateOrConnectWithoutMembersInput[]
  createMany?: Prisma.participationsCreateManyMembersInputEnvelope
  connect?: Prisma.participationsWhereUniqueInput | Prisma.participationsWhereUniqueInput[]
}

export type participationsUpdateManyWithoutMembersNestedInput = {
  create?: Prisma.XOR<Prisma.participationsCreateWithoutMembersInput, Prisma.participationsUncheckedCreateWithoutMembersInput> | Prisma.participationsCreateWithoutMembersInput[] | Prisma.participationsUncheckedCreateWithoutMembersInput[]
  connectOrCreate?: Prisma.participationsCreateOrConnectWithoutMembersInput | Prisma.participationsCreateOrConnectWithoutMembersInput[]
  upsert?: Prisma.participationsUpsertWithWhereUniqueWithoutMembersInput | Prisma.participationsUpsertWithWhereUniqueWithoutMembersInput[]
  createMany?: Prisma.participationsCreateManyMembersInputEnvelope
  set?: Prisma.participationsWhereUniqueInput | Prisma.participationsWhereUniqueInput[]
  disconnect?: Prisma.participationsWhereUniqueInput | Prisma.participationsWhereUniqueInput[]
  delete?: Prisma.participationsWhereUniqueInput | Prisma.participationsWhereUniqueInput[]
  connect?: Prisma.participationsWhereUniqueInput | Prisma.participationsWhereUniqueInput[]
  update?: Prisma.participationsUpdateWithWhereUniqueWithoutMembersInput | Prisma.participationsUpdateWithWhereUniqueWithoutMembersInput[]
  updateMany?: Prisma.participationsUpdateManyWithWhereWithoutMembersInput | Prisma.participationsUpdateManyWithWhereWithoutMembersInput[]
  deleteMany?: Prisma.participationsScalarWhereInput | Prisma.participationsScalarWhereInput[]
}

export type participationsUncheckedUpdateManyWithoutMembersNestedInput = {
  create?: Prisma.XOR<Prisma.participationsCreateWithoutMembersInput, Prisma.participationsUncheckedCreateWithoutMembersInput> | Prisma.participationsCreateWithoutMembersInput[] | Prisma.participationsUncheckedCreateWithoutMembersInput[]
  connectOrCreate?: Prisma.participationsCreateOrConnectWithoutMembersInput | Prisma.participationsCreateOrConnectWithoutMembersInput[]
  upsert?: Prisma.participationsUpsertWithWhereUniqueWithoutMembersInput | Prisma.participationsUpsertWithWhereUniqueWithoutMembersInput[]
  createMany?: Prisma.participationsCreateManyMembersInputEnvelope
  set?: Prisma.participationsWhereUniqueInput | Prisma.participationsWhereUniqueInput[]
  disconnect?: Prisma.participationsWhereUniqueInput | Prisma.participationsWhereUniqueInput[]
  delete?: Prisma.participationsWhereUniqueInput | Prisma.participationsWhereUniqueInput[]
  connect?: Prisma.participationsWhereUniqueInput | Prisma.participationsWhereUniqueInput[]
  update?: Prisma.participationsUpdateWithWhereUniqueWithoutMembersInput | Prisma.participationsUpdateWithWhereUniqueWithoutMembersInput[]
  updateMany?: Prisma.participationsUpdateManyWithWhereWithoutMembersInput | Prisma.participationsUpdateManyWithWhereWithoutMembersInput[]
  deleteMany?: Prisma.participationsScalarWhereInput | Prisma.participationsScalarWhereInput[]
}

export type participationsCreateNestedManyWithoutShowsInput = {
  create?: Prisma.XOR<Prisma.participationsCreateWithoutShowsInput, Prisma.participationsUncheckedCreateWithoutShowsInput> | Prisma.participationsCreateWithoutShowsInput[] | Prisma.participationsUncheckedCreateWithoutShowsInput[]
  connectOrCreate?: Prisma.participationsCreateOrConnectWithoutShowsInput | Prisma.participationsCreateOrConnectWithoutShowsInput[]
  createMany?: Prisma.participationsCreateManyShowsInputEnvelope
  connect?: Prisma.participationsWhereUniqueInput | Prisma.participationsWhereUniqueInput[]
}

export type participationsUncheckedCreateNestedManyWithoutShowsInput = {
  create?: Prisma.XOR<Prisma.participationsCreateWithoutShowsInput, Prisma.participationsUncheckedCreateWithoutShowsInput> | Prisma.participationsCreateWithoutShowsInput[] | Prisma.participationsUncheckedCreateWithoutShowsInput[]
  connectOrCreate?: Prisma.participationsCreateOrConnectWithoutShowsInput | Prisma.participationsCreateOrConnectWithoutShowsInput[]
  createMany?: Prisma.participationsCreateManyShowsInputEnvelope
  connect?: Prisma.participationsWhereUniqueInput | Prisma.participationsWhereUniqueInput[]
}

export type participationsUpdateManyWithoutShowsNestedInput = {
  create?: Prisma.XOR<Prisma.participationsCreateWithoutShowsInput, Prisma.participationsUncheckedCreateWithoutShowsInput> | Prisma.participationsCreateWithoutShowsInput[] | Prisma.participationsUncheckedCreateWithoutShowsInput[]
  connectOrCreate?: Prisma.participationsCreateOrConnectWithoutShowsInput | Prisma.participationsCreateOrConnectWithoutShowsInput[]
  upsert?: Prisma.participationsUpsertWithWhereUniqueWithoutShowsInput | Prisma.participationsUpsertWithWhereUniqueWithoutShowsInput[]
  createMany?: Prisma.participationsCreateManyShowsInputEnvelope
  set?: Prisma.participationsWhereUniqueInput | Prisma.participationsWhereUniqueInput[]
  disconnect?: Prisma.participationsWhereUniqueInput | Prisma.participationsWhereUniqueInput[]
  delete?: Prisma.participationsWhereUniqueInput | Prisma.participationsWhereUniqueInput[]
  connect?: Prisma.participationsWhereUniqueInput | Prisma.participationsWhereUniqueInput[]
  update?: Prisma.participationsUpdateWithWhereUniqueWithoutShowsInput | Prisma.participationsUpdateWithWhereUniqueWithoutShowsInput[]
  updateMany?: Prisma.participationsUpdateManyWithWhereWithoutShowsInput | Prisma.participationsUpdateManyWithWhereWithoutShowsInput[]
  deleteMany?: Prisma.participationsScalarWhereInput | Prisma.participationsScalarWhereInput[]
}

export type participationsUncheckedUpdateManyWithoutShowsNestedInput = {
  create?: Prisma.XOR<Prisma.participationsCreateWithoutShowsInput, Prisma.participationsUncheckedCreateWithoutShowsInput> | Prisma.participationsCreateWithoutShowsInput[] | Prisma.participationsUncheckedCreateWithoutShowsInput[]
  connectOrCreate?: Prisma.participationsCreateOrConnectWithoutShowsInput | Prisma.participationsCreateOrConnectWithoutShowsInput[]
  upsert?: Prisma.participationsUpsertWithWhereUniqueWithoutShowsInput | Prisma.participationsUpsertWithWhereUniqueWithoutShowsInput[]
  createMany?: Prisma.participationsCreateManyShowsInputEnvelope
  set?: Prisma.participationsWhereUniqueInput | Prisma.participationsWhereUniqueInput[]
  disconnect?: Prisma.participationsWhereUniqueInput | Prisma.participationsWhereUniqueInput[]
  delete?: Prisma.participationsWhereUniqueInput | Prisma.participationsWhereUniqueInput[]
  connect?: Prisma.participationsWhereUniqueInput | Prisma.participationsWhereUniqueInput[]
  update?: Prisma.participationsUpdateWithWhereUniqueWithoutShowsInput | Prisma.participationsUpdateWithWhereUniqueWithoutShowsInput[]
  updateMany?: Prisma.participationsUpdateManyWithWhereWithoutShowsInput | Prisma.participationsUpdateManyWithWhereWithoutShowsInput[]
  deleteMany?: Prisma.participationsScalarWhereInput | Prisma.participationsScalarWhereInput[]
}

export type participationsCreateWithoutMembersInput = {
  status?: string | null
  points?: number | null
  updated_at?: Date | string | null
  notes?: string | null
  shows?: Prisma.showsCreateNestedOneWithoutParticipationsInput
}

export type participationsUncheckedCreateWithoutMembersInput = {
  id?: number
  show_id?: number | null
  status?: string | null
  points?: number | null
  updated_at?: Date | string | null
  notes?: string | null
}

export type participationsCreateOrConnectWithoutMembersInput = {
  where: Prisma.participationsWhereUniqueInput
  create: Prisma.XOR<Prisma.participationsCreateWithoutMembersInput, Prisma.participationsUncheckedCreateWithoutMembersInput>
}

export type participationsCreateManyMembersInputEnvelope = {
  data: Prisma.participationsCreateManyMembersInput | Prisma.participationsCreateManyMembersInput[]
  skipDuplicates?: boolean
}

export type participationsUpsertWithWhereUniqueWithoutMembersInput = {
  where: Prisma.participationsWhereUniqueInput
  update: Prisma.XOR<Prisma.participationsUpdateWithoutMembersInput, Prisma.participationsUncheckedUpdateWithoutMembersInput>
  create: Prisma.XOR<Prisma.participationsCreateWithoutMembersInput, Prisma.participationsUncheckedCreateWithoutMembersInput>
}

export type participationsUpdateWithWhereUniqueWithoutMembersInput = {
  where: Prisma.participationsWhereUniqueInput
  data: Prisma.XOR<Prisma.participationsUpdateWithoutMembersInput, Prisma.participationsUncheckedUpdateWithoutMembersInput>
}

export type participationsUpdateManyWithWhereWithoutMembersInput = {
  where: Prisma.participationsScalarWhereInput
  data: Prisma.XOR<Prisma.participationsUpdateManyMutationInput, Prisma.participationsUncheckedUpdateManyWithoutMembersInput>
}

export type participationsScalarWhereInput = {
  AND?: Prisma.participationsScalarWhereInput | Prisma.participationsScalarWhereInput[]
  OR?: Prisma.participationsScalarWhereInput[]
  NOT?: Prisma.participationsScalarWhereInput | Prisma.participationsScalarWhereInput[]
  id?: Prisma.IntFilter<"participations"> | number
  member_id?: Prisma.IntNullableFilter<"participations"> | number | null
  show_id?: Prisma.IntNullableFilter<"participations"> | number | null
  status?: Prisma.StringNullableFilter<"participations"> | string | null
  points?: Prisma.IntNullableFilter<"participations"> | number | null
  updated_at?: Prisma.DateTimeNullableFilter<"participations"> | Date | string | null
  notes?: Prisma.StringNullableFilter<"participations"> | string | null
}

export type participationsCreateWithoutShowsInput = {
  status?: string | null
  points?: number | null
  updated_at?: Date | string | null
  notes?: string | null
  members?: Prisma.membersCreateNestedOneWithoutParticipationsInput
}

export type participationsUncheckedCreateWithoutShowsInput = {
  id?: number
  member_id?: number | null
  status?: string | null
  points?: number | null
  updated_at?: Date | string | null
  notes?: string | null
}

export type participationsCreateOrConnectWithoutShowsInput = {
  where: Prisma.participationsWhereUniqueInput
  create: Prisma.XOR<Prisma.participationsCreateWithoutShowsInput, Prisma.participationsUncheckedCreateWithoutShowsInput>
}

export type participationsCreateManyShowsInputEnvelope = {
  data: Prisma.participationsCreateManyShowsInput | Prisma.participationsCreateManyShowsInput[]
  skipDuplicates?: boolean
}

export type participationsUpsertWithWhereUniqueWithoutShowsInput = {
  where: Prisma.participationsWhereUniqueInput
  update: Prisma.XOR<Prisma.participationsUpdateWithoutShowsInput, Prisma.participationsUncheckedUpdateWithoutShowsInput>
  create: Prisma.XOR<Prisma.participationsCreateWithoutShowsInput, Prisma.participationsUncheckedCreateWithoutShowsInput>
}

export type participationsUpdateWithWhereUniqueWithoutShowsInput = {
  where: Prisma.participationsWhereUniqueInput
  data: Prisma.XOR<Prisma.participationsUpdateWithoutShowsInput, Prisma.participationsUncheckedUpdateWithoutShowsInput>
}

export type participationsUpdateManyWithWhereWithoutShowsInput = {
  where: Prisma.participationsScalarWhereInput
  data: Prisma.XOR<Prisma.participationsUpdateManyMutationInput, Prisma.participationsUncheckedUpdateManyWithoutShowsInput>
}

export type participationsCreateManyMembersInput = {
  id?: number
  show_id?: number | null
  status?: string | null
  points?: number | null
  updated_at?: Date | string | null
  notes?: string | null
}

export type participationsUpdateWithoutMembersInput = {
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  points?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  shows?: Prisma.showsUpdateOneWithoutParticipationsNestedInput
}

export type participationsUncheckedUpdateWithoutMembersInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  show_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  points?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type participationsUncheckedUpdateManyWithoutMembersInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  show_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  points?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type participationsCreateManyShowsInput = {
  id?: number
  member_id?: number | null
  status?: string | null
  points?: number | null
  updated_at?: Date | string | null
  notes?: string | null
}

export type participationsUpdateWithoutShowsInput = {
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  points?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  members?: Prisma.membersUpdateOneWithoutParticipationsNestedInput
}

export type participationsUncheckedUpdateWithoutShowsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  member_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  points?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type participationsUncheckedUpdateManyWithoutShowsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  member_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  status?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  points?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  updated_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  notes?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type participationsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  member_id?: boolean
  show_id?: boolean
  status?: boolean
  points?: boolean
  updated_at?: boolean
  notes?: boolean
  members?: boolean | Prisma.participations$membersArgs<ExtArgs>
  shows?: boolean | Prisma.participations$showsArgs<ExtArgs>
}, ExtArgs["result"]["participations"]>

export type participationsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  member_id?: boolean
  show_id?: boolean
  status?: boolean
  points?: boolean
  updated_at?: boolean
  notes?: boolean
  members?: boolean | Prisma.participations$membersArgs<ExtArgs>
  shows?: boolean | Prisma.participations$showsArgs<ExtArgs>
}, ExtArgs["result"]["participations"]>

export type participationsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  member_id?: boolean
  show_id?: boolean
  status?: boolean
  points?: boolean
  updated_at?: boolean
  notes?: boolean
  members?: boolean | Prisma.participations$membersArgs<ExtArgs>
  shows?: boolean | Prisma.participations$showsArgs<ExtArgs>
}, ExtArgs["result"]["participations"]>

export type participationsSelectScalar = {
  id?: boolean
  member_id?: boolean
  show_id?: boolean
  status?: boolean
  points?: boolean
  updated_at?: boolean
  notes?: boolean
}

export type participationsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "member_id" | "show_id" | "status" | "points" | "updated_at" | "notes", ExtArgs["result"]["participations"]>
export type participationsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  members?: boolean | Prisma.participations$membersArgs<ExtArgs>
  shows?: boolean | Prisma.participations$showsArgs<ExtArgs>
}
export type participationsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  members?: boolean | Prisma.participations$membersArgs<ExtArgs>
  shows?: boolean | Prisma.participations$showsArgs<ExtArgs>
}
export type participationsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  members?: boolean | Prisma.participations$membersArgs<ExtArgs>
  shows?: boolean | Prisma.participations$showsArgs<ExtArgs>
}

export type $participationsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "participations"
  objects: {
    members: Prisma.$membersPayload<ExtArgs> | null
    shows: Prisma.$showsPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    member_id: number | null
    show_id: number | null
    status: string | null
    points: number | null
    updated_at: Date | null
    notes: string | null
  }, ExtArgs["result"]["participations"]>
  composites: {}
}

export type participationsGetPayload<S extends boolean | null | undefined | participationsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$participationsPayload, S>

export type participationsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<participationsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ParticipationsCountAggregateInputType | true
  }

export interface participationsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['participations'], meta: { name: 'participations' } }
  /**
   * Find zero or one Participations that matches the filter.
   * @param {participationsFindUniqueArgs} args - Arguments to find a Participations
   * @example
   * // Get one Participations
   * const participations = await prisma.participations.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends participationsFindUniqueArgs>(args: Prisma.SelectSubset<T, participationsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__participationsClient<runtime.Types.Result.GetResult<Prisma.$participationsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Participations that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {participationsFindUniqueOrThrowArgs} args - Arguments to find a Participations
   * @example
   * // Get one Participations
   * const participations = await prisma.participations.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends participationsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, participationsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__participationsClient<runtime.Types.Result.GetResult<Prisma.$participationsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Participations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {participationsFindFirstArgs} args - Arguments to find a Participations
   * @example
   * // Get one Participations
   * const participations = await prisma.participations.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends participationsFindFirstArgs>(args?: Prisma.SelectSubset<T, participationsFindFirstArgs<ExtArgs>>): Prisma.Prisma__participationsClient<runtime.Types.Result.GetResult<Prisma.$participationsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Participations that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {participationsFindFirstOrThrowArgs} args - Arguments to find a Participations
   * @example
   * // Get one Participations
   * const participations = await prisma.participations.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends participationsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, participationsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__participationsClient<runtime.Types.Result.GetResult<Prisma.$participationsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Participations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {participationsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Participations
   * const participations = await prisma.participations.findMany()
   * 
   * // Get first 10 Participations
   * const participations = await prisma.participations.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const participationsWithIdOnly = await prisma.participations.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends participationsFindManyArgs>(args?: Prisma.SelectSubset<T, participationsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$participationsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Participations.
   * @param {participationsCreateArgs} args - Arguments to create a Participations.
   * @example
   * // Create one Participations
   * const Participations = await prisma.participations.create({
   *   data: {
   *     // ... data to create a Participations
   *   }
   * })
   * 
   */
  create<T extends participationsCreateArgs>(args: Prisma.SelectSubset<T, participationsCreateArgs<ExtArgs>>): Prisma.Prisma__participationsClient<runtime.Types.Result.GetResult<Prisma.$participationsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Participations.
   * @param {participationsCreateManyArgs} args - Arguments to create many Participations.
   * @example
   * // Create many Participations
   * const participations = await prisma.participations.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends participationsCreateManyArgs>(args?: Prisma.SelectSubset<T, participationsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Participations and returns the data saved in the database.
   * @param {participationsCreateManyAndReturnArgs} args - Arguments to create many Participations.
   * @example
   * // Create many Participations
   * const participations = await prisma.participations.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Participations and only return the `id`
   * const participationsWithIdOnly = await prisma.participations.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends participationsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, participationsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$participationsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Participations.
   * @param {participationsDeleteArgs} args - Arguments to delete one Participations.
   * @example
   * // Delete one Participations
   * const Participations = await prisma.participations.delete({
   *   where: {
   *     // ... filter to delete one Participations
   *   }
   * })
   * 
   */
  delete<T extends participationsDeleteArgs>(args: Prisma.SelectSubset<T, participationsDeleteArgs<ExtArgs>>): Prisma.Prisma__participationsClient<runtime.Types.Result.GetResult<Prisma.$participationsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Participations.
   * @param {participationsUpdateArgs} args - Arguments to update one Participations.
   * @example
   * // Update one Participations
   * const participations = await prisma.participations.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends participationsUpdateArgs>(args: Prisma.SelectSubset<T, participationsUpdateArgs<ExtArgs>>): Prisma.Prisma__participationsClient<runtime.Types.Result.GetResult<Prisma.$participationsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Participations.
   * @param {participationsDeleteManyArgs} args - Arguments to filter Participations to delete.
   * @example
   * // Delete a few Participations
   * const { count } = await prisma.participations.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends participationsDeleteManyArgs>(args?: Prisma.SelectSubset<T, participationsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Participations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {participationsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Participations
   * const participations = await prisma.participations.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends participationsUpdateManyArgs>(args: Prisma.SelectSubset<T, participationsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Participations and returns the data updated in the database.
   * @param {participationsUpdateManyAndReturnArgs} args - Arguments to update many Participations.
   * @example
   * // Update many Participations
   * const participations = await prisma.participations.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Participations and only return the `id`
   * const participationsWithIdOnly = await prisma.participations.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends participationsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, participationsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$participationsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Participations.
   * @param {participationsUpsertArgs} args - Arguments to update or create a Participations.
   * @example
   * // Update or create a Participations
   * const participations = await prisma.participations.upsert({
   *   create: {
   *     // ... data to create a Participations
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Participations we want to update
   *   }
   * })
   */
  upsert<T extends participationsUpsertArgs>(args: Prisma.SelectSubset<T, participationsUpsertArgs<ExtArgs>>): Prisma.Prisma__participationsClient<runtime.Types.Result.GetResult<Prisma.$participationsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Participations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {participationsCountArgs} args - Arguments to filter Participations to count.
   * @example
   * // Count the number of Participations
   * const count = await prisma.participations.count({
   *   where: {
   *     // ... the filter for the Participations we want to count
   *   }
   * })
  **/
  count<T extends participationsCountArgs>(
    args?: Prisma.Subset<T, participationsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ParticipationsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Participations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParticipationsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ParticipationsAggregateArgs>(args: Prisma.Subset<T, ParticipationsAggregateArgs>): Prisma.PrismaPromise<GetParticipationsAggregateType<T>>

  /**
   * Group by Participations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {participationsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends participationsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: participationsGroupByArgs['orderBy'] }
      : { orderBy?: participationsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, participationsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetParticipationsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the participations model
 */
readonly fields: participationsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for participations.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__participationsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  members<T extends Prisma.participations$membersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.participations$membersArgs<ExtArgs>>): Prisma.Prisma__membersClient<runtime.Types.Result.GetResult<Prisma.$membersPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  shows<T extends Prisma.participations$showsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.participations$showsArgs<ExtArgs>>): Prisma.Prisma__showsClient<runtime.Types.Result.GetResult<Prisma.$showsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the participations model
 */
export interface participationsFieldRefs {
  readonly id: Prisma.FieldRef<"participations", 'Int'>
  readonly member_id: Prisma.FieldRef<"participations", 'Int'>
  readonly show_id: Prisma.FieldRef<"participations", 'Int'>
  readonly status: Prisma.FieldRef<"participations", 'String'>
  readonly points: Prisma.FieldRef<"participations", 'Int'>
  readonly updated_at: Prisma.FieldRef<"participations", 'DateTime'>
  readonly notes: Prisma.FieldRef<"participations", 'String'>
}
    

// Custom InputTypes
/**
 * participations findUnique
 */
export type participationsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the participations
   */
  select?: Prisma.participationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the participations
   */
  omit?: Prisma.participationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.participationsInclude<ExtArgs> | null
  /**
   * Filter, which participations to fetch.
   */
  where: Prisma.participationsWhereUniqueInput
}

/**
 * participations findUniqueOrThrow
 */
export type participationsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the participations
   */
  select?: Prisma.participationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the participations
   */
  omit?: Prisma.participationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.participationsInclude<ExtArgs> | null
  /**
   * Filter, which participations to fetch.
   */
  where: Prisma.participationsWhereUniqueInput
}

/**
 * participations findFirst
 */
export type participationsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the participations
   */
  select?: Prisma.participationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the participations
   */
  omit?: Prisma.participationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.participationsInclude<ExtArgs> | null
  /**
   * Filter, which participations to fetch.
   */
  where?: Prisma.participationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of participations to fetch.
   */
  orderBy?: Prisma.participationsOrderByWithRelationInput | Prisma.participationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for participations.
   */
  cursor?: Prisma.participationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` participations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` participations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of participations.
   */
  distinct?: Prisma.ParticipationsScalarFieldEnum | Prisma.ParticipationsScalarFieldEnum[]
}

/**
 * participations findFirstOrThrow
 */
export type participationsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the participations
   */
  select?: Prisma.participationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the participations
   */
  omit?: Prisma.participationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.participationsInclude<ExtArgs> | null
  /**
   * Filter, which participations to fetch.
   */
  where?: Prisma.participationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of participations to fetch.
   */
  orderBy?: Prisma.participationsOrderByWithRelationInput | Prisma.participationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for participations.
   */
  cursor?: Prisma.participationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` participations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` participations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of participations.
   */
  distinct?: Prisma.ParticipationsScalarFieldEnum | Prisma.ParticipationsScalarFieldEnum[]
}

/**
 * participations findMany
 */
export type participationsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the participations
   */
  select?: Prisma.participationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the participations
   */
  omit?: Prisma.participationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.participationsInclude<ExtArgs> | null
  /**
   * Filter, which participations to fetch.
   */
  where?: Prisma.participationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of participations to fetch.
   */
  orderBy?: Prisma.participationsOrderByWithRelationInput | Prisma.participationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing participations.
   */
  cursor?: Prisma.participationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` participations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` participations.
   */
  skip?: number
  distinct?: Prisma.ParticipationsScalarFieldEnum | Prisma.ParticipationsScalarFieldEnum[]
}

/**
 * participations create
 */
export type participationsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the participations
   */
  select?: Prisma.participationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the participations
   */
  omit?: Prisma.participationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.participationsInclude<ExtArgs> | null
  /**
   * The data needed to create a participations.
   */
  data?: Prisma.XOR<Prisma.participationsCreateInput, Prisma.participationsUncheckedCreateInput>
}

/**
 * participations createMany
 */
export type participationsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many participations.
   */
  data: Prisma.participationsCreateManyInput | Prisma.participationsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * participations createManyAndReturn
 */
export type participationsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the participations
   */
  select?: Prisma.participationsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the participations
   */
  omit?: Prisma.participationsOmit<ExtArgs> | null
  /**
   * The data used to create many participations.
   */
  data: Prisma.participationsCreateManyInput | Prisma.participationsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.participationsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * participations update
 */
export type participationsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the participations
   */
  select?: Prisma.participationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the participations
   */
  omit?: Prisma.participationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.participationsInclude<ExtArgs> | null
  /**
   * The data needed to update a participations.
   */
  data: Prisma.XOR<Prisma.participationsUpdateInput, Prisma.participationsUncheckedUpdateInput>
  /**
   * Choose, which participations to update.
   */
  where: Prisma.participationsWhereUniqueInput
}

/**
 * participations updateMany
 */
export type participationsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update participations.
   */
  data: Prisma.XOR<Prisma.participationsUpdateManyMutationInput, Prisma.participationsUncheckedUpdateManyInput>
  /**
   * Filter which participations to update
   */
  where?: Prisma.participationsWhereInput
  /**
   * Limit how many participations to update.
   */
  limit?: number
}

/**
 * participations updateManyAndReturn
 */
export type participationsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the participations
   */
  select?: Prisma.participationsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the participations
   */
  omit?: Prisma.participationsOmit<ExtArgs> | null
  /**
   * The data used to update participations.
   */
  data: Prisma.XOR<Prisma.participationsUpdateManyMutationInput, Prisma.participationsUncheckedUpdateManyInput>
  /**
   * Filter which participations to update
   */
  where?: Prisma.participationsWhereInput
  /**
   * Limit how many participations to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.participationsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * participations upsert
 */
export type participationsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the participations
   */
  select?: Prisma.participationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the participations
   */
  omit?: Prisma.participationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.participationsInclude<ExtArgs> | null
  /**
   * The filter to search for the participations to update in case it exists.
   */
  where: Prisma.participationsWhereUniqueInput
  /**
   * In case the participations found by the `where` argument doesn't exist, create a new participations with this data.
   */
  create: Prisma.XOR<Prisma.participationsCreateInput, Prisma.participationsUncheckedCreateInput>
  /**
   * In case the participations was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.participationsUpdateInput, Prisma.participationsUncheckedUpdateInput>
}

/**
 * participations delete
 */
export type participationsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the participations
   */
  select?: Prisma.participationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the participations
   */
  omit?: Prisma.participationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.participationsInclude<ExtArgs> | null
  /**
   * Filter which participations to delete.
   */
  where: Prisma.participationsWhereUniqueInput
}

/**
 * participations deleteMany
 */
export type participationsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which participations to delete
   */
  where?: Prisma.participationsWhereInput
  /**
   * Limit how many participations to delete.
   */
  limit?: number
}

/**
 * participations.members
 */
export type participations$membersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the members
   */
  select?: Prisma.membersSelect<ExtArgs> | null
  /**
   * Omit specific fields from the members
   */
  omit?: Prisma.membersOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.membersInclude<ExtArgs> | null
  where?: Prisma.membersWhereInput
}

/**
 * participations.shows
 */
export type participations$showsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the shows
   */
  select?: Prisma.showsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the shows
   */
  omit?: Prisma.showsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.showsInclude<ExtArgs> | null
  where?: Prisma.showsWhereInput
}

/**
 * participations without action
 */
export type participationsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the participations
   */
  select?: Prisma.participationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the participations
   */
  omit?: Prisma.participationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.participationsInclude<ExtArgs> | null
}
