
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `shows` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model shows
 * This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info.
 * This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info.
 */
export type showsModel = runtime.Types.Result.DefaultSelection<Prisma.$showsPayload>

export type AggregateShows = {
  _count: ShowsCountAggregateOutputType | null
  _avg: ShowsAvgAggregateOutputType | null
  _sum: ShowsSumAggregateOutputType | null
  _min: ShowsMinAggregateOutputType | null
  _max: ShowsMaxAggregateOutputType | null
}

export type ShowsAvgAggregateOutputType = {
  id: number | null
  rally_id: number | null
  show_number: number | null
}

export type ShowsSumAggregateOutputType = {
  id: number | null
  rally_id: number | null
  show_number: number | null
}

export type ShowsMinAggregateOutputType = {
  id: number | null
  rally_id: number | null
  show_number: number | null
  name: string | null
  details: string | null
  created_at: Date | null
}

export type ShowsMaxAggregateOutputType = {
  id: number | null
  rally_id: number | null
  show_number: number | null
  name: string | null
  details: string | null
  created_at: Date | null
}

export type ShowsCountAggregateOutputType = {
  id: number
  rally_id: number
  show_number: number
  name: number
  details: number
  created_at: number
  _all: number
}


export type ShowsAvgAggregateInputType = {
  id?: true
  rally_id?: true
  show_number?: true
}

export type ShowsSumAggregateInputType = {
  id?: true
  rally_id?: true
  show_number?: true
}

export type ShowsMinAggregateInputType = {
  id?: true
  rally_id?: true
  show_number?: true
  name?: true
  details?: true
  created_at?: true
}

export type ShowsMaxAggregateInputType = {
  id?: true
  rally_id?: true
  show_number?: true
  name?: true
  details?: true
  created_at?: true
}

export type ShowsCountAggregateInputType = {
  id?: true
  rally_id?: true
  show_number?: true
  name?: true
  details?: true
  created_at?: true
  _all?: true
}

export type ShowsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which shows to aggregate.
   */
  where?: Prisma.showsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of shows to fetch.
   */
  orderBy?: Prisma.showsOrderByWithRelationInput | Prisma.showsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.showsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` shows from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` shows.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned shows
  **/
  _count?: true | ShowsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ShowsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ShowsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ShowsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ShowsMaxAggregateInputType
}

export type GetShowsAggregateType<T extends ShowsAggregateArgs> = {
      [P in keyof T & keyof AggregateShows]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateShows[P]>
    : Prisma.GetScalarType<T[P], AggregateShows[P]>
}




export type showsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.showsWhereInput
  orderBy?: Prisma.showsOrderByWithAggregationInput | Prisma.showsOrderByWithAggregationInput[]
  by: Prisma.ShowsScalarFieldEnum[] | Prisma.ShowsScalarFieldEnum
  having?: Prisma.showsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ShowsCountAggregateInputType | true
  _avg?: ShowsAvgAggregateInputType
  _sum?: ShowsSumAggregateInputType
  _min?: ShowsMinAggregateInputType
  _max?: ShowsMaxAggregateInputType
}

export type ShowsGroupByOutputType = {
  id: number
  rally_id: number | null
  show_number: number
  name: string
  details: string | null
  created_at: Date | null
  _count: ShowsCountAggregateOutputType | null
  _avg: ShowsAvgAggregateOutputType | null
  _sum: ShowsSumAggregateOutputType | null
  _min: ShowsMinAggregateOutputType | null
  _max: ShowsMaxAggregateOutputType | null
}

type GetShowsGroupByPayload<T extends showsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ShowsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ShowsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ShowsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ShowsGroupByOutputType[P]>
      }
    >
  >



export type showsWhereInput = {
  AND?: Prisma.showsWhereInput | Prisma.showsWhereInput[]
  OR?: Prisma.showsWhereInput[]
  NOT?: Prisma.showsWhereInput | Prisma.showsWhereInput[]
  id?: Prisma.IntFilter<"shows"> | number
  rally_id?: Prisma.IntNullableFilter<"shows"> | number | null
  show_number?: Prisma.IntFilter<"shows"> | number
  name?: Prisma.StringFilter<"shows"> | string
  details?: Prisma.StringNullableFilter<"shows"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"shows"> | Date | string | null
  participations?: Prisma.ParticipationsListRelationFilter
  rallies?: Prisma.XOR<Prisma.RalliesNullableScalarRelationFilter, Prisma.ralliesWhereInput> | null
}

export type showsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  rally_id?: Prisma.SortOrderInput | Prisma.SortOrder
  show_number?: Prisma.SortOrder
  name?: Prisma.SortOrder
  details?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  participations?: Prisma.participationsOrderByRelationAggregateInput
  rallies?: Prisma.ralliesOrderByWithRelationInput
}

export type showsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.showsWhereInput | Prisma.showsWhereInput[]
  OR?: Prisma.showsWhereInput[]
  NOT?: Prisma.showsWhereInput | Prisma.showsWhereInput[]
  rally_id?: Prisma.IntNullableFilter<"shows"> | number | null
  show_number?: Prisma.IntFilter<"shows"> | number
  name?: Prisma.StringFilter<"shows"> | string
  details?: Prisma.StringNullableFilter<"shows"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"shows"> | Date | string | null
  participations?: Prisma.ParticipationsListRelationFilter
  rallies?: Prisma.XOR<Prisma.RalliesNullableScalarRelationFilter, Prisma.ralliesWhereInput> | null
}, "id">

export type showsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  rally_id?: Prisma.SortOrderInput | Prisma.SortOrder
  show_number?: Prisma.SortOrder
  name?: Prisma.SortOrder
  details?: Prisma.SortOrderInput | Prisma.SortOrder
  created_at?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.showsCountOrderByAggregateInput
  _avg?: Prisma.showsAvgOrderByAggregateInput
  _max?: Prisma.showsMaxOrderByAggregateInput
  _min?: Prisma.showsMinOrderByAggregateInput
  _sum?: Prisma.showsSumOrderByAggregateInput
}

export type showsScalarWhereWithAggregatesInput = {
  AND?: Prisma.showsScalarWhereWithAggregatesInput | Prisma.showsScalarWhereWithAggregatesInput[]
  OR?: Prisma.showsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.showsScalarWhereWithAggregatesInput | Prisma.showsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"shows"> | number
  rally_id?: Prisma.IntNullableWithAggregatesFilter<"shows"> | number | null
  show_number?: Prisma.IntWithAggregatesFilter<"shows"> | number
  name?: Prisma.StringWithAggregatesFilter<"shows"> | string
  details?: Prisma.StringNullableWithAggregatesFilter<"shows"> | string | null
  created_at?: Prisma.DateTimeNullableWithAggregatesFilter<"shows"> | Date | string | null
}

export type showsCreateInput = {
  show_number: number
  name: string
  details?: string | null
  created_at?: Date | string | null
  participations?: Prisma.participationsCreateNestedManyWithoutShowsInput
  rallies?: Prisma.ralliesCreateNestedOneWithoutShowsInput
}

export type showsUncheckedCreateInput = {
  id?: number
  rally_id?: number | null
  show_number: number
  name: string
  details?: string | null
  created_at?: Date | string | null
  participations?: Prisma.participationsUncheckedCreateNestedManyWithoutShowsInput
}

export type showsUpdateInput = {
  show_number?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  participations?: Prisma.participationsUpdateManyWithoutShowsNestedInput
  rallies?: Prisma.ralliesUpdateOneWithoutShowsNestedInput
}

export type showsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  rally_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  show_number?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  participations?: Prisma.participationsUncheckedUpdateManyWithoutShowsNestedInput
}

export type showsCreateManyInput = {
  id?: number
  rally_id?: number | null
  show_number: number
  name: string
  details?: string | null
  created_at?: Date | string | null
}

export type showsUpdateManyMutationInput = {
  show_number?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type showsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  rally_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  show_number?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ShowsNullableScalarRelationFilter = {
  is?: Prisma.showsWhereInput | null
  isNot?: Prisma.showsWhereInput | null
}

export type ShowsListRelationFilter = {
  every?: Prisma.showsWhereInput
  some?: Prisma.showsWhereInput
  none?: Prisma.showsWhereInput
}

export type showsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type showsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  rally_id?: Prisma.SortOrder
  show_number?: Prisma.SortOrder
  name?: Prisma.SortOrder
  details?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type showsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  rally_id?: Prisma.SortOrder
  show_number?: Prisma.SortOrder
}

export type showsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  rally_id?: Prisma.SortOrder
  show_number?: Prisma.SortOrder
  name?: Prisma.SortOrder
  details?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type showsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  rally_id?: Prisma.SortOrder
  show_number?: Prisma.SortOrder
  name?: Prisma.SortOrder
  details?: Prisma.SortOrder
  created_at?: Prisma.SortOrder
}

export type showsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  rally_id?: Prisma.SortOrder
  show_number?: Prisma.SortOrder
}

export type showsCreateNestedOneWithoutParticipationsInput = {
  create?: Prisma.XOR<Prisma.showsCreateWithoutParticipationsInput, Prisma.showsUncheckedCreateWithoutParticipationsInput>
  connectOrCreate?: Prisma.showsCreateOrConnectWithoutParticipationsInput
  connect?: Prisma.showsWhereUniqueInput
}

export type showsUpdateOneWithoutParticipationsNestedInput = {
  create?: Prisma.XOR<Prisma.showsCreateWithoutParticipationsInput, Prisma.showsUncheckedCreateWithoutParticipationsInput>
  connectOrCreate?: Prisma.showsCreateOrConnectWithoutParticipationsInput
  upsert?: Prisma.showsUpsertWithoutParticipationsInput
  disconnect?: Prisma.showsWhereInput | boolean
  delete?: Prisma.showsWhereInput | boolean
  connect?: Prisma.showsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.showsUpdateToOneWithWhereWithoutParticipationsInput, Prisma.showsUpdateWithoutParticipationsInput>, Prisma.showsUncheckedUpdateWithoutParticipationsInput>
}

export type showsCreateNestedManyWithoutRalliesInput = {
  create?: Prisma.XOR<Prisma.showsCreateWithoutRalliesInput, Prisma.showsUncheckedCreateWithoutRalliesInput> | Prisma.showsCreateWithoutRalliesInput[] | Prisma.showsUncheckedCreateWithoutRalliesInput[]
  connectOrCreate?: Prisma.showsCreateOrConnectWithoutRalliesInput | Prisma.showsCreateOrConnectWithoutRalliesInput[]
  createMany?: Prisma.showsCreateManyRalliesInputEnvelope
  connect?: Prisma.showsWhereUniqueInput | Prisma.showsWhereUniqueInput[]
}

export type showsUncheckedCreateNestedManyWithoutRalliesInput = {
  create?: Prisma.XOR<Prisma.showsCreateWithoutRalliesInput, Prisma.showsUncheckedCreateWithoutRalliesInput> | Prisma.showsCreateWithoutRalliesInput[] | Prisma.showsUncheckedCreateWithoutRalliesInput[]
  connectOrCreate?: Prisma.showsCreateOrConnectWithoutRalliesInput | Prisma.showsCreateOrConnectWithoutRalliesInput[]
  createMany?: Prisma.showsCreateManyRalliesInputEnvelope
  connect?: Prisma.showsWhereUniqueInput | Prisma.showsWhereUniqueInput[]
}

export type showsUpdateManyWithoutRalliesNestedInput = {
  create?: Prisma.XOR<Prisma.showsCreateWithoutRalliesInput, Prisma.showsUncheckedCreateWithoutRalliesInput> | Prisma.showsCreateWithoutRalliesInput[] | Prisma.showsUncheckedCreateWithoutRalliesInput[]
  connectOrCreate?: Prisma.showsCreateOrConnectWithoutRalliesInput | Prisma.showsCreateOrConnectWithoutRalliesInput[]
  upsert?: Prisma.showsUpsertWithWhereUniqueWithoutRalliesInput | Prisma.showsUpsertWithWhereUniqueWithoutRalliesInput[]
  createMany?: Prisma.showsCreateManyRalliesInputEnvelope
  set?: Prisma.showsWhereUniqueInput | Prisma.showsWhereUniqueInput[]
  disconnect?: Prisma.showsWhereUniqueInput | Prisma.showsWhereUniqueInput[]
  delete?: Prisma.showsWhereUniqueInput | Prisma.showsWhereUniqueInput[]
  connect?: Prisma.showsWhereUniqueInput | Prisma.showsWhereUniqueInput[]
  update?: Prisma.showsUpdateWithWhereUniqueWithoutRalliesInput | Prisma.showsUpdateWithWhereUniqueWithoutRalliesInput[]
  updateMany?: Prisma.showsUpdateManyWithWhereWithoutRalliesInput | Prisma.showsUpdateManyWithWhereWithoutRalliesInput[]
  deleteMany?: Prisma.showsScalarWhereInput | Prisma.showsScalarWhereInput[]
}

export type showsUncheckedUpdateManyWithoutRalliesNestedInput = {
  create?: Prisma.XOR<Prisma.showsCreateWithoutRalliesInput, Prisma.showsUncheckedCreateWithoutRalliesInput> | Prisma.showsCreateWithoutRalliesInput[] | Prisma.showsUncheckedCreateWithoutRalliesInput[]
  connectOrCreate?: Prisma.showsCreateOrConnectWithoutRalliesInput | Prisma.showsCreateOrConnectWithoutRalliesInput[]
  upsert?: Prisma.showsUpsertWithWhereUniqueWithoutRalliesInput | Prisma.showsUpsertWithWhereUniqueWithoutRalliesInput[]
  createMany?: Prisma.showsCreateManyRalliesInputEnvelope
  set?: Prisma.showsWhereUniqueInput | Prisma.showsWhereUniqueInput[]
  disconnect?: Prisma.showsWhereUniqueInput | Prisma.showsWhereUniqueInput[]
  delete?: Prisma.showsWhereUniqueInput | Prisma.showsWhereUniqueInput[]
  connect?: Prisma.showsWhereUniqueInput | Prisma.showsWhereUniqueInput[]
  update?: Prisma.showsUpdateWithWhereUniqueWithoutRalliesInput | Prisma.showsUpdateWithWhereUniqueWithoutRalliesInput[]
  updateMany?: Prisma.showsUpdateManyWithWhereWithoutRalliesInput | Prisma.showsUpdateManyWithWhereWithoutRalliesInput[]
  deleteMany?: Prisma.showsScalarWhereInput | Prisma.showsScalarWhereInput[]
}

export type showsCreateWithoutParticipationsInput = {
  show_number: number
  name: string
  details?: string | null
  created_at?: Date | string | null
  rallies?: Prisma.ralliesCreateNestedOneWithoutShowsInput
}

export type showsUncheckedCreateWithoutParticipationsInput = {
  id?: number
  rally_id?: number | null
  show_number: number
  name: string
  details?: string | null
  created_at?: Date | string | null
}

export type showsCreateOrConnectWithoutParticipationsInput = {
  where: Prisma.showsWhereUniqueInput
  create: Prisma.XOR<Prisma.showsCreateWithoutParticipationsInput, Prisma.showsUncheckedCreateWithoutParticipationsInput>
}

export type showsUpsertWithoutParticipationsInput = {
  update: Prisma.XOR<Prisma.showsUpdateWithoutParticipationsInput, Prisma.showsUncheckedUpdateWithoutParticipationsInput>
  create: Prisma.XOR<Prisma.showsCreateWithoutParticipationsInput, Prisma.showsUncheckedCreateWithoutParticipationsInput>
  where?: Prisma.showsWhereInput
}

export type showsUpdateToOneWithWhereWithoutParticipationsInput = {
  where?: Prisma.showsWhereInput
  data: Prisma.XOR<Prisma.showsUpdateWithoutParticipationsInput, Prisma.showsUncheckedUpdateWithoutParticipationsInput>
}

export type showsUpdateWithoutParticipationsInput = {
  show_number?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rallies?: Prisma.ralliesUpdateOneWithoutShowsNestedInput
}

export type showsUncheckedUpdateWithoutParticipationsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  rally_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  show_number?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type showsCreateWithoutRalliesInput = {
  show_number: number
  name: string
  details?: string | null
  created_at?: Date | string | null
  participations?: Prisma.participationsCreateNestedManyWithoutShowsInput
}

export type showsUncheckedCreateWithoutRalliesInput = {
  id?: number
  show_number: number
  name: string
  details?: string | null
  created_at?: Date | string | null
  participations?: Prisma.participationsUncheckedCreateNestedManyWithoutShowsInput
}

export type showsCreateOrConnectWithoutRalliesInput = {
  where: Prisma.showsWhereUniqueInput
  create: Prisma.XOR<Prisma.showsCreateWithoutRalliesInput, Prisma.showsUncheckedCreateWithoutRalliesInput>
}

export type showsCreateManyRalliesInputEnvelope = {
  data: Prisma.showsCreateManyRalliesInput | Prisma.showsCreateManyRalliesInput[]
  skipDuplicates?: boolean
}

export type showsUpsertWithWhereUniqueWithoutRalliesInput = {
  where: Prisma.showsWhereUniqueInput
  update: Prisma.XOR<Prisma.showsUpdateWithoutRalliesInput, Prisma.showsUncheckedUpdateWithoutRalliesInput>
  create: Prisma.XOR<Prisma.showsCreateWithoutRalliesInput, Prisma.showsUncheckedCreateWithoutRalliesInput>
}

export type showsUpdateWithWhereUniqueWithoutRalliesInput = {
  where: Prisma.showsWhereUniqueInput
  data: Prisma.XOR<Prisma.showsUpdateWithoutRalliesInput, Prisma.showsUncheckedUpdateWithoutRalliesInput>
}

export type showsUpdateManyWithWhereWithoutRalliesInput = {
  where: Prisma.showsScalarWhereInput
  data: Prisma.XOR<Prisma.showsUpdateManyMutationInput, Prisma.showsUncheckedUpdateManyWithoutRalliesInput>
}

export type showsScalarWhereInput = {
  AND?: Prisma.showsScalarWhereInput | Prisma.showsScalarWhereInput[]
  OR?: Prisma.showsScalarWhereInput[]
  NOT?: Prisma.showsScalarWhereInput | Prisma.showsScalarWhereInput[]
  id?: Prisma.IntFilter<"shows"> | number
  rally_id?: Prisma.IntNullableFilter<"shows"> | number | null
  show_number?: Prisma.IntFilter<"shows"> | number
  name?: Prisma.StringFilter<"shows"> | string
  details?: Prisma.StringNullableFilter<"shows"> | string | null
  created_at?: Prisma.DateTimeNullableFilter<"shows"> | Date | string | null
}

export type showsCreateManyRalliesInput = {
  id?: number
  show_number: number
  name: string
  details?: string | null
  created_at?: Date | string | null
}

export type showsUpdateWithoutRalliesInput = {
  show_number?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  participations?: Prisma.participationsUpdateManyWithoutShowsNestedInput
}

export type showsUncheckedUpdateWithoutRalliesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  show_number?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  participations?: Prisma.participationsUncheckedUpdateManyWithoutShowsNestedInput
}

export type showsUncheckedUpdateManyWithoutRalliesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  show_number?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  details?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  created_at?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type ShowsCountOutputType
 */

export type ShowsCountOutputType = {
  participations: number
}

export type ShowsCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  participations?: boolean | ShowsCountOutputTypeCountParticipationsArgs
}

/**
 * ShowsCountOutputType without action
 */
export type ShowsCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ShowsCountOutputType
   */
  select?: Prisma.ShowsCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ShowsCountOutputType without action
 */
export type ShowsCountOutputTypeCountParticipationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.participationsWhereInput
}


export type showsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  rally_id?: boolean
  show_number?: boolean
  name?: boolean
  details?: boolean
  created_at?: boolean
  participations?: boolean | Prisma.shows$participationsArgs<ExtArgs>
  rallies?: boolean | Prisma.shows$ralliesArgs<ExtArgs>
  _count?: boolean | Prisma.ShowsCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["shows"]>

export type showsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  rally_id?: boolean
  show_number?: boolean
  name?: boolean
  details?: boolean
  created_at?: boolean
  rallies?: boolean | Prisma.shows$ralliesArgs<ExtArgs>
}, ExtArgs["result"]["shows"]>

export type showsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  rally_id?: boolean
  show_number?: boolean
  name?: boolean
  details?: boolean
  created_at?: boolean
  rallies?: boolean | Prisma.shows$ralliesArgs<ExtArgs>
}, ExtArgs["result"]["shows"]>

export type showsSelectScalar = {
  id?: boolean
  rally_id?: boolean
  show_number?: boolean
  name?: boolean
  details?: boolean
  created_at?: boolean
}

export type showsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "rally_id" | "show_number" | "name" | "details" | "created_at", ExtArgs["result"]["shows"]>
export type showsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  participations?: boolean | Prisma.shows$participationsArgs<ExtArgs>
  rallies?: boolean | Prisma.shows$ralliesArgs<ExtArgs>
  _count?: boolean | Prisma.ShowsCountOutputTypeDefaultArgs<ExtArgs>
}
export type showsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  rallies?: boolean | Prisma.shows$ralliesArgs<ExtArgs>
}
export type showsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  rallies?: boolean | Prisma.shows$ralliesArgs<ExtArgs>
}

export type $showsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "shows"
  objects: {
    participations: Prisma.$participationsPayload<ExtArgs>[]
    rallies: Prisma.$ralliesPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    rally_id: number | null
    show_number: number
    name: string
    details: string | null
    created_at: Date | null
  }, ExtArgs["result"]["shows"]>
  composites: {}
}

export type showsGetPayload<S extends boolean | null | undefined | showsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$showsPayload, S>

export type showsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<showsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ShowsCountAggregateInputType | true
  }

export interface showsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['shows'], meta: { name: 'shows' } }
  /**
   * Find zero or one Shows that matches the filter.
   * @param {showsFindUniqueArgs} args - Arguments to find a Shows
   * @example
   * // Get one Shows
   * const shows = await prisma.shows.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends showsFindUniqueArgs>(args: Prisma.SelectSubset<T, showsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__showsClient<runtime.Types.Result.GetResult<Prisma.$showsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Shows that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {showsFindUniqueOrThrowArgs} args - Arguments to find a Shows
   * @example
   * // Get one Shows
   * const shows = await prisma.shows.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends showsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, showsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__showsClient<runtime.Types.Result.GetResult<Prisma.$showsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Shows that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {showsFindFirstArgs} args - Arguments to find a Shows
   * @example
   * // Get one Shows
   * const shows = await prisma.shows.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends showsFindFirstArgs>(args?: Prisma.SelectSubset<T, showsFindFirstArgs<ExtArgs>>): Prisma.Prisma__showsClient<runtime.Types.Result.GetResult<Prisma.$showsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Shows that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {showsFindFirstOrThrowArgs} args - Arguments to find a Shows
   * @example
   * // Get one Shows
   * const shows = await prisma.shows.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends showsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, showsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__showsClient<runtime.Types.Result.GetResult<Prisma.$showsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Shows that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {showsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Shows
   * const shows = await prisma.shows.findMany()
   * 
   * // Get first 10 Shows
   * const shows = await prisma.shows.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const showsWithIdOnly = await prisma.shows.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends showsFindManyArgs>(args?: Prisma.SelectSubset<T, showsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$showsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Shows.
   * @param {showsCreateArgs} args - Arguments to create a Shows.
   * @example
   * // Create one Shows
   * const Shows = await prisma.shows.create({
   *   data: {
   *     // ... data to create a Shows
   *   }
   * })
   * 
   */
  create<T extends showsCreateArgs>(args: Prisma.SelectSubset<T, showsCreateArgs<ExtArgs>>): Prisma.Prisma__showsClient<runtime.Types.Result.GetResult<Prisma.$showsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Shows.
   * @param {showsCreateManyArgs} args - Arguments to create many Shows.
   * @example
   * // Create many Shows
   * const shows = await prisma.shows.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends showsCreateManyArgs>(args?: Prisma.SelectSubset<T, showsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Shows and returns the data saved in the database.
   * @param {showsCreateManyAndReturnArgs} args - Arguments to create many Shows.
   * @example
   * // Create many Shows
   * const shows = await prisma.shows.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Shows and only return the `id`
   * const showsWithIdOnly = await prisma.shows.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends showsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, showsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$showsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Shows.
   * @param {showsDeleteArgs} args - Arguments to delete one Shows.
   * @example
   * // Delete one Shows
   * const Shows = await prisma.shows.delete({
   *   where: {
   *     // ... filter to delete one Shows
   *   }
   * })
   * 
   */
  delete<T extends showsDeleteArgs>(args: Prisma.SelectSubset<T, showsDeleteArgs<ExtArgs>>): Prisma.Prisma__showsClient<runtime.Types.Result.GetResult<Prisma.$showsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Shows.
   * @param {showsUpdateArgs} args - Arguments to update one Shows.
   * @example
   * // Update one Shows
   * const shows = await prisma.shows.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends showsUpdateArgs>(args: Prisma.SelectSubset<T, showsUpdateArgs<ExtArgs>>): Prisma.Prisma__showsClient<runtime.Types.Result.GetResult<Prisma.$showsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Shows.
   * @param {showsDeleteManyArgs} args - Arguments to filter Shows to delete.
   * @example
   * // Delete a few Shows
   * const { count } = await prisma.shows.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends showsDeleteManyArgs>(args?: Prisma.SelectSubset<T, showsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Shows.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {showsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Shows
   * const shows = await prisma.shows.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends showsUpdateManyArgs>(args: Prisma.SelectSubset<T, showsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Shows and returns the data updated in the database.
   * @param {showsUpdateManyAndReturnArgs} args - Arguments to update many Shows.
   * @example
   * // Update many Shows
   * const shows = await prisma.shows.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Shows and only return the `id`
   * const showsWithIdOnly = await prisma.shows.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends showsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, showsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$showsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Shows.
   * @param {showsUpsertArgs} args - Arguments to update or create a Shows.
   * @example
   * // Update or create a Shows
   * const shows = await prisma.shows.upsert({
   *   create: {
   *     // ... data to create a Shows
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Shows we want to update
   *   }
   * })
   */
  upsert<T extends showsUpsertArgs>(args: Prisma.SelectSubset<T, showsUpsertArgs<ExtArgs>>): Prisma.Prisma__showsClient<runtime.Types.Result.GetResult<Prisma.$showsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Shows.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {showsCountArgs} args - Arguments to filter Shows to count.
   * @example
   * // Count the number of Shows
   * const count = await prisma.shows.count({
   *   where: {
   *     // ... the filter for the Shows we want to count
   *   }
   * })
  **/
  count<T extends showsCountArgs>(
    args?: Prisma.Subset<T, showsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ShowsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Shows.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ShowsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ShowsAggregateArgs>(args: Prisma.Subset<T, ShowsAggregateArgs>): Prisma.PrismaPromise<GetShowsAggregateType<T>>

  /**
   * Group by Shows.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {showsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends showsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: showsGroupByArgs['orderBy'] }
      : { orderBy?: showsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, showsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetShowsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the shows model
 */
readonly fields: showsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for shows.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__showsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  participations<T extends Prisma.shows$participationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.shows$participationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$participationsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  rallies<T extends Prisma.shows$ralliesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.shows$ralliesArgs<ExtArgs>>): Prisma.Prisma__ralliesClient<runtime.Types.Result.GetResult<Prisma.$ralliesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the shows model
 */
export interface showsFieldRefs {
  readonly id: Prisma.FieldRef<"shows", 'Int'>
  readonly rally_id: Prisma.FieldRef<"shows", 'Int'>
  readonly show_number: Prisma.FieldRef<"shows", 'Int'>
  readonly name: Prisma.FieldRef<"shows", 'String'>
  readonly details: Prisma.FieldRef<"shows", 'String'>
  readonly created_at: Prisma.FieldRef<"shows", 'DateTime'>
}
    

// Custom InputTypes
/**
 * shows findUnique
 */
export type showsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the shows
   */
  select?: Prisma.showsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the shows
   */
  omit?: Prisma.showsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.showsInclude<ExtArgs> | null
  /**
   * Filter, which shows to fetch.
   */
  where: Prisma.showsWhereUniqueInput
}

/**
 * shows findUniqueOrThrow
 */
export type showsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the shows
   */
  select?: Prisma.showsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the shows
   */
  omit?: Prisma.showsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.showsInclude<ExtArgs> | null
  /**
   * Filter, which shows to fetch.
   */
  where: Prisma.showsWhereUniqueInput
}

/**
 * shows findFirst
 */
export type showsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the shows
   */
  select?: Prisma.showsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the shows
   */
  omit?: Prisma.showsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.showsInclude<ExtArgs> | null
  /**
   * Filter, which shows to fetch.
   */
  where?: Prisma.showsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of shows to fetch.
   */
  orderBy?: Prisma.showsOrderByWithRelationInput | Prisma.showsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for shows.
   */
  cursor?: Prisma.showsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` shows from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` shows.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of shows.
   */
  distinct?: Prisma.ShowsScalarFieldEnum | Prisma.ShowsScalarFieldEnum[]
}

/**
 * shows findFirstOrThrow
 */
export type showsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the shows
   */
  select?: Prisma.showsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the shows
   */
  omit?: Prisma.showsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.showsInclude<ExtArgs> | null
  /**
   * Filter, which shows to fetch.
   */
  where?: Prisma.showsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of shows to fetch.
   */
  orderBy?: Prisma.showsOrderByWithRelationInput | Prisma.showsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for shows.
   */
  cursor?: Prisma.showsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` shows from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` shows.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of shows.
   */
  distinct?: Prisma.ShowsScalarFieldEnum | Prisma.ShowsScalarFieldEnum[]
}

/**
 * shows findMany
 */
export type showsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the shows
   */
  select?: Prisma.showsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the shows
   */
  omit?: Prisma.showsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.showsInclude<ExtArgs> | null
  /**
   * Filter, which shows to fetch.
   */
  where?: Prisma.showsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of shows to fetch.
   */
  orderBy?: Prisma.showsOrderByWithRelationInput | Prisma.showsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing shows.
   */
  cursor?: Prisma.showsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` shows from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` shows.
   */
  skip?: number
  distinct?: Prisma.ShowsScalarFieldEnum | Prisma.ShowsScalarFieldEnum[]
}

/**
 * shows create
 */
export type showsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the shows
   */
  select?: Prisma.showsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the shows
   */
  omit?: Prisma.showsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.showsInclude<ExtArgs> | null
  /**
   * The data needed to create a shows.
   */
  data: Prisma.XOR<Prisma.showsCreateInput, Prisma.showsUncheckedCreateInput>
}

/**
 * shows createMany
 */
export type showsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many shows.
   */
  data: Prisma.showsCreateManyInput | Prisma.showsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * shows createManyAndReturn
 */
export type showsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the shows
   */
  select?: Prisma.showsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the shows
   */
  omit?: Prisma.showsOmit<ExtArgs> | null
  /**
   * The data used to create many shows.
   */
  data: Prisma.showsCreateManyInput | Prisma.showsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.showsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * shows update
 */
export type showsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the shows
   */
  select?: Prisma.showsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the shows
   */
  omit?: Prisma.showsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.showsInclude<ExtArgs> | null
  /**
   * The data needed to update a shows.
   */
  data: Prisma.XOR<Prisma.showsUpdateInput, Prisma.showsUncheckedUpdateInput>
  /**
   * Choose, which shows to update.
   */
  where: Prisma.showsWhereUniqueInput
}

/**
 * shows updateMany
 */
export type showsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update shows.
   */
  data: Prisma.XOR<Prisma.showsUpdateManyMutationInput, Prisma.showsUncheckedUpdateManyInput>
  /**
   * Filter which shows to update
   */
  where?: Prisma.showsWhereInput
  /**
   * Limit how many shows to update.
   */
  limit?: number
}

/**
 * shows updateManyAndReturn
 */
export type showsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the shows
   */
  select?: Prisma.showsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the shows
   */
  omit?: Prisma.showsOmit<ExtArgs> | null
  /**
   * The data used to update shows.
   */
  data: Prisma.XOR<Prisma.showsUpdateManyMutationInput, Prisma.showsUncheckedUpdateManyInput>
  /**
   * Filter which shows to update
   */
  where?: Prisma.showsWhereInput
  /**
   * Limit how many shows to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.showsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * shows upsert
 */
export type showsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the shows
   */
  select?: Prisma.showsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the shows
   */
  omit?: Prisma.showsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.showsInclude<ExtArgs> | null
  /**
   * The filter to search for the shows to update in case it exists.
   */
  where: Prisma.showsWhereUniqueInput
  /**
   * In case the shows found by the `where` argument doesn't exist, create a new shows with this data.
   */
  create: Prisma.XOR<Prisma.showsCreateInput, Prisma.showsUncheckedCreateInput>
  /**
   * In case the shows was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.showsUpdateInput, Prisma.showsUncheckedUpdateInput>
}

/**
 * shows delete
 */
export type showsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the shows
   */
  select?: Prisma.showsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the shows
   */
  omit?: Prisma.showsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.showsInclude<ExtArgs> | null
  /**
   * Filter which shows to delete.
   */
  where: Prisma.showsWhereUniqueInput
}

/**
 * shows deleteMany
 */
export type showsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which shows to delete
   */
  where?: Prisma.showsWhereInput
  /**
   * Limit how many shows to delete.
   */
  limit?: number
}

/**
 * shows.participations
 */
export type shows$participationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the participations
   */
  select?: Prisma.participationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the participations
   */
  omit?: Prisma.participationsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.participationsInclude<ExtArgs> | null
  where?: Prisma.participationsWhereInput
  orderBy?: Prisma.participationsOrderByWithRelationInput | Prisma.participationsOrderByWithRelationInput[]
  cursor?: Prisma.participationsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ParticipationsScalarFieldEnum | Prisma.ParticipationsScalarFieldEnum[]
}

/**
 * shows.rallies
 */
export type shows$ralliesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the rallies
   */
  select?: Prisma.ralliesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the rallies
   */
  omit?: Prisma.ralliesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ralliesInclude<ExtArgs> | null
  where?: Prisma.ralliesWhereInput
}

/**
 * shows without action
 */
export type showsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the shows
   */
  select?: Prisma.showsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the shows
   */
  omit?: Prisma.showsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.showsInclude<ExtArgs> | null
}
