
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  brands: 'brands',
  directivos: 'directivos',
  houses: 'houses',
  members: 'members',
  participations: 'participations',
  rallies: 'rallies',
  shows: 'shows'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const BrandsScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  created_at: 'created_at'
} as const

export type BrandsScalarFieldEnum = (typeof BrandsScalarFieldEnum)[keyof typeof BrandsScalarFieldEnum]


export const DirectivosScalarFieldEnum = {
  id: 'id',
  house_id: 'house_id',
  member_id: 'member_id',
  role: 'role',
  start_date: 'start_date',
  end_date: 'end_date'
} as const

export type DirectivosScalarFieldEnum = (typeof DirectivosScalarFieldEnum)[keyof typeof DirectivosScalarFieldEnum]


export const HousesScalarFieldEnum = {
  id: 'id',
  brand_id: 'brand_id',
  name: 'name',
  description: 'description',
  created_at: 'created_at'
} as const

export type HousesScalarFieldEnum = (typeof HousesScalarFieldEnum)[keyof typeof HousesScalarFieldEnum]


export const MembersScalarFieldEnum = {
  id: 'id',
  house_id: 'house_id',
  cuenta: 'cuenta',
  nombre: 'nombre',
  activo: 'activo',
  fecha_ingreso: 'fecha_ingreso',
  fecha_salida: 'fecha_salida',
  created_at: 'created_at',
  user_id: 'user_id'
} as const

export type MembersScalarFieldEnum = (typeof MembersScalarFieldEnum)[keyof typeof MembersScalarFieldEnum]


export const ParticipationsScalarFieldEnum = {
  id: 'id',
  member_id: 'member_id',
  show_id: 'show_id',
  status: 'status',
  points: 'points',
  updated_at: 'updated_at',
  notes: 'notes'
} as const

export type ParticipationsScalarFieldEnum = (typeof ParticipationsScalarFieldEnum)[keyof typeof ParticipationsScalarFieldEnum]


export const RalliesScalarFieldEnum = {
  id: 'id',
  brand_id: 'brand_id',
  month: 'month',
  rally_number: 'rally_number',
  start_day: 'start_day',
  end_day: 'end_day',
  slot_ini: 'slot_ini',
  slot_fin: 'slot_fin',
  created_at: 'created_at'
} as const

export type RalliesScalarFieldEnum = (typeof RalliesScalarFieldEnum)[keyof typeof RalliesScalarFieldEnum]


export const ShowsScalarFieldEnum = {
  id: 'id',
  rally_id: 'rally_id',
  show_number: 'show_number',
  name: 'name',
  details: 'details',
  created_at: 'created_at'
} as const

export type ShowsScalarFieldEnum = (typeof ShowsScalarFieldEnum)[keyof typeof ShowsScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

