
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/brands'
export type * from './models/directivos'
export type * from './models/houses'
export type * from './models/members'
export type * from './models/participations'
export type * from './models/rallies'
export type * from './models/shows'
export type * from './commonInputTypes'